"""Session 116 (DRAFT, not sealed; amended after the pre-seal check, ROADMAP 116 items 3-4): mutants of obs116.py - each
must be killed by test_obs116.py.  At the seal they are run through the frozen mutlib (--control, work dir
C:/kyty/s116/work*) on the sealed copy; this loop is the draft check (one fresh `python test_obs116.py <mutant>` per
mutant, mutant files in C:/kyty/s116/work_mut116)."""
import subprocess
import sys
from pathlib import Path

STAGE = Path('C:/kyty/s116/work_mut116')
SRC = Path('C:/kyty/s116/obs116.py').read_text(encoding='utf-8')
MUTANTS = [
    # constants (the suite pins them in CONSTANTS and uses them at their edges)
    ('min_rows', 'MIN_ROWS = 6000', 'MIN_ROWS = 5999'),
    ('hold_s', 'HOLD_S = 300', 'HOLD_S = 299'),
    ('id_hold_tol', 'ID_HOLD_TOL = 16', 'ID_HOLD_TOL = 17'),
    ('id_emit_tol', 'ID_EMIT_TOL = 256', 'ID_EMIT_TOL = 257'),
    ('proc_n_tol', 'PROC_N_TOL = 16', 'PROC_N_TOL = 17'),
    ('proc_wall_pct', 'PROC_WALL_PCT = 101', 'PROC_WALL_PCT = 102'),
    ('cover_lo_c', 'HOLD_COVER_LO_PCT = 98', 'HOLD_COVER_LO_PCT = 97'),
    ('cover_hi_c', 'HOLD_COVER_HI_PCT = 102', 'HOLD_COVER_HI_PCT = 103'),
    ('idle_max', 'IDLE_GPU_MAX = 10', 'IDLE_GPU_MAX = 11'),
    ('gates_sha', "GATES_SHA = '678f", "GATES_SHA = '578f"),
    ('pred_path', "PRED_PATH = 'C:/kyty/s116/pred/01_obs116.md'", "PRED_PATH = 'C:/kyty/s116/pred/02_obs116.md'"),
    ('bda_new_c', 'BDA_NEW_MAX = 300', 'BDA_NEW_MAX = 301'),
    ('bda_old_c', 'BDA_OLD_MIN = 600', 'BDA_OLD_MIN = 599'),
    ('build_sha', "BUILD_SHA = 'd3a9", "BUILD_SHA = 'd3a8"),
    ('env_wall', "'KYTY_GPU_WALL': '1',", "'KYTY_GPU_WALLX': '1',"),
    ('env_markers', "'KYTY_GPU_MARKERS': '0',", "'KYTY_GPU_MARKERS': '2',"),
    ('env_lite', "'KYTY_FRAME_TRACE': 'lite',", "'KYTY_FRAME_TRACE': '1',"),
    ('vk_allowed', "VK_ALLOWED = ('VK_SDK_PATH',)", "VK_ALLOWED = ('VK_SDK_PATH', 'VK_LAYER_PATH')"),
    ('marker_fatal', "b'fatal', ", ''),
    ('marker_hang', "b'gpuhangabort', ", ''),
    ('marker_skipped', "b'asyncpipelines: skipped draw'", "b'asyncpipelines: skipped drawX'"),
    ('main_prio', "'semwait_gpu_us', 'prio_us', 'prios')", "'semwait_gpu_us', 'prios')"),
    ('ns_flip', "'gw_cmd_ns', 'flip_rsv_wait_ns')", "'gw_cmd_ns')"),
    ('hold_parts', "HOLD_PARTS = ('mh_pro_us', ", 'HOLD_PARTS = ('),
    ('named_parts', "NAMED_PARTS = ('pl_pref', ", 'NAMED_PARTS = ('),
    ('wall_parts', "WALL_PARTS = ('gw_idle', ", 'WALL_PARTS = ('),
    ('span_keys_rm', "'thread_unwalled', 'offcpu_unexplained', 'flip_rsv_wait', 'semwait_gpu_us', 'prio_us'))",
     "'thread_unwalled', 'flip_rsv_wait', 'semwait_gpu_us', 'prio_us'))"),
    ('pop_tail', "'mh_tail_us': 'mh_n',", "'mh_tail_us': 'mh_draws',"),
    ('pop_disp', "'mh_disp_us': 'mh_disp_n',", "'mh_disp_us': 'mh_draws',"),
    ('pop_wait', "'a_wait_us': 'a_hold_n',", "'a_wait_us': 'mh_n',"),
    ('pop_cmd', "'pl_cmd': 'pl_cmd_n',", "'pl_cmd': 'pl_proc_n',"),
    ('pop_flip', "'flip_rsv_wait': 'flip_rsv_wait_n',", "'flip_rsv_wait': 'gw_flip_n',"),
    ('pop_prio', "'prio_us': 'prios'}", "'prio_us': 'mh_n'}"),
    # admission checks
    ('binary', "binary=meta.get('binary_sha256') == BUILD_SHA,", 'binary=True,'),
    ('installed', 'installed_now=installed_sha == BUILD_SHA,', 'installed_now=True,'),
    ('pin_env', "pinned=env.get('KYTY_GPU_CLOCK_PIN') == '1' and pins == [1],", 'pinned=pins == [1],'),
    ('pin_list', 'and pins == [1],', 'and 1 in pins,'),
    ('pin_prefix', "            if line.startswith(b'GpuClockPin:'):", '            if PIN.match(line):'),
    ('env_exact', 'env_exact=kyty_env == ENV_EXPECT,', 'env_exact=True,'),
    ('env_superset', 'env_exact=kyty_env == ENV_EXPECT,', 'env_exact=kyty_env.items() >= ENV_EXPECT.items(),'),
    ('env_filter', "if k.startswith('KYTY_')}", '}'),
    ('env_vk', 'env_vk=all(k in VK_ALLOWED for k in vk_env),', 'env_vk=True,'),
    ('vk_filter', "vk_env = sorted(k for k in env if k.startswith('VK_'))", 'vk_env = []'),
    ('hold', "hold=meta.get('hold_s') == HOLD_S,", 'hold=True,'),
    ('att_len', 'one_ok_attempt=len(atts) == 1 and len(ok_att) == 1,', 'one_ok_attempt=len(ok_att) == 1,'),
    ('att_ok', 'one_ok_attempt=len(atts) == 1 and len(ok_att) == 1,', 'one_ok_attempt=len(atts) == 1,'),
    ('att_exit', "ok_att = [a for a in atts if a.get('outcome') == 'ok' and a.get('hold_exit') is None]",
     "ok_att = [a for a in atts if a.get('outcome') == 'ok']"),
    ('att_stable', "stable = ok_att[-1].get('stable_frame') if ok_att else None",
     "stable = atts[0].get('stable_frame') if atts else None"),
    ('prereg', r"prereg=prereg_path.replace('\\', '/') == PRED_PATH,", 'prereg=True,'),
    ('prereg_norm', r"prereg_path.replace('\\', '/') == PRED_PATH", 'prereg_path == PRED_PATH'),
    ('prereg_sha', "prereg_sha=pred_sha is not None and prereg.get('sha256') == pred_sha,", 'prereg_sha=True,'),
    ('pred_default', 'pred_sha = sha_file(PRED_PATH) if Path(PRED_PATH).is_file() else None', 'pred_sha = None'),
    ('gates_exact', "gates_exact=hashlib.sha256(gates.encode('utf-8')).hexdigest() == GATES_SHA,", 'gates_exact=True,'),
    ('gates_norm', "gates = ' '.join((meta.get('gates') or '').split())", "gates = meta.get('gates') or ''"),
    ('mut_tok', "gate_mutsite=mut_tokens == ['mutsite=1'],", 'gate_mutsite=True,'),
    ('mut_tok_any', "gate_mutsite=mut_tokens == ['mutsite=1'],", "gate_mutsite='mutsite=1' in mut_tokens,"),
    ('path_tok', "gate_pathlap=path_tokens == ['pathlap=1'],", 'gate_pathlap=True,'),
    ('path_tok_any', "gate_pathlap=path_tokens == ['pathlap=1'],", "gate_pathlap='pathlap=1' in path_tokens,"),
    ('gate_pairs', "gate_lines=gate_pairs == [('mutsite', '1'), ('pathlap', '1')] and gate_frames_ok,",
     'gate_lines=gate_frames_ok,'),
    ('gate_frames', " and gate_frames_ok,", ','),
    ('gate_frame_lt', 'int(g.group(3)) < stable', 'int(g.group(3)) <= stable'),
    ('gate_frame_none', 'all(g is not None and int(g.group(3))', 'all(g is None or int(g.group(3))'),
    ('gate_prefix', "if line.startswith(b'Gate: '):", "if line.startswith(b'Gate: m'):"),
    ('wall', "wall_logged=walls == [b'GpuWall: mode 1'],", 'wall_logged=True,'),
    ('wall_any', "wall_logged=walls == [b'GpuWall: mode 1'],", "wall_logged=b'GpuWall: mode 1' in walls,"),
    ('marker', 'no_marker=not markers,', 'no_marker=True,'),
    ('stdout', '    if so.is_file():', '    if False:'),
    ('rows_min', 'rows=len(good) >= min_rows and missing == 0,', 'rows=len(good) > min_rows and missing == 0,'),
    ('rows_missing', ' and missing == 0,', ','),
    ('rows_default', 'min_rows = MIN_ROWS if min_rows is None else min_rows',
     'min_rows = 0 if min_rows is None else min_rows'),
    ('dups', 'good = sorted(n for n in ns if n not in dups and all(', 'good = sorted(n for n in ns if all('),
    ('complete', 'rec if len(rec) == len(names) else None', 'rec if rec else None'),
    ('stable_gt', '                if n >= stable:', '                if n > stable:'),
    ('stable_any', '                if n >= stable:', '                if n >= 0:'),
    ('kinds_draw', "(LINE_DRAW, 'draw', DRAW_FIELDS), ", ''),
    ('armed_draws', "tot['mh_draws'] > 0 and ", ''),
    ('armed_disp', "tot['mh_disp_n'] > 0 and ", ''),
    ('armed_proc', "tot['pl_proc_n'] > 0 and ", ''),
    ('armed_em', "and tot['pl_em_n'] > 0", 'and True'),
    ('armed_wall', "and tot['gw_proc_n'] > 0),", 'and True),'),
    ('id_hold', "id_hold_n=abs(tot['a_hold_n'] - tot['mh_n'] - tot['mh_disp_n']) <= ID_HOLD_TOL,", 'id_hold_n=True,'),
    ('id_hold_le', "tot['mh_disp_n']) <= ID_HOLD_TOL,", "tot['mh_disp_n']) < ID_HOLD_TOL,"),
    ('id_hold_disp', "tot['a_hold_n'] - tot['mh_n'] - tot['mh_disp_n']", "tot['a_hold_n'] - tot['mh_n']"),
    ('id_hold_abs', "id_hold_n=abs(tot['a_hold_n']", "id_hold_n=(tot['a_hold_n']"),
    ('id_emit', "id_emit_n=abs(tot['pl_em_n'] - tot['mh_draws']) <= ID_EMIT_TOL,", 'id_emit_n=True,'),
    ('id_emit_le', "tot['mh_draws']) <= ID_EMIT_TOL,", "tot['mh_draws']) < ID_EMIT_TOL,"),
    ('id_emit_abs', "id_emit_n=abs(tot['pl_em_n'] - tot['mh_draws'])", "id_emit_n=(tot['pl_em_n'] - tot['mh_draws'])"),
    ('proc_n', "proc_n=abs(tot['pl_proc_n'] - tot['gw_proc_n']) <= PROC_N_TOL,", 'proc_n=True,'),
    ('proc_n_le', "tot['gw_proc_n']) <= PROC_N_TOL,", "tot['gw_proc_n']) < PROC_N_TOL,"),
    ('proc_n_abs', "proc_n=abs(tot['pl_proc_n'] - tot['gw_proc_n'])", "proc_n=(tot['pl_proc_n'] - tot['gw_proc_n'])"),
    ('proc_wall', "proc_wall=100 * raw['pl_proc_ns'] <= PROC_WALL_PCT * raw['gw_proc_ns'],", 'proc_wall=True,'),
    ('proc_wall_lt', "raw['pl_proc_ns'] <= PROC_WALL_PCT", "raw['pl_proc_ns'] < PROC_WALL_PCT"),
    ('proc_wall_swap', "proc_wall=100 * raw['pl_proc_ns'] <= PROC_WALL_PCT * raw['gw_proc_ns'],",
     "proc_wall=100 * raw['gw_proc_ns'] <= PROC_WALL_PCT * raw['pl_proc_ns'],"),
    ('cover_pos', "hold_cover=(raw['a_hold_us'] > 0 and ", 'hold_cover=(True and '),
    ('cover_lo', "100 * hold_raw >= HOLD_COVER_LO_PCT * raw['a_hold_us']", '100 * hold_raw >= 0'),
    ('cover_hi', "100 * hold_raw <= HOLD_COVER_HI_PCT * raw['a_hold_us']", '100 * hold_raw <= 10 ** 12'),
    ('cover_lo_gt', '100 * hold_raw >= HOLD_COVER_LO_PCT', '100 * hold_raw > HOLD_COVER_LO_PCT'),
    ('cover_hi_lt', '100 * hold_raw <= HOLD_COVER_HI_PCT', '100 * hold_raw < HOLD_COVER_HI_PCT'),
    ('hold_raw_parts', 'hold_raw = sum(raw[k] for k in HOLD_PARTS)', "hold_raw = raw['mh_bind_us']"),
    ('idle', 'idle=idle_ok(meta))', 'idle=True)'),
    ('idle_le', 'v <= IDLE_GPU_MAX', 'v < IDLE_GPU_MAX'),
    ('idle_type', 'isinstance(v, (int, float)) and ', ''),
    ('verdict', "res['verdict'] = 'ADMITTED' if all(checks.values()) else 'NOT_ADMITTED'", "res['verdict'] = 'ADMITTED'"),
    # the report
    ('ns_unit', 'v.update((k[:-3], x[k] / 1000.0) for k in NS_FIELDS)', 'v.update((k[:-3], x[k] / 1024.0) for k in NS_FIELDS)'),
    ('us_unit', 'v.update((k, float(x[k])) for k in US_FIELDS)', 'v.update((k, x[k] / 1000.0) for k in US_FIELDS)'),
    ('ops', "v['ops'] = v['draws'] + v['dispatches']", "v['ops'] = v['draws']"),
    ('cpu_per_op', "v['cpu_per_op'] = v['cpu_gpu_us'] / v['ops'] if", "v['cpu_per_op'] = v['cpu_gpu_us'] / v['draws'] if"),
    ('outside_wait', "v['outside'] = v['pl_proc'] - v['a_hold_us'] - v['a_wait_us']", "v['outside'] = v['pl_proc'] - v['a_hold_us']"),
    ('residue', "v['residue'] = v['outside'] - v['named']", "v['residue'] = v['outside']"),
    ('noflip', "v['residue_noflip'] = v['residue'] - v['gw_flip']", "v['residue_noflip'] = v['residue']"),
    ('s96', "(v['a_hold_us'] - v['mh_pres_us'])", "(v['a_hold_us'] + v['mh_pres_us'])"),
    ('attributed_wait', "v['attributed'] = v['hold'] + v['a_wait_us'] + v['named']", "v['attributed'] = v['hold'] + v['named']"),
    ('remainder', "v['remainder'] = v['cpu_gpu_us'] - v['attributed']", "v['remainder'] = v['dt_us'] - v['attributed']"),
    ('unwalled', "v['thread_unwalled'] = v['dt_us'] - sum(v[k] for k in WALL_PARTS)", "v['thread_unwalled'] = v['dt_us'] - v['gw_proc']"),
    ('offcpu', "v['offcpu'] = v['dt_us'] - v['cpu_gpu_us']", "v['offcpu'] = v['cpu_gpu_us'] - v['dt_us']"),
    ('offcpu_unexpl', "(v['gw_idle'] + v['gw_blk'] + v['gw_flip'])", "(v['gw_idle'] + v['gw_blk'])"),
    ('mean', 'mean=sum(col) / len(col) if col else None,', 'mean=statistics.median(col) if col else None,'),
    ('sum_entry', 'sum=sums[k],', 'sum=sums[k] / len(values),'),
    ('median', 'median=statistics.median(col) if col else None)', 'median=sum(col) / len(col) if col else None)'),
    ('span_off', "            entry['median'] = None", '            pass'),
    ('share', "entry['share_cpu'] = sums[k] / cpu if cpu else None", "entry['share_cpu'] = sums[k] / ops if cpu else None"),
    ('per_op', "entry['per_op'] = sums[k] / ops if ops else None", "entry['per_op'] = sums[k] / cpu if ops else None"),
    ('per_unit', "entry['per_unit'] = sums[k] / sums[pop] if sums[pop] else None",
     "entry['per_unit'] = sums[k] / len(values) if sums[pop] else None"),
    ('sum_ratio', "fields['cpu_per_op']['sum_ratio'] = cpu / ops if ops else None",
     "fields['cpu_per_op']['sum_ratio'] = fields['cpu_per_op']['mean']"),
    ('bda_le', 'if median <= BDA_NEW_MAX:', 'if median < BDA_NEW_MAX:'),
    ('bda_ge', 'if median >= BDA_OLD_MIN:', 'if median > BDA_OLD_MIN:'),
    ('bda_none', "return 'UNKNOWN'", "return 'NEW'"),
    ('bda_med', "bda_med = fields['bda_scan']['median']", "bda_med = fields['bda_scan']['mean']"),
    ('pred_hi', 'lo <= mean <= hi)', 'lo <= mean < hi)'),
    ('pred_lo', 'in_range=mean is not None and lo <= mean', 'in_range=mean is not None and lo < mean'),
    ('span', "span_s=sums['dt_us'] / 1e6", "span_s=sums['cpu_gpu_us'] / 1e6"),
    ('report_rows', 'n_rows=len(values)', 'n_rows=len(values) - 1'),
    ('report_stable', 'stable_frame=stable, span_s', 'stable_frame=None, span_s'),
    ('cons_hold', "hold_over_a_hold=sums['hold'] / sums['a_hold_us']", "hold_over_a_hold=sums['hold'] / sums['cpu_gpu_us']"),
    ('cons_emit', "emit_split_over_mh_emit=sums['emit_split'] / sums['mh_emit_us']",
     "emit_split_over_mh_emit=sums['emit_split'] / sums['hold']"),
    ('cons_proc', "pl_proc_over_gw_proc=sums['pl_proc'] / sums['gw_proc']", "pl_proc_over_gw_proc=sums['gw_proc'] / sums['pl_proc']"),
    ('cons_mh_n', "mh_n_over_draws=sums['mh_n'] / sums['draws']", "mh_n_over_draws=sums['mh_draws'] / sums['draws']"),
    ('cons_disp', "mh_disp_n_over_dispatches=sums['mh_disp_n'] / sums['dispatches']",
     "mh_disp_n_over_dispatches=sums['mh_disp_n'] / sums['ops']"),
    ('cons_hold_n', "a_hold_n_minus_mh=sums['a_hold_n'] - sums['mh_n'] - sums['mh_disp_n'],",
     "a_hold_n_minus_mh=sums['a_hold_n'] - sums['mh_n'],"),
    ('cons_em', "pl_em_n_minus_mh_draws=sums['pl_em_n'] - sums['mh_draws'],", "pl_em_n_minus_mh_draws=sums['pl_em_n'] - sums['mh_n'],"),
    ('cons_proc_n', "pl_proc_n_minus_gw_proc_n=sums['pl_proc_n'] - sums['gw_proc_n'])", "pl_proc_n_minus_gw_proc_n=sums['pl_proc_n'])"),
    ('text_flag', "out.append('REPORT OF A NOT_ADMITTED RUN - NOT TO BE QUOTED')", 'pass'),
    ('text_flag_if', "        if res['verdict'] != 'ADMITTED':", '        if False:'),
    ('text_none', "out.append('REPORT: no complete scene rows')", 'pass'),
    ('text_caveat', "out.append('  caveat ' + c)", 'pass'),
]
STAGE.mkdir(parents=True, exist_ok=True)
killed = 0
for name, old, new in MUTANTS:
    if SRC.count(old) != 1:
        print('%-16s ANCHOR x%d' % (name, SRC.count(old)))
        continue
    path = STAGE / ('mut_obs116_%s.py' % name)
    path.write_text(SRC.replace(old, new), encoding='utf-8', newline='\n')
    r = subprocess.run([sys.executable, 'C:/kyty/s116/test_obs116.py', str(path)], capture_output=True, text=True)
    killed += r.returncode != 0
    print('%-16s %s' % (name, 'killed' if r.returncode != 0 else 'SURVIVED'))
    path.unlink()
print('killed %d of %d' % (killed, len(MUTANTS)))
