"""Session 118: mutants of spk118.py - each must be killed by test_spk118.py.  At the seal they are run through the frozen
mutlib v4.1 (--control --no-memo, work dir C:/kyty/s118/work*) on the sealed copy; this loop is the draft check (one fresh
`python test_spk118.py <mutant>` per mutant, mutant files in C:/kyty/s118/work_mut118)."""
import subprocess
import sys
from pathlib import Path

STAGE = Path('C:/kyty/s118/work_mut118')
SRC = Path('C:/kyty/s118/spk118.py').read_text(encoding='utf-8')
MUTANTS = [
    # constants
    ('hold_s', 'HOLD_S = 300', 'HOLD_S = 299'),
    ('period', 'PERIOD = 90', 'PERIOD = 91'),
    ('start', 'START = 1800', 'START = 1890'),
    ('keep_lo', 'KEEP = (10, 89)', 'KEEP = (5, 89)'),
    ('keep_hi', 'KEEP = (10, 89)', 'KEEP = (10, 90)'),
    ('abba', 'ABBA = (0, 1, 1, 0)', 'ABBA = (0, 1, 0, 1)'),
    ('arm_text0', "ARM_TEXT = ('spine=2 slicecen=1", "ARM_TEXT = ('spine=1 slicecen=1"),
    ('arm_text1', "            'spine=0 slicecen=0 takelap=1 bindlap=1 pathlap=1 mutsite=1')",
     "            'spine=0 slicecen=0 takelap=1 bindlap=1 pathlap=1 mutsite=0')"),
    ('min_blocks', 'MIN_BLOCKS = 20', 'MIN_BLOCKS = 19'),
    ('cmp_pct', 'CMP_MIN_PCT = 90', 'CMP_MIN_PCT = 89'),
    ('safe_pct', 'SAFE_MAX_PCT = 10', 'SAFE_MAX_PCT = 11'),
    ('el_lo', 'EL_OPS_LO_PCT = 95', 'EL_OPS_LO_PCT = 94'),
    ('el_hi', 'EL_OPS_HI_PCT = 105', 'EL_OPS_HI_PCT = 106'),
    ('k3_share', 'K3_SHARE_PERMILLE = 250', 'K3_SHARE_PERMILLE = 251'),
    ('k4_bar', 'K4_DEP_MAX_PERMILLE = 300', 'K4_DEP_MAX_PERMILLE = 301'),
    ('k4_min', 'K4_MIN_PCT = 50', 'K4_MIN_PCT = 51'),
    ('idle_max', 'IDLE_GPU_MAX = 10', 'IDLE_GPU_MAX = 11'),
    ('gates_sha', "GATES_SHA = '91da", "GATES_SHA = '81da"),
    ('pred_path', "PRED_PATH = 'C:/kyty/s118/pred/01_spk118.md'", "PRED_PATH = 'C:/kyty/s118/pred/02_spk118.md'"),
    ('schedule', "SCHEDULE = '90+1800:' + ARM_TEXT[0] + '|' + ARM_TEXT[1]", "SCHEDULE = '90+1800:' + ARM_TEXT[1] + '|' + ARM_TEXT[0]"),
    ('env_abba', "    'KYTY_GATE_SCHEDULE_ABBA': '1',", "    'KYTY_GATE_SCHEDULE_ABBAX': '1',"),
    ('env_markers', "    'KYTY_GPU_MARKERS': '0',", "    'KYTY_GPU_MARKERS': '2',"),
    ('vk_allowed', "VK_ALLOWED = ('VK_SDK_PATH',)", "VK_ALLOWED = ('VK_SDK_PATH', 'VK_LAYER_PATH')"),
    ('marker_fatal', "           b'std::terminate', b'abort()', b'fatal', b'unhandled exception', b'--- error ---',",
     "           b'std::terminate', b'abort()', b'unhandled exception', b'--- error ---',"),
    ('marker_hang', "MARKERS = (b'gpuhangabort', ", 'MARKERS = ('),
    ('draw_fields', "DRAW_FIELDS = ('da_take_us', 'bda_scan')", "DRAW_FIELDS = ('da_take_us',)"),
    ('k5_raw_cram', "K5_RAW = ('spine_bad', 'spine_misal', 'cram_write')", "K5_RAW = ('spine_bad', 'spine_misal')"),
    ('c_lines', "C_LINES = (b'SpineCarry:',)", "C_LINES = (b'SpineCarryX:',)"),
    ('k5_lines', "K5_LINES = (b'SpineMismatch:', b'SpineMisalign:')", "K5_LINES = (b'SpineMismatch:',)"),
    # admission
    ('binary', "        binary=meta.get('binary_sha256') == BUILD_SHA,", '        binary=True,'),
    ('installed', '        installed_now=installed_sha == BUILD_SHA,', '        installed_now=True,'),
    ('pin_env', "        pinned=env.get('KYTY_GPU_CLOCK_PIN') == '1' and pins == [1],", '        pinned=pins == [1],'),
    ('pin_list', "        pinned=env.get('KYTY_GPU_CLOCK_PIN') == '1' and pins == [1],",
     "        pinned=env.get('KYTY_GPU_CLOCK_PIN') == '1' and 1 in pins,"),
    ('pin_parse', '                pins.append(int(mp.group(1)) if mp else -1)', '                pins.append(int(mp.group(1)) if mp else 1)'),
    ('env_exact', '        env_exact=kyty_env == ENV_EXPECT,', '        env_exact=True,'),
    ('env_superset', '        env_exact=kyty_env == ENV_EXPECT,', '        env_exact=kyty_env.items() >= ENV_EXPECT.items(),'),
    ('env_vk', '        env_vk=all(k in VK_ALLOWED for k in vk_env),', '        env_vk=True,'),
    ('hold', "        hold=meta.get('hold_s') == HOLD_S,", '        hold=True,'),
    ('att_len', '        one_ok_attempt=len(atts) == 1 and len(ok_att) == 1,', '        one_ok_attempt=len(ok_att) == 1,'),
    ('att_ok', '        one_ok_attempt=len(atts) == 1 and len(ok_att) == 1,', '        one_ok_attempt=len(atts) == 1,'),
    ('hold_exit', "    ok_att = [a for a in atts if a.get('outcome') == 'ok' and a.get('hold_exit') is None]",
     "    ok_att = [a for a in atts if a.get('outcome') == 'ok']"),
    ('prereg', "        prereg=prereg_path.replace('\\\\', '/') == PRED_PATH,", '        prereg=True,'),
    ('prereg_sha', "        prereg_sha=pred_sha is not None and prereg.get('sha256') == pred_sha,", '        prereg_sha=True,'),
    ('gates_hash', "        gates_exact=hashlib.sha256(gates.encode('utf-8')).hexdigest() == GATES_SHA,", '        gates_exact=True,'),
    ('gates_norm', "    gates = ' '.join((meta.get('gates') or '').split())", "    gates = meta.get('gates') or ''"),
    ('gate_lines', '        gate_lines=gate_lines_ok(gate_lines, blocks),', '        gate_lines=True,'),
    ('gate_none', '        if m is None:\n            return False\n        name =', '        if m is None:\n            continue\n        name ='),
    ('gate_name', "        if name not in ARM_VALUES[0] or (frame - START) % PERIOD != 0 or frame < START:",
     "        if (frame - START) % PERIOD != 0 or frame < START:"),
    ('gate_mod', "        if name not in ARM_VALUES[0] or (frame - START) % PERIOD != 0 or frame < START:",
     "        if name not in ARM_VALUES[0] or frame < START:"),
    ('gate_value', "        if block not in blocks or m.group(2).decode() != ARM_VALUES[blocks[block]][name]:",
     '        if block not in blocks:'),
    ('arms', '        arms=arms_fine,', '        arms=True,'),
    ('arms_count', '        if arms != 2 or period != PERIOD', '        if period != PERIOD'),
    ('arms_period', '        if arms != 2 or period != PERIOD or abba != 1', '        if arms != 2 or abba != 1'),
    ('arms_abba', ' or abba != 1 or arm not in (0, 1)', ' or arm not in (0, 1)'),
    ('arms_text', ' or text != ARM_TEXT[arm]:', ':'),
    ('arms_frame', '        if frame != START + PERIOD * block or ABBA[block % 4] != arm', '        if ABBA[block % 4] != arm'),
    ('arms_order', ' or ABBA[block % 4] != arm or block in blocks:', ' or block in blocks:'),
    ('arms_dup', ' or ABBA[block % 4] != arm or block in blocks:', ' or ABBA[block % 4] != arm:'),
    ('arms_consecutive', '    ok = bool(blocks) and sorted(blocks) == list(range(len(blocks)))', '    ok = bool(blocks)'),
    ('arms_none', '    for g in gate_arms:\n        if g is None:', '    for g in [x for x in gate_arms if x is not None]:\n        if g is None:'),
    ('spine_logged', '        spine_logged=len(spine_lines) == 1,', '        spine_logged=len(spine_lines) >= 1,'),
    ('no_marker', '        no_marker=not markers,', '        no_marker=True,'),
    ('stdout_markers', "    so = Path(root) / ('stdout_%s.txt' % tag)", "    so = Path(root) / ('stdout_%s.txtX' % tag)"),
    ('blocks_arm1', '        blocks=complete_blocks[0] >= min_blocks and complete_blocks[1] >= min_blocks,',
     '        blocks=complete_blocks[0] >= min_blocks,'),
    ('blocks_ge', '        blocks=complete_blocks[0] >= min_blocks and complete_blocks[1] >= min_blocks,',
     '        blocks=complete_blocks[0] > min_blocks and complete_blocks[1] >= min_blocks,'),
    ('block_label_arm', "        if not all(complete(n) and seen['main'][n]['arm'] == arm and seen['main'][n]['blk'] == b for n in frames):",
     "        if not all(complete(n) and seen['main'][n]['blk'] == b for n in frames):"),
    ('block_label_blk', "        if not all(complete(n) and seen['main'][n]['arm'] == arm and seen['main'][n]['blk'] == b for n in frames):",
     "        if not all(complete(n) and seen['main'][n]['arm'] == arm for n in frames):"),
    ('complete_dups', '        return n not in dups and all(seen[k].get(n) is not None for k in seen)',
     '        return all(seen[k].get(n) is not None for k in seen)'),
    ('rec_full', '                seen[kind][n] = rec if len(rec) == len(names) else None', '                seen[kind][n] = rec'),
    ('armed_spine', "        armed=(ksum(0, 'spine_n') > 0 and ksum(0, 'sc_frames') > 0 and ksum(0, 'carry_cmp') > 0",
     "        armed=(ksum(0, 'sc_frames') > 0 and ksum(0, 'carry_cmp') > 0"),
    ('armed_sc', "        armed=(ksum(0, 'spine_n') > 0 and ksum(0, 'sc_frames') > 0 and ksum(0, 'carry_cmp') > 0",
     "        armed=(ksum(0, 'spine_n') > 0 and ksum(0, 'carry_cmp') > 0"),
    ('armed_carry', "        armed=(ksum(0, 'spine_n') > 0 and ksum(0, 'sc_frames') > 0 and ksum(0, 'carry_cmp') > 0",
     "        armed=(ksum(0, 'spine_n') > 0 and ksum(0, 'sc_frames') > 0"),
    ('armed_p_take', "               and ksum(0, 'da_t_n') == 0 and ksum(1, 'da_t_n') > 0 and ksum(1, 'bl_stage_n') > 0",
     "               and ksum(1, 'da_t_n') > 0 and ksum(1, 'bl_stage_n') > 0"),
    ('armed_m_take', "               and ksum(0, 'da_t_n') == 0 and ksum(1, 'da_t_n') > 0 and ksum(1, 'bl_stage_n') > 0",
     "               and ksum(0, 'da_t_n') == 0 and ksum(1, 'bl_stage_n') > 0"),
    ('armed_m_bind', "               and ksum(0, 'da_t_n') == 0 and ksum(1, 'da_t_n') > 0 and ksum(1, 'bl_stage_n') > 0",
     "               and ksum(0, 'da_t_n') == 0 and ksum(1, 'da_t_n') > 0"),
    ('armed_m_path', "               and ksum(1, 'pl_em_n') > 0 and ksum(1, 'mh_draws') > 0 and ksum(1, 'sc_frames') == 0",
     "               and ksum(1, 'mh_draws') > 0 and ksum(1, 'sc_frames') == 0"),
    ('armed_m_mut', "               and ksum(1, 'pl_em_n') > 0 and ksum(1, 'mh_draws') > 0 and ksum(1, 'sc_frames') == 0",
     "               and ksum(1, 'pl_em_n') > 0 and ksum(1, 'sc_frames') == 0"),
    ('armed_m_sc', "               and ksum(1, 'pl_em_n') > 0 and ksum(1, 'mh_draws') > 0 and ksum(1, 'sc_frames') == 0",
     "               and ksum(1, 'pl_em_n') > 0 and ksum(1, 'mh_draws') > 0"),
    ('armed_m_spine', "               and 100 * ksum(1, 'spine_n') <= ksum(0, 'spine_n')),", '               ),'),
    ('armed_m_spine_lt', "               and 100 * ksum(1, 'spine_n') <= ksum(0, 'spine_n')),",
     "               and 100 * ksum(1, 'spine_n') < ksum(0, 'spine_n') // 4),"),
    ('el_ops_off', '        el_ops=(ops_p > 0 and 100 * ksum(0, ', '        el_ops=(True or 100 * ksum(0, '),
    ('el_ops_ops', "    ops_p = ksum(0, 'draws') + ksum(0, 'dispatches')", "    ops_p = ksum(0, 'draws')"),
    ('idle', '        idle=idle_ok(meta))', '        idle=True)'),
    ('idle_le', '    return isinstance(v, (int, float)) and v <= IDLE_GPU_MAX', '    return isinstance(v, (int, float)) and v < IDLE_GPU_MAX'),
    # verdicts
    ('safe_off', "    safe = plans > 0 and 100 * (ksum(0, 'spine_unc') + ksum(0, 'spine_abort')) <= SAFE_MAX_PCT * plans",
     '    safe = plans > 0'),
    ('safe_unc', "    safe = plans > 0 and 100 * (ksum(0, 'spine_unc') + ksum(0, 'spine_abort')) <= SAFE_MAX_PCT * plans",
     "    safe = plans > 0 and 100 * ksum(0, 'spine_abort') <= SAFE_MAX_PCT * plans"),
    ('safe_abort', "    safe = plans > 0 and 100 * (ksum(0, 'spine_unc') + ksum(0, 'spine_abort')) <= SAFE_MAX_PCT * plans",
     "    safe = plans > 0 and 100 * ksum(0, 'spine_unc') <= SAFE_MAX_PCT * plans"),
    ('k5_bad', "    if raw['spine_bad'] > 0 or raw['spine_misal'] > 0 or raw['cram_write'] > 0 or k5_lines > 0:",
     "    if raw['spine_misal'] > 0 or raw['cram_write'] > 0 or k5_lines > 0:"),
    ('k5_misal', "    if raw['spine_bad'] > 0 or raw['spine_misal'] > 0 or raw['cram_write'] > 0 or k5_lines > 0:",
     "    if raw['spine_bad'] > 0 or raw['cram_write'] > 0 or k5_lines > 0:"),
    ('k5_cram', "    if raw['spine_bad'] > 0 or raw['spine_misal'] > 0 or raw['cram_write'] > 0 or k5_lines > 0:",
     "    if raw['spine_bad'] > 0 or raw['spine_misal'] > 0 or k5_lines > 0:"),
    ('k5_lines_off', "    if raw['spine_bad'] > 0 or raw['spine_misal'] > 0 or raw['cram_write'] > 0 or k5_lines > 0:",
     "    if raw['spine_bad'] > 0 or raw['spine_misal'] > 0 or raw['cram_write'] > 0:"),
    ('k5_safe', "    elif safe and el_p > 0 and 100 * ksum(0, 'spine_cmp') >= CMP_MIN_PCT * el_p:",
     "    elif el_p > 0 and 100 * ksum(0, 'spine_cmp') >= CMP_MIN_PCT * el_p:"),
    ('k5_ge', "    elif safe and el_p > 0 and 100 * ksum(0, 'spine_cmp') >= CMP_MIN_PCT * el_p:",
     "    elif safe and el_p > 0 and 100 * ksum(0, 'spine_cmp') > CMP_MIN_PCT * el_p:"),
    ('raw_start', '                if kind == \'x\' and n > START:', '                if kind == \'x\' and n >= START:'),
    ('raw_start_late', '                if kind == \'x\' and n > START:', '                if kind == \'x\' and n > START + 1:'),
    ('raw_dups', "                if kind == 'x' and n > START:", "                if kind == 'x' and n > START and n not in seen['x']:"),
    ('c_bad', "    if raw['carry_bad'] > 0 or c_lines > 0:", '    if c_lines > 0:'),
    ('c_lines_off', "    if raw['carry_bad'] > 0 or c_lines > 0:", "    if raw['carry_bad'] > 0:"),
    ('c_safe', "    elif safe and with_pred > 0 and 100 * ksum(0, 'carry_cmp') >= CMP_MIN_PCT * with_pred:",
     "    elif with_pred > 0 and 100 * ksum(0, 'carry_cmp') >= CMP_MIN_PCT * with_pred:"),
    ('c_ge', "    elif safe and with_pred > 0 and 100 * ksum(0, 'carry_cmp') >= CMP_MIN_PCT * with_pred:",
     "    elif safe and with_pred > 0 and 100 * ksum(0, 'carry_cmp') > CMP_MIN_PCT * with_pred:"),
    ('c_skip', "    with_pred = plans - ksum(0, 'carry_skip')", '    with_pred = plans'),
    ('k3_one', "    one = [v for v in values[0] if v['sc_frames'] == 1 and v['sc_el'] > 0]", "    one = [v for v in values[0] if v['sc_el'] > 0]"),
    ('k3_ge', '    w_max = None if k3_median is None else (4 if 1000 * k3_median >= K3_SHARE_PERMILLE else 8)',
     '    w_max = None if k3_median is None else (4 if 1000 * k3_median > K3_SHARE_PERMILLE else 8)'),
    ('k3_mean', '    k3_median = median(k3_shares)', '    k3_median = mean(k3_shares)'),
    ('k4_n', "        col = [v['k4_w%d_dep' % w] for v in one if v['k4_w%d_n' % w] == 1]", "        col = [v['k4_w%d_dep' % w] for v in one]"),
    ('k4_le', "                     else ('PASS' if med <= K4_DEP_MAX_PERMILLE else 'FAIL'))",
     "                     else ('PASS' if med < K4_DEP_MAX_PERMILLE else 'FAIL'))"),
    ('k4_mean', '        med = median(col)', '        med = mean(col)'),
    ('k4_qual', '        qualified = len(values[0]) > 0 and 100 * len(col) >= K4_MIN_PCT * len(values[0])',
     '        qualified = len(values[0]) > 0'),
    ('k4_qual_ge', '        qualified = len(values[0]) > 0 and 100 * len(col) >= K4_MIN_PCT * len(values[0])',
     '        qualified = len(values[0]) > 0 and 100 * len(col) > K4_MIN_PCT * len(values[0])'),
    ('cons_stop_c', "    if k5 == 'FAIL' or carry == 'FAIL':", "    if k5 == 'FAIL':"),
    ('cons_ne', "    elif 'NOT_EVALUABLE' in (k5, carry, k4[2]['verdict']):", "    elif 'NOT_EVALUABLE' in (k5, carry):"),
    ('cons_close', "        consequence = 'CLOSE_A'", "        consequence = 'W2_CEILING'"),
    ('cons_w2', "    elif k4[4]['verdict'] != 'PASS':", "    elif k4[4]['verdict'] == 'FAIL':"),
    ('cons_stage3', "        consequence = 'STAGE3'", "        consequence = 'W2_CEILING'"),
    ('cons_admitted', "               consequence=consequence if admitted else 'NOT_ADMITTED', raw=raw, k5_lines=k5_lines, c_lines=c_lines,",
     '               consequence=consequence, raw=raw, k5_lines=k5_lines, c_lines=c_lines,'),
    ('verdict', "    res.update(checks=checks, verdict='ADMITTED' if admitted else 'NOT_ADMITTED', k5=k5, carry=carry, safe=safe,",
     "    res.update(checks=checks, verdict='ADMITTED', k5=k5, carry=carry, safe=safe,"),
    # item 4 report lines
    ('above_ge', '        above = sum(1 for d in col if d > K4_DEP_MAX_PERMILLE)',
     '        above = sum(1 for d in col if d >= K4_DEP_MAX_PERMILLE)'),
    ('above_den', '                     above_pct=None if not col else 100.0 * above / len(col),',
     '                     above_pct=None if not col else 100.0 * above / len(values[0]),'),
    ('above_none', '                     above_pct=None if not col else 100.0 * above / len(col),',
     '                     above_pct=0.0 if not col else 100.0 * above / len(col),'),
    ('blk_n', "            if v['k4_w%d_n' % w] == 1:\n                by_block", "            if True:\n                by_block"),
    ('blk_mean', "                     block_medians=[[blk, median(ds)] for blk, ds in sorted(by_block.items())],",
     "                     block_medians=[[blk, mean(ds)] for blk, ds in sorted(by_block.items())],"),
    ('blk_w', "                by_block.setdefault(v['blk'], []).append(v['k4_w%d_dep' % w])",
     "                by_block.setdefault(v['blk'], []).append(v['k4_w4_dep'])"),
    ('skip_pct', "               100.0 * ksum(0, 'carry_skip') / plans, report=report, pins=pins, gate_arms=len(gate_arms),",
     "               100.0 * ksum(0, 'carry_cmp') / plans, report=report, pins=pins, gate_arms=len(gate_arms),"),
    ('skip_line', "    out.append('  carry_skip %s %% of plans (report only)' % fmt(res['carry_skip_pct'], 1))", '    pass'),
    ('above_line', "                   % (w, fmt(e['above_pct'], 1), e['frames'],",
     "                   % (w, fmt(e['p90'], 1), e['frames'],"),
]
STAGE.mkdir(parents=True, exist_ok=True)
killed = 0
for name, old, new in MUTANTS:
    if SRC.count(old) != 1:
        print('%-18s ANCHOR x%d' % (name, SRC.count(old)))
        continue
    path = STAGE / ('mut_spk118_%s.py' % name)
    path.write_bytes(SRC.replace(old, new).encode('utf-8'))
    r = subprocess.run([sys.executable, 'C:/kyty/s118/test_spk118.py', str(path)], capture_output=True, text=True)
    killed += r.returncode != 0
    print('%-18s %s' % (name, 'killed' if r.returncode != 0 else 'SURVIVED'))
    path.unlink()
print('killed %d of %d' % (killed, len(MUTANTS)))
