"""Session 120: mutants of spc120.py - each must be killed by test_spc120.py.  Run through the frozen mutlib v4.1 FULL
(--control --no-memo, work/cache dirs C:/kyty/s120/mutwork_spc120 / mutcache_spc120); the loop below is the old-style
draft check (one fresh `python test_spc120.py <mutant>` per mutant, mutant files in C:/kyty/s120/work_mut_spc120).
Every anchor occurs exactly once in spc120.py (LF)."""
import subprocess
import sys
from pathlib import Path

STAGE = Path('C:/kyty/s120/work_mut_spc120')
SRC = Path('C:/kyty/s120/spc120.py').read_text(encoding='utf-8')
MUTANTS = [
    # ---- constants: run shape, window, thresholds
    ('hold_s', 'HOLD_S = 300', 'HOLD_S = 299'),
    ('period', 'PERIOD = 90', 'PERIOD = 91'),
    ('start', 'START = 1800', 'START = 1710'),
    ('keep_lo9', 'KEEP = (10, 89)', 'KEEP = (9, 89)'),
    ('keep_lo11', 'KEEP = (10, 89)', 'KEEP = (11, 89)'),
    ('keep_hi90', 'KEEP = (10, 89)', 'KEEP = (10, 90)'),
    ('keep_hi88', 'KEEP = (10, 89)', 'KEEP = (10, 88)'),
    ('window_0_99', 'KEEP = (10, 89)', 'KEEP = (0, 100)'),
    ('draws_min_2999', 'DRAWS_MIN = 3000', 'DRAWS_MIN = 2999'),
    ('draws_min_3001', 'DRAWS_MIN = 3000', 'DRAWS_MIN = 3001'),
    ('abba', 'ABBA = (0, 1, 1, 0)', 'ABBA = (0, 1, 0, 1)'),
    ('arm_text_p', "ARM_TEXT = ('r1cen=2 r2cen=2 spcen=1", "ARM_TEXT = ('r1cen=2 r2cen=1 spcen=1"),
    ('arm_text_m', "'r1cen=0 r2cen=1 spcen=0 bindlap=1 pathlap=1 mutsite=1')",
     "'r1cen=0 r2cen=1 spcen=0 bindlap=1 pathlap=1 mutsite=0')"),
    ('min_pairs_29', 'MIN_PAIRS = 30', 'MIN_PAIRS = 29'),
    ('min_pairs_31', 'MIN_PAIRS = 30', 'MIN_PAIRS = 31'),
    ('threshold_499_9', 'THRESHOLD_US = 500.0', 'THRESHOLD_US = 499.9'),
    ('threshold_1000', 'THRESHOLD_US = 500.0', 'THRESHOLD_US = 1000.0'),
    ('race_per_9999', 'RACE_PER = 10000', 'RACE_PER = 9999'),
    ('race_per_10001', 'RACE_PER = 10000', 'RACE_PER = 10001'),
    ('skew_7', 'SKEW_COUNT = 8', 'SKEW_COUNT = 7'),
    ('skew_9', 'SKEW_COUNT = 8', 'SKEW_COUNT = 9'),
    ('draw_id_block_63', 'DRAW_ID_BLOCK_TOL = 64', 'DRAW_ID_BLOCK_TOL = 63'),
    ('draw_id_block_65', 'DRAW_ID_BLOCK_TOL = 64', 'DRAW_ID_BLOCK_TOL = 65'),
    ('draw_id_tol_255', 'DRAW_ID_TOL = 256', 'DRAW_ID_TOL = 255'),
    ('draw_id_tol_320', 'DRAW_ID_TOL = 256', 'DRAW_ID_TOL = 320'),
    ('emit_tol_255', 'EMIT_TOL_US = 256', 'EMIT_TOL_US = 255'),
    ('emit_tol_257', 'EMIT_TOL_US = 256', 'EMIT_TOL_US = 257'),
    ('tr_round_0', 'TR_ROUND_NS = 1000', 'TR_ROUND_NS = 0'),
    ('tr_round_2000', 'TR_ROUND_NS = 1000', 'TR_ROUND_NS = 2000'),
    ('idle_9', 'IDLE_GPU_MAX = 10', 'IDLE_GPU_MAX = 9'),
    ('idle_11', 'IDLE_GPU_MAX = 10', 'IDLE_GPU_MAX = 11'),
    ('bda_new_299', 'BDA_NEW_MAX = 300', 'BDA_NEW_MAX = 299'),
    ('bda_new_301', 'BDA_NEW_MAX = 300', 'BDA_NEW_MAX = 301'),
    ('bda_old_599', 'BDA_OLD_MIN = 600', 'BDA_OLD_MIN = 599'),
    ('bda_old_601', 'BDA_OLD_MIN = 600', 'BDA_OLD_MIN = 601'),
    ('build_sha', "BUILD_SHA = '15cdbfc6", "BUILD_SHA = '25cdbfc6"),
    ('gates_file_sha', "GATES_FILE_SHA = '303a", "GATES_FILE_SHA = '403a"),
    ('gates_text_sha', "GATES_TEXT_SHA = '91da", "GATES_TEXT_SHA = '81da"),
    ('base_pin', "BASE_PINS = {'texmemo2': '0'", "BASE_PINS = {'texmemo2': '1'"),
    ('base_pin_drop', ", 'fslean': '0'}", '}'),
    ('base_absent_spine', "'slicecen', 'spine', 'bindpack')", "'slicecen', 'bindpack')"),
    ('base_absent_bindwit', "BASE_ABSENT = ('bindwit', ", "BASE_ABSENT = ("),
    ('pred_path', "PRED_PATH = 'C:/kyty/s120/pred/01_cen120.md'", "PRED_PATH = 'C:/kyty/s120/pred/02_cen120.md'"),
    ('schedule', "SCHEDULE = '90+1800:'", "SCHEDULE = '90+1890:'"),
    ('env_markers', "    'KYTY_GPU_MARKERS': '0',", "    'KYTY_GPU_MARKERS': '2',"),
    ('env_trace', "    'KYTY_FRAME_TRACE': 'lite',", "    'KYTY_FRAME_TRACE': '1',"),
    ('vk_allowed', "VK_ALLOWED = ('VK_SDK_PATH',)", "VK_ALLOWED = ('VK_SDK_PATH', 'VK_LAYER_PATH')"),
    ('marker_fatal', "b'abort()', b'fatal', ", "b'abort()', "),
    ('marker_hang', "MARKERS = (b'gpuhangabort', ", "MARKERS = ("),
    ('skip_mark', "SKIP_MARK = b'AsyncPipelines: skipped draw'", "SKIP_MARK = b'AsyncPipelines: skipped draws'"),
    ('rt_mismatch_tag', "RT_MISMATCH = b'SpRtMismatch:'", "RT_MISMATCH = b'SpRtMismatchX:'"),
    ('tr_mismatch_tag', "TR_MISMATCH = b'SpTrMismatch:'", "TR_MISMATCH = b'SpTrMismatchX:'"),
    ('census_mode', "SP_CENSUS = b'SpCensus: mode 1'", "SP_CENSUS = b'SpCensus: mode'"),
    ('rt_reason_off_by_one', "RT_REASONS = ('sp_rt_x_memo', 'sp_rt_x_cfg', ", "RT_REASONS = ('sp_rt_x_memo', "),
    ('tr_reason_off_by_one', "'sp_tr_x_ser', 'sp_tr_x_flags')", "'sp_tr_x_ser')"),
    ('emit_new_parts_dropped',
     "EMIT_PARTS = ('pl_em_vtx_ns', 'pl_em_spchk_ns', 'pl_em_rt_ns', 'pl_em_sppost_ns', 'pl_em_pipe_ns', 'pl_em_com_ns',",
     "EMIT_PARTS = ('pl_em_vtx_ns', 'pl_em_rt_ns', 'pl_em_pipe_ns', 'pl_em_com_ns',"),
    ('emit_spchk_dropped', "EMIT_PARTS = ('pl_em_vtx_ns', 'pl_em_spchk_ns', ", "EMIT_PARTS = ('pl_em_vtx_ns', "),
    ('emit_rest_dropped', "              'pl_em_rec_ns', 'pl_em_rest_ns')", "              'pl_em_rec_ns')"),
    ('x_fields_rt_fast_no', "'rt_kpx', 'rt_fast_ok', 'rt_fast_no')", "'rt_kpx', 'rt_fast_ok')"),
    ('m_zero_rst', "M_ZERO = tuple(k for k in SP_FIELDS if k not in ('sp_ser_n', 'sp_ser_val'))",
     "M_ZERO = tuple(k for k in SP_FIELDS if k not in ('sp_ser_n', 'sp_ser_val', 'sp_rt_rst'))"),
    ('m_zero_empty', "M_ZERO = tuple(k for k in SP_FIELDS if k not in ('sp_ser_n', 'sp_ser_val'))", "M_ZERO = ()"),
    # ---- nestings (kinds, entries)
    ('nest_rt_wg_edge', "A_NESTS = (('rt_wg', 'sp_rt_wg', 'sp_rt_would', 'count'),",
     "A_NESTS = (('rt_wg', 'sp_rt_wg', 'sp_rt_would', 'edge'),"),
    ('nest_tr_wg_edge', "B_NESTS = (('tr_wg', 'sp_tr_wg', 'sp_tr_would', 'count'),",
     "B_NESTS = (('tr_wg', 'sp_tr_wg', 'sp_tr_would', 'edge'),"),
    ('nest_rt_hitg_drop', "           ('rt_hitg', 'pl_em_rt_hitg_ns', 'pl_em_rt_hit_ns', 'edge'),\n", ''),
    ('nest_rt_hit_drop', "           ('rt_hit', 'pl_em_rt_hit_ns', 'pl_em_rt_ns', 'edge'),\n", ''),
    ('nest_rt_chkh_drop', "           ('rt_chkh', 'sp_rt_chkh_ns', 'pl_em_spchk_ns', 'edge'),\n", ''),
    ('nest_rt_rep_drop', "           ('rt_rep', 'sp_rt_rep_ns', 'pl_em_sppost_ns', 'edge'),\n", ''),
    ('nest_rt_att_drop', "           ('rt_att', 'sp_rt_rep_att', 'rt_att', 'edge'),\n", ''),
    ('nest_rt_kpx_drop', "           ('rt_kpx', 'sp_rt_rep_kpx', 'rt_kpx', 'edge'),\n", ''),
    ('nest_rt_att_tgt_drop', "           ('rt_att_tgt', 'sp_rt_rep_att', 'sp_rt_tgt', 'edge'),\n", ''),
    ('nest_rt_tgt_one', "('rt_tgt', 'sp_rt_tgt', ('rt_fast_ok', 'rt_fast_no'), 'edge'))",
     "('rt_tgt', 'sp_rt_tgt', ('rt_fast_ok', 'rt_fast_no', 'rt_kpx'), 'edge'))"),
    ('nest_tr_wslots_drop', "           ('tr_wslots', 'sp_tr_wslots', 'sp_tr_slots', 'edge'),\n", ''),
    ('nest_tr_hitg_drop', "           ('tr_hitg', 'bl_tr_hitg_ns', 'bl_tr_hit_ns', 'edge'),\n", ''),
    ('nest_tr_hit_drop', "           ('tr_hit', 'bl_tr_hit_ns', 'sp_tr_loop_ns', 'edge'),\n", ''),
    ('nest_tr_loop_edge_kind', "           ('tr_loop', 'sp_tr_loop_ns', 'bl_tr_us', 'us'),",
     "           ('tr_loop', 'sp_tr_loop_ns', 'bl_tr_us', 'edge'),"),
    ('nest_tr_chkh_drop', "           ('tr_chkh', 'sp_tr_chkh_ns', 'sp_tr_chk_ns', 'edge'),\n", ''),
    ('nest_tr_rep_drop', "           ('tr_rep', 'sp_tr_rep_ns', 'sp_tr_post_ns', 'edge'),\n", ''),
    ('nest_tr_rec_drop', "           ('tr_rec', 'sp_tr_rec_ns', 'sp_tr_post_ns', 'edge'))", "           )"),
    ('field_negative', "FIELD = re.compile(rb' (\\w+)=(-?\\d+)')", "FIELD = re.compile(rb' (\\w+)=(\\d+)')"),
    # ---- helpers
    ('marker_case', '    low = line.lower()', '    low = line'),
    ('idle_lt', '    return isinstance(v, (int, float)) and v <= IDLE_GPU_MAX',
     '    return isinstance(v, (int, float)) and v < IDLE_GPU_MAX'),
    ('arm_assert_pathlap', "        if v.get('pathlap') != '1' or v.get('mutsite') != '1'",
     "        if v.get('pathlap') != '0' or v.get('mutsite') != '1'"),
    ('arm_assert_r2cen', "ARM_VALUES[0].get('r2cen') == '2'", "ARM_VALUES[0].get('r2cen') == '1'"),
    ('in_window_lo', '    return KEEP[0] <= pos < KEEP[1]', '    return KEEP[0] < pos < KEEP[1]'),
    ('in_window_hi', '    return KEEP[0] <= pos < KEEP[1]', '    return KEEP[0] <= pos <= KEEP[1]'),
    ('arms_count', 'if arms != 2 or period != PERIOD', 'if arms != 3 or period != PERIOD'),
    ('arms_abba', 'or abba != 1 or arm not in (0, 1)', 'or arm not in (0, 1)'),
    ('arms_text', ' or text != ARM_TEXT[arm]:', ':'),
    ('arms_frame', 'if frame != START + PERIOD * block or ABBA', 'if ABBA'),
    ('arms_dup', ' != arm or block in blocks:', ' != arm:'),
    ('arms_consecutive', '    ok = bool(blocks) and sorted(blocks) == list(range(len(blocks)))', '    ok = bool(blocks)'),
    ('gate_name', "        if name not in ARM_VALUES[0] or (frame - START) % PERIOD != 0",
     "        if (frame - START) % PERIOD != 0"),
    ('gate_frame', " or (frame - START) % PERIOD != 0 or frame < START:", " or frame < START:"),
    ('gate_value', " or m.group(2).decode() != ARM_VALUES[blocks[block]][name]:", ":"),
    ('last_main_dropped', '                        last_main = n', '                        pass'),
    ('skip_attrib', '                skip_frames.append(None if last_main is None else last_main + 1)',
     '                skip_frames.append(None if last_main is None else last_main)'),
    ('dups_ignored', '                        dups.add(n)', '                        pass'),
    ('rec_incomplete', '                    seen[kind][n] = rec if len(rec) == len(names) else None',
     '                    seen[kind][n] = rec if len(rec) >= 5 else None'),
    ('pin_malformed', '                pins.append(int(mp.group(1)) if mp else -1)',
     '                pins.append(int(mp.group(1)) if mp else 1)'),
    ('stdout_markers', "    so = Path(root) / ('stdout_%s.txt' % tag)", "    so = Path(root) / ('stdout_%s.nope' % tag)"),
    ('se2_pstdev', '    return 2.0 * statistics.stdev(values) / math.sqrt(len(values))',
     '    return 2.0 * statistics.pstdev(values) / math.sqrt(len(values))'),
    ('se2_no_sqrt', '    return 2.0 * statistics.stdev(values) / math.sqrt(len(values))',
     '    return 2.0 * statistics.stdev(values) / len(values)'),
    ('se2_one', '    return 2.0 * statistics.stdev(values) / math.sqrt(len(values))',
     '    return 1.0 * statistics.stdev(values) / math.sqrt(len(values))'),
    ('se2_len1', '    if len(values) < 2 or any(v is None for v in values):',
     '    if len(values) < 1 or any(v is None for v in values):'),
    # ---- formula terms
    ('g_a_hitg', "    t['G_A'] = sp('pl_em_rt_hit_ns') / nfp / 1000", "    t['G_A'] = sp('pl_em_rt_hitg_ns') / nfp / 1000"),
    ('g_a_units', "    t['G_A'] = sp('pl_em_rt_hit_ns') / nfp / 1000", "    t['G_A'] = sp('pl_em_rt_hit_ns') / nfp"),
    ('g_b_loop', "    t['G_B'] = sp('bl_tr_hit_ns') / nfp / 1000", "    t['G_B'] = sp('sp_tr_loop_ns') / nfp / 1000"),
    ('n_a_gross', "    t['N_A'] = (sp('pl_em_rt_hit_ns') - sp('pl_em_spchk_ns') - sp('sp_rt_rep_ns') - sp('sp_rt_rec_ns')) / nfp / 1000",
     "    t['N_A'] = sp('pl_em_rt_hit_ns') / nfp / 1000"),
    ('n_a_chk_hits_only', "sp('pl_em_rt_hit_ns') - sp('pl_em_spchk_ns') - sp('sp_rt_rep_ns')",
     "sp('pl_em_rt_hit_ns') - sp('sp_rt_chkh_ns') - sp('sp_rt_rep_ns')"),
    ('n_a_rec_not_subtracted', "- sp('sp_rt_rep_ns') - sp('sp_rt_rec_ns')) / nfp / 1000",
     "- sp('sp_rt_rep_ns')) / nfp / 1000"),
    ('n_a_rep_not_subtracted', "sp('pl_em_spchk_ns') - sp('sp_rt_rep_ns') - sp('sp_rt_rec_ns')) / nfp",
     "sp('pl_em_spchk_ns') - sp('sp_rt_rec_ns')) / nfp"),
    ('n_a_per_draw', "sp('sp_rt_rep_ns') - sp('sp_rt_rec_ns')) / nfp / 1000",
     "sp('sp_rt_rep_ns') - sp('sp_rt_rec_ns')) / sp('sp_rt_would') / 1000"),
    ('n_a_units', "sp('sp_rt_rep_ns') - sp('sp_rt_rec_ns')) / nfp / 1000", "sp('sp_rt_rep_ns') - sp('sp_rt_rec_ns')) / nfp"),
    ('n_b_gross', "    t['N_B'] = (sp('bl_tr_hit_ns') - sp('sp_tr_chk_ns') - sp('sp_tr_rep_ns') - sp('sp_tr_rec_ns')) / nfp / 1000",
     "    t['N_B'] = sp('bl_tr_hit_ns') / nfp / 1000"),
    ('n_b_chk_hits_only', "sp('bl_tr_hit_ns') - sp('sp_tr_chk_ns') - sp('sp_tr_rep_ns')",
     "sp('bl_tr_hit_ns') - sp('sp_tr_chkh_ns') - sp('sp_tr_rep_ns')"),
    ('n_b_rec_not_subtracted', "- sp('sp_tr_rep_ns') - sp('sp_tr_rec_ns')) / nfp / 1000",
     "- sp('sp_tr_rep_ns')) / nfp / 1000"),
    ('n_b_rep_not_subtracted', "sp('sp_tr_chk_ns') - sp('sp_tr_rep_ns') - sp('sp_tr_rec_ns')) / nfp",
     "sp('sp_tr_chk_ns') - sp('sp_tr_rec_ns')) / nfp"),
    ('n_b_per_draw', "sp('sp_tr_rep_ns') - sp('sp_tr_rec_ns')) / nfp / 1000",
     "sp('sp_tr_rep_ns') - sp('sp_tr_rec_ns')) / sp('sp_tr_n') / 1000"),
    ('n_a_only', "    t['N'] = t['N_A'] + t['N_B']", "    t['N'] = t['N_A']"),
    ('z_a_single_rt', "    t['Z_A'] = zbar * (2 * sp('sp_rt_n') + sp('sp_rt_rec')) / nfp / 1000",
     "    t['Z_A'] = zbar * (sp('sp_rt_n') + sp('sp_rt_rec')) / nfp / 1000"),
    ('z_a_no_rec', "    t['Z_A'] = zbar * (2 * sp('sp_rt_n') + sp('sp_rt_rec')) / nfp / 1000",
     "    t['Z_A'] = zbar * (2 * sp('sp_rt_n')) / nfp / 1000"),
    ('z_a_units', "    t['Z_A'] = zbar * (2 * sp('sp_rt_n') + sp('sp_rt_rec')) / nfp / 1000",
     "    t['Z_A'] = zbar * (2 * sp('sp_rt_n') + sp('sp_rt_rec')) / nfp"),
    ('z_b_single', "    t['Z_B'] = zbar * (2 * sp('sp_tr_n')) / nfp / 1000", "    t['Z_B'] = zbar * (sp('sp_tr_n')) / nfp / 1000"),
    ('d_a_sign', "    t['D_A_ns'] = sm('pl_em_rt_ns') / nfm - sp('pl_em_rt_ns') / nfp",
     "    t['D_A_ns'] = sp('pl_em_rt_ns') / nfp - sm('pl_em_rt_ns') / nfm"),
    ('d_b_us_as_ns', "    t['D_B_ns'] = 1000 * (sm('bl_tr_us') / nfm - sp('bl_tr_us') / nfp)",
     "    t['D_B_ns'] = (sm('bl_tr_us') / nfm - sp('bl_tr_us') / nfp)"),
    ('d_b_sign', "    t['D_B_ns'] = 1000 * (sm('bl_tr_us') / nfm - sp('bl_tr_us') / nfp)",
     "    t['D_B_ns'] = 1000 * (sp('bl_tr_us') / nfp - sm('bl_tr_us') / nfm)"),
    ('d_bp_is_d_b', "    t['D_Bp_ns'] = t['D_B_ns'] + zbar * sp('sp_tr_n') / nfp", "    t['D_Bp_ns'] = t['D_B_ns']"),
    ('d_bp_rt_n', "    t['D_Bp_ns'] = t['D_B_ns'] + zbar * sp('sp_tr_n') / nfp",
     "    t['D_Bp_ns'] = t['D_B_ns'] + zbar * sp('sp_rt_n') / nfp"),
    ('r_a_hitg', "    r_a = div(sp('pl_em_rt_hit_ns'), sp('pl_em_rt_ns'))", "    r_a = div(sp('pl_em_rt_hitg_ns'), sp('pl_em_rt_ns'))"),
    ('r_b_bl_tr', "    r_b = div(sp('bl_tr_hit_ns'), sp('sp_tr_loop_ns'))", "    r_b = div(sp('bl_tr_hit_ns'), 1000 * sp('bl_tr_us'))"),
    ('t_a_no_clamp', "else max(0.0, t['D_A_ns']) * r_a / 1000", "else t['D_A_ns'] * r_a / 1000"),
    ('t_a_no_ratio', "else max(0.0, t['D_A_ns']) * r_a / 1000", "else max(0.0, t['D_A_ns']) / 1000"),
    ('t_b_no_clamp', "else max(0.0, t['D_Bp_ns']) * r_b / 1000", "else t['D_Bp_ns'] * r_b / 1000"),
    ('t_b_uses_d_b', "else max(0.0, t['D_Bp_ns']) * r_b / 1000", "else max(0.0, t['D_B_ns']) * r_b / 1000"),
    ('t_b_no_ratio', "else max(0.0, t['D_Bp_ns']) * r_b / 1000", "else max(0.0, t['D_Bp_ns']) / 1000"),
    ('up_a_z_dropped', "else t['N_A'] + t['Z_A'] + t['T_A']", "else t['N_A'] + t['T_A']"),
    ('up_b_z_dropped', "else t['N_B'] + t['Z_B'] + t['T_B']", "else t['N_B'] + t['T_B']"),
    ('up_a_delta_dropped', "else t['N_A'] + t['Z_A'] + t['T_A']", "else t['N_A'] + t['Z_A']"),
    ('up_b_delta_dropped', "else t['N_B'] + t['Z_B'] + t['T_B']", "else t['N_B'] + t['Z_B']"),
    ('up_a_is_g', "else t['N_A'] + t['Z_A'] + t['T_A']", "else t['G_A']"),
    ('up_b_is_g', "else t['N_B'] + t['Z_B'] + t['T_B']", "else t['G_B']"),
    ('up_sp_a_only', "else t['N_A_up'] + t['N_B_up']", "else t['N_A_up']"),
    ('g_a_up', "    t['G_A_up'] = None if t['T_A'] is None else t['G_A'] + t['T_A']",
     "    t['G_A_up'] = None if t['T_A'] is None else t['G_A']"),
    ('n_a_g_unscaled', "sp('sp_rt_rep_ns') * wa", "sp('sp_rt_rep_ns')"),
    ('n_b_g_unscaled', "sp('sp_tr_rep_ns') * wb", "sp('sp_tr_rep_ns')"),
    ('price_sign', "    t['price_dt_us'] = sp('dt_us') / nfp - sm('dt_us') / nfm",
     "    t['price_dt_us'] = sm('dt_us') / nfm - sp('dt_us') / nfp"),
    # ---- which arm's frame count divides each term (pre-seal check: nfp != nfm)
    ('div_g_a_nfm', "    t['G_A'] = sp('pl_em_rt_hit_ns') / nfp / 1000", "    t['G_A'] = sp('pl_em_rt_hit_ns') / nfm / 1000"),
    ('div_g_b_nfm', "    t['G_B'] = sp('bl_tr_hit_ns') / nfp / 1000", "    t['G_B'] = sp('bl_tr_hit_ns') / nfm / 1000"),
    ('div_n_a_nfm', "sp('sp_rt_rep_ns') - sp('sp_rt_rec_ns')) / nfp / 1000", "sp('sp_rt_rep_ns') - sp('sp_rt_rec_ns')) / nfm / 1000"),
    ('div_n_b_nfm', "sp('sp_tr_rep_ns') - sp('sp_tr_rec_ns')) / nfp / 1000", "sp('sp_tr_rep_ns') - sp('sp_tr_rec_ns')) / nfm / 1000"),
    ('div_z_a_nfm', "    t['Z_A'] = zbar * (2 * sp('sp_rt_n') + sp('sp_rt_rec')) / nfp / 1000",
     "    t['Z_A'] = zbar * (2 * sp('sp_rt_n') + sp('sp_rt_rec')) / nfm / 1000"),
    ('div_z_b_nfm', "    t['Z_B'] = zbar * (2 * sp('sp_tr_n')) / nfp / 1000", "    t['Z_B'] = zbar * (2 * sp('sp_tr_n')) / nfm / 1000"),
    ('div_d_a_m_nfp', "    t['D_A_ns'] = sm('pl_em_rt_ns') / nfm - sp('pl_em_rt_ns') / nfp",
     "    t['D_A_ns'] = sm('pl_em_rt_ns') / nfp - sp('pl_em_rt_ns') / nfp"),
    ('div_d_a_p_nfm', "    t['D_A_ns'] = sm('pl_em_rt_ns') / nfm - sp('pl_em_rt_ns') / nfp",
     "    t['D_A_ns'] = sm('pl_em_rt_ns') / nfm - sp('pl_em_rt_ns') / nfm"),
    ('div_d_b_m_nfp', "    t['D_B_ns'] = 1000 * (sm('bl_tr_us') / nfm - sp('bl_tr_us') / nfp)",
     "    t['D_B_ns'] = 1000 * (sm('bl_tr_us') / nfp - sp('bl_tr_us') / nfp)"),
    ('div_d_b_p_nfm', "    t['D_B_ns'] = 1000 * (sm('bl_tr_us') / nfm - sp('bl_tr_us') / nfp)",
     "    t['D_B_ns'] = 1000 * (sm('bl_tr_us') / nfm - sp('bl_tr_us') / nfm)"),
    ('div_d_bp_nfm', "    t['D_Bp_ns'] = t['D_B_ns'] + zbar * sp('sp_tr_n') / nfp",
     "    t['D_Bp_ns'] = t['D_B_ns'] + zbar * sp('sp_tr_n') / nfm"),
    ('div_g_a_g_nfm', "    t['G_A_g'] = sp('pl_em_rt_hitg_ns') / nfp / 1000", "    t['G_A_g'] = sp('pl_em_rt_hitg_ns') / nfm / 1000"),
    ('div_g_b_g_nfm', "    t['G_B_g'] = sp('bl_tr_hitg_ns') / nfp / 1000", "    t['G_B_g'] = sp('bl_tr_hitg_ns') / nfm / 1000"),
    ('div_n_a_g_nfm', "                                          - sp('sp_rt_rec_ns')) / nfp / 1000",
     "                                          - sp('sp_rt_rec_ns')) / nfm / 1000"),
    ('div_n_b_g_nfm', "                                          - sp('sp_tr_rec_ns')) / nfp / 1000",
     "                                          - sp('sp_tr_rec_ns')) / nfm / 1000"),
    ('div_price_m_nfp', "    t['price_dt_us'] = sp('dt_us') / nfp - sm('dt_us') / nfm",
     "    t['price_dt_us'] = sp('dt_us') / nfp - sm('dt_us') / nfp"),
    ('div_price_p_nfm', "    t['price_dt_us'] = sp('dt_us') / nfp - sm('dt_us') / nfm",
     "    t['price_dt_us'] = sp('dt_us') / nfm - sm('dt_us') / nfm"),
    ('div_price_cpu_m_nfp', "    t['price_cpu_gpu_us'] = sp('cpu_gpu_us') / nfp - sm('cpu_gpu_us') / nfm",
     "    t['price_cpu_gpu_us'] = sp('cpu_gpu_us') / nfp - sm('cpu_gpu_us') / nfp"),
    ('div_price_cpu_p_nfm', "    t['price_cpu_gpu_us'] = sp('cpu_gpu_us') / nfp - sm('cpu_gpu_us') / nfm",
     "    t['price_cpu_gpu_us'] = sp('cpu_gpu_us') / nfm - sm('cpu_gpu_us') / nfm"),
    # ---- nest_ok / part_ok / verdict
    ('nest_us_as_ns', '            big = 1000 * ssum(rows, sup) + TR_ROUND_NS * len(rows)',
     '            big = ssum(rows, sup) + TR_ROUND_NS * len(rows)'),
    ('nest_count_tol0', '            tol = SKEW_COUNT', '            tol = 0'),
    ('nest_edge_tol0', '            tol = rows[0][sub] + rows[-1][sub]', '            tol = 0'),
    ('nest_edge_first_only', '            tol = rows[0][sub] + rows[-1][sub]', '            tol = 2 * rows[0][sub]'),
    ('nest_edge_last_only', '            tol = rows[0][sub] + rows[-1][sub]', '            tol = 2 * rows[-1][sub]'),
    ('nest_ge', '        if s > big + tol:', '        if s >= big + tol:'),
    ('nest_plus_one', '        if s > big + tol:', '        if s > big + tol + 1:'),
    ('nest_exact_per_frame', '        if s > big + tol:',
     "        if s > big + tol or (kind == 'count' and any(r[sub] > r[sup] for r in rows)):"),
    ('part_signed', '        if abs(res) > SKEW_COUNT:', '        if res > SKEW_COUNT:'),
    ('part_exact_per_frame', '        if abs(res) > SKEW_COUNT:',
     '        if abs(res) > SKEW_COUNT or any(r[total] != r[would] + sum(r[k] for k in reasons) for r in rows):'),
    ('part_reason_skipped', '        res = ssum(rows, total) - ssum(rows, would) - sum(ssum(rows, k) for k in reasons)',
     '        res = ssum(rows, total) - ssum(rows, would) - sum(ssum(rows, k) for k in reasons[:-1])'),
    ('bad_ignored', "    if fail:\n        return 'FAIL'", "    if False:\n        return 'FAIL'"),
    ('notev_ignored', '    if notev or point is None or upper is None or two_se is None:',
     '    if point is None or upper is None or two_se is None:'),
    ('open_gt', '    if point >= THRESHOLD_US:', '    if point > THRESHOLD_US:'),
    ('closed_le', '    if upper + two_se < THRESHOLD_US:', '    if upper + two_se <= THRESHOLD_US:'),
    ('closed_no_2se', '    if upper + two_se < THRESHOLD_US:', '    if upper < THRESHOLD_US:'),
    ('closed_on_point', '    if upper + two_se < THRESHOLD_US:', '    if point + two_se < THRESHOLD_US:'),
    ('closed_minus_2se', '    if upper + two_se < THRESHOLD_US:', '    if upper - two_se < THRESHOLD_US:'),
    # ---- evaluate: frames, pairs, admission
    ('stream_end_break', '            if n > last_main:\n                break', '            if False:\n                break'),
    ('stream_last_not_exempt', '            if n == last_main and (draw is None or x is None):\n                break\n', ''),
    ('stream_last_always_dropped', '            if n == last_main and (draw is None or x is None):',
     '            if n == last_main:'),
    ('stream_last_x_only', '            if n == last_main and (draw is None or x is None):',
     '            if n == last_main and x is None:'),
    ('stream_penultimate_exempt', '            if n == last_main and (draw is None or x is None):',
     '            if n >= last_main - 1 and (draw is None or x is None):'),
    ('pair_complete_dropped', '                and START + PERIOD * (b + 1) + KEEP[1] <= last_main):',
     '                and True):'),
    ('pair_complete_lt', '                and START + PERIOD * (b + 1) + KEEP[1] <= last_main):',
     '                and START + PERIOD * (b + 1) + KEEP[1] < last_main):'),
    ('pair_complete_pos87', '                and START + PERIOD * (b + 1) + KEEP[1] <= last_main):',
     '                and START + PERIOD * (b + 1) + KEEP[1] - 1 <= last_main):'),
    ('stream_blk_label', " or main['arm'] != arm or main['blk'] != b:", " or main['arm'] != arm:"),
    ('arm_by_counter_frame', " or main['arm'] != arm or main['blk'] != b:",
     " or (0 if x['sp_rt_n'] > 0 else 1) != arm or main['blk'] != b:"),
    ('draws_ge', "        est[b] = [r for r in rows if r['draws'] > DRAWS_MIN]",
     "        est[b] = [r for r in rows if r['draws'] >= DRAWS_MIN]"),
    ('controls_on_estimator_p', '    p_blocks = [win[b] for b in sorted(win) if arm_of[b] == 0 and win[b]]',
     '    p_blocks = [est[b] for b in sorted(est) if arm_of[b] == 0 and est[b]]'),
    ('controls_on_estimator_m', '    m_blocks = [win[b] for b in sorted(win) if arm_of[b] == 1 and win[b]]',
     '    m_blocks = [est[b] for b in sorted(est) if arm_of[b] == 1 and est[b]]'),
    ('estimator_is_window', "        est[b] = [r for r in rows if r['draws'] > DRAWS_MIN]", '        est[b] = rows'),
    ('arm_by_counter_pair', '            p, m = (b, b + 1) if arm_of[b] == 0 else (b + 1, b)',
     "            p, m = (b, b + 1) if ssum(est[b], 'sp_rt_n') > 0 else (b + 1, b)"),
    ('pair_order_fixed', '            p, m = (b, b + 1) if arm_of[b] == 0 else (b + 1, b)', '            p, m = (b, b + 1)'),
    ('pair_empty_blocks', "        if (b % 2 == 0 and b + 1 in est and est[b] and est[b + 1]",
     "        if (b % 2 == 0 and b + 1 in est"),
    ('pool_unpaired', '    prow = [r for p, m in pairs for r in est[p]]', '    prow = prow_all'),
    ('skip_any_frame', "                   and in_window(window_pos(f)[1])]", "                   ]"),
    ('prereg_unsealed_passes', '    prereg_ok = (want_sha is not None and want_bytes is not None',
     '    prereg_ok = (True'),
    ('prereg_path_slashes', "str(prereg.get('path') or '').replace('\\\\', '/') == PRED_PATH",
     "str(prereg.get('path') or '') == PRED_PATH"),
    ('prereg_bytes', " and prereg.get('bytes') == want_bytes", ''),
    ('prereg_now_sha', '                 and pred_now[0] == want_sha and pred_now[1] == want_bytes)',
     '                 and pred_now[1] == want_bytes)'),
    ('prereg_now_bytes', '                 and pred_now[0] == want_sha and pred_now[1] == want_bytes)',
     '                 and pred_now[0] == want_sha)'),
    ('gates_file_bytes', '    gates_base = (gf.is_file() and sha_file(gf) == GATES_FILE_SHA and hashlib.sha256(',
     '    gates_base = (gf.is_file() and hashlib.sha256('),
    ('base_names_arm_only', 'and not any(k in gate_names or k in arm_names for k in BASE_ABSENT)',
     'and not any(k in arm_names for k in BASE_ABSENT)'),
    ('base_pins_ignored', '        base_names=(all(gate_names.get(k) == v for k, v in BASE_PINS.items())',
     '        base_names=(True'),
    ('pins_any', "pinned=env.get('KYTY_GPU_CLOCK_PIN') == '1' and run['pins'] == [1],",
     "pinned=env.get('KYTY_GPU_CLOCK_PIN') == '1' and 1 in run['pins'],"),
    ('env_vk_ignored', '        env_vk=all(k in VK_ALLOWED for k in vk_env),', '        env_vk=True,'),
    ('hold_not_skipped', "        hold=None if draft else meta.get('hold_s') == HOLD_S,",
     "        hold=meta.get('hold_s') == HOLD_S,"),
    ('prereg_not_skipped', '        prereg=None if draft else prereg_ok,', '        prereg=prereg_ok,'),
    ('pairs_not_skipped', '        pairs=None if draft else len(pairs) >= min_pairs,', '        pairs=len(pairs) >= min_pairs,'),
    ('pairs_gt', '        pairs=None if draft else len(pairs) >= min_pairs,',
     '        pairs=None if draft else len(pairs) > min_pairs,'),
    ('attempts_any', '        one_ok_attempt=len(atts) == 1 and len(ok_att) == 1,', '        one_ok_attempt=len(ok_att) == 1,'),
    ('census_count', "        sp_logged=len(run['census']) == 1 and run['census'][0].startswith(SP_CENSUS),",
     "        sp_logged=len(run['census']) >= 1 and run['census'][0].startswith(SP_CENSUS),"),
    ('admitted_none_fails', '    admitted = all(v is not False for v in checks.values())',
     '    admitted = all(v for v in checks.values())'),
    ('zbar_from_m', "    zbar = div(sp('r2_nul_ns'), sp('r2_nul_n'))", "    zbar = div(sm('r2_nul_ns'), sm('r2_nul_n'))"),
    ('zbar_all_frames', "    zbar = div(sp('r2_nul_ns'), sp('r2_nul_n'))", "    zbar = div(cp('r2_nul_ns'), cp('r2_nul_n'))"),
    ('nt_m_rows', "if window_pos(n) is not None and blocks.get(window_pos(n)[0]) == 0)",
     "if window_pos(n) is not None and blocks.get(window_pos(n)[0]) in (0, 1))"),
    ('nt_prestart', "if window_pos(n) is not None and blocks.get(window_pos(n)[0]) == 0)",
     "if blocks.get((window_pos(n) or (0, 0))[0]) == 0)"),
    ('nt_by_label', "if window_pos(n) is not None and blocks.get(window_pos(n)[0]) == 0)",
     "if window_pos(n) is not None and (seen['main'].get(n) or {}).get('arm') == 0)"),
    ('nt_window_only', "if window_pos(n) is not None and blocks.get(window_pos(n)[0]) == 0)",
     "if window_pos(n) is not None and blocks.get(window_pos(n)[0]) == 0 and in_window(window_pos(n)[1]))"),
    ('emit_no_abs', "    em_p = None if not prow_all else abs(sum(cp(k) for k in EMIT_PARTS) / len(prow_all) / 1000",
     "    em_p = None if not prow_all else (sum(cp(k) for k in EMIT_PARTS) / len(prow_all) / 1000"),
    ('common_admitted', '        admitted=admitted,', '        admitted=True,'),
    ('common_pairs2', '        pairs2=len(pairs) >= 2,', '        pairs2=True,'),
    ('common_zbar_pos', "        zbar=sp('r2_nul_n') > 0 and zbar is not None and zbar > 0,",
     "        zbar=sp('r2_nul_n') > 0 and zbar is not None,"),
    ('common_m_zeros', '        m_zeros=all(cm(k) == 0 for k in M_ZERO),', '        m_zeros=True,'),
    ('common_ser_m', "        ser_alive=cp('sp_ser_n') > 0 and cm('sp_ser_n') > 0,", "        ser_alive=cp('sp_ser_n') > 0,"),
    ('common_ser_nest_p_only', "        ser_nest=nest_ok(p_blocks + m_blocks, 'sp_ser_val', 'sp_ser_n', 'count'),",
     "        ser_nest=nest_ok(p_blocks, 'sp_ser_val', 'sp_ser_n', 'count'),"),
    ('common_alive_m', " and cp('pl_em_n') > 0 and cm('pl_em_n') > 0,", " and cp('pl_em_n') > 0,"),
    ('race_ignored', "        race=RACE_PER * all_rows['sp_rt_race'] <= all_rows['sp_rt_would'],", '        race=True,'),
    ('race_lt', "        race=RACE_PER * all_rows['sp_rt_race'] <= all_rows['sp_rt_would'],",
     "        race=RACE_PER * all_rows['sp_rt_race'] < all_rows['sp_rt_would'],"),
    ('race_window_would', "        race=RACE_PER * all_rows['sp_rt_race'] <= all_rows['sp_rt_would'],",
     "        race=RACE_PER * all_rows['sp_rt_race'] <= cp('sp_rt_would'),"),
    ('nt_ignored', '        nt=nt_p == 0,', '        nt=True,'),
    ('draw_id_block_ignored',
     "        draw_id=(all(abs(ssum(rows, 'sp_rt_n') - ssum(rows, 'pl_em_n')) <= DRAW_ID_BLOCK_TOL for rows in p_blocks)",
     '        draw_id=(True'),
    ('draw_id_total_ignored', "                 and abs(cp('sp_rt_n') - cp('pl_em_n')) <= DRAW_ID_TOL),", '                 ),'),
    ('rt_part_per_frame', "        rt_part=part_ok(p_blocks, 'sp_rt_n', 'sp_rt_would', RT_REASONS),",
     "        rt_part=part_ok([[r] for r in prow_all], 'sp_rt_n', 'sp_rt_would', RT_REASONS),"),
    ('emit_m_ignored', ' and em_p <= EMIT_TOL_US and em_m <= EMIT_TOL_US,', ' and em_p <= EMIT_TOL_US,'),
    ('a_den_ignored', "        a_den=sp('pl_em_rt_ns') > 0)", '        a_den=True)'),
    ('a_den_window', "        a_den=sp('pl_em_rt_ns') > 0)", "        a_den=cp('pl_em_rt_ns') > 0)"),
    ('bl_tr_alive_window_m', " and sm('bl_tr_us') > 0,", " and cm('bl_tr_us') > 0,"),
    ('bl_tr_alive_window_p', "        bl_tr_alive=sp('bl_tr_us') > 0", "        bl_tr_alive=cp('bl_tr_us') > 0"),
    ('draw_id_total_estimator', "                 and abs(cp('sp_rt_n') - cp('pl_em_n')) <= DRAW_ID_TOL),",
     "                 and abs(sp('sp_rt_n') - sp('pl_em_n')) <= DRAW_ID_TOL),"),
    ('hold_exit_ignored', "    ok_att = [a for a in atts if a.get('outcome') == 'ok' and a.get('hold_exit') is None]",
     "    ok_att = [a for a in atts if a.get('outcome') == 'ok']"),
    ('tr_part_ignored', "        tr_part=part_ok(p_blocks, 'sp_tr_n', 'sp_tr_would', TR_REASONS),", '        tr_part=True,'),
    ('bl_tr_m_ignored', "        bl_tr_alive=sp('bl_tr_us') > 0 and sm('bl_tr_us') > 0,", "        bl_tr_alive=sp('bl_tr_us') > 0,"),
    ('b_den_ignored', "        b_den=sp('sp_tr_loop_ns') > 0)", '        b_den=True)'),
    ('b_nest_ignored', "        b_ctl['nest_' + name] = nest_ok(p_blocks, sub, sup, kind)", "        b_ctl['nest_' + name] = True"),
    ('a_nest_m_blocks', "        a_ctl['nest_' + name] = nest_ok(p_blocks, sub, sup, kind)",
     "        a_ctl['nest_' + name] = nest_ok(m_blocks, sub, sup, kind)"),
    ('terms_zbar_ungated', "    t = terms(prow, mrow, zbar if common['zbar'] else None)", '    t = terms(prow, mrow, zbar)'),
    ('pair_terms_swapped', "    per_pair = [terms(est[p], est[m], zbar if common['zbar'] else None) for p, m in pairs]",
     "    per_pair = [terms(est[m], est[p], zbar if common['zbar'] else None) for p, m in pairs]"),
    ('fail_a_no_lines', "    fail_a = all_rows['sp_rt_bad'] > 0 or run['rt_lines'] > 0", "    fail_a = all_rows['sp_rt_bad'] > 0"),
    ('fail_b_no_lines', "    fail_b = all_rows['sp_tr_bad'] > 0 or run['tr_lines'] > 0", "    fail_b = all_rows['sp_tr_bad'] > 0"),
    ('fail_a_window_only', "    fail_a = all_rows['sp_rt_bad'] > 0 or run['rt_lines'] > 0",
     "    fail_a = cp('sp_rt_bad') > 0 or run['rt_lines'] > 0"),
    ('fail_b_window_only', "    fail_b = all_rows['sp_tr_bad'] > 0 or run['tr_lines'] > 0",
     "    fail_b = cp('sp_tr_bad') > 0 or run['tr_lines'] > 0"),
    ('race_as_bad', "    fail_a = all_rows['sp_rt_bad'] > 0 or run['rt_lines'] > 0",
     "    fail_a = all_rows['sp_rt_bad'] + all_rows['sp_rt_race'] > 0 or run['rt_lines'] > 0"),
    ('ne_a_common_only', '    ne_a = ne_common or not all(a_ctl.values())', '    ne_a = ne_common'),
    ('ne_b_common_only', '    ne_b = ne_common or not all(b_ctl.values())', '    ne_b = ne_common'),
    ('ne_common_ignored', '    ne_common = not all(common.values())', '    ne_common = False'),
    ('member_a_global', "('A', fail_a, ne_a, 'N_A', 'N_A_up')", "('A', fail_a, ne_a, 'N_A_g', 'N_A_up')"),
    ('member_a_g_upper', "('A', fail_a, ne_a, 'N_A', 'N_A_up')", "('A', fail_a, ne_a, 'N_A', 'G_A_up')"),
    ('member_b_swap', "('B', fail_b, ne_b, 'N_B', 'N_B_up')", "('B', fail_b, ne_b, 'N_B', 'N_B')"),
    ('package_fail_a_only', "('SP', fail_a or fail_b, ne_a or ne_b, 'N', 'N_up')", "('SP', fail_a, ne_a or ne_b, 'N', 'N_up')"),
    ('package_ne_a_only', "('SP', fail_a or fail_b, ne_a or ne_b, 'N', 'N_up')", "('SP', fail_a or fail_b, ne_a, 'N', 'N_up')"),
    ('se2_of_point', '        two_se = se2(pair_col(uk))', '        two_se = se2(pair_col(pk))'),
    ('carrying_by_point', "    carrying = [n for n in ('A', 'B') if members[n]['verdict'] == 'OPEN']",
     "    carrying = [n for n in ('A', 'B') if members[n]['point'] is not None and members[n]['point'] >= THRESHOLD_US]"),
    ('consequence_package_only', "    elif sp_v == 'OPEN' or carrying:", "    elif sp_v == 'OPEN':"),
    ('member_consequence_pkg', "        v = members[n]['verdict']", '        v = sp_v'),
    ('member_consequence_order', "        if v == 'FAIL':\n            member_consequence[n] = CONSEQUENCES['FAIL']\n"
                                 "        elif not admitted:",
     "        if not admitted:\n            member_consequence[n] = CONSEQUENCES['NOT_ADMITTED']\n        elif v == 'FAIL':"),
    ('member_consequence_admit_ignored', "        elif not admitted:\n            member_consequence[n]",
     "        elif False:\n            member_consequence[n]"),
    ('member_consequence_open_name', "            member_consequence[n] = CONSEQUENCES['OPEN'] % n",
     "            member_consequence[n] = CONSEQUENCES['OPEN'] % 'A+B'"),
    ('report_member_lines', "        out.append('CONSEQUENCE %s: %s' % (name, res['member_consequence'][name]))",
     '        pass'),
    ('consequence_order', "    if sp_v == 'FAIL':\n        consequence = CONSEQUENCES['FAIL']\n    elif not admitted:",
     "    if not admitted:\n        consequence = CONSEQUENCES['NOT_ADMITTED']\n    elif sp_v == 'FAIL':"),
    ('regime_new_lt', "'NEW' if bda <= BDA_NEW_MAX", "'NEW' if bda < BDA_NEW_MAX"),
    ('regime_old_gt', "'OLD' if bda >= BDA_OLD_MIN", "'OLD' if bda > BDA_OLD_MIN"),
    ('report_pkg_label', "('PACKAGE' if name == 'SP' else 'MEMBER', name,", "('MEMBER', name,"),
    ('report_2se_point', "                                                        fmt(m['se2_upper'])))",
     "                                                        fmt(m['se2_point'])))"),
    ('report_draft_line', "    if res['draft']:\n        out.append('DRAFT", "    if False:\n        out.append('DRAFT"),
]
if __name__ == '__main__':
    STAGE.mkdir(parents=True, exist_ok=True)
    killed = 0
    for name, old, new in MUTANTS:
        if SRC.count(old) != 1:
            print('%-26s ANCHOR x%d' % (name, SRC.count(old)))
            continue
        path = STAGE / ('mut_spc120_%s.py' % name)
        path.write_bytes(SRC.replace(old, new).encode('utf-8'))
        r = subprocess.run([sys.executable, 'C:/kyty/s120/test_spc120.py', str(path)], capture_output=True, text=True)
        killed += r.returncode != 0
        print('%-26s %s' % (name, 'killed' if r.returncode != 0 else 'SURVIVED'))
        path.unlink()
    print('killed %d of %d' % (killed, len(MUTANTS)))
