"""Session 120: mutants of rpk120.py - each must be killed by test_rpk120.py.  Run through the frozen mutlib v4.1 FULL:
    python C:/kyty/KytyPS5/docs/session-116/mutlib_v41/mutlib.py --scorer C:/kyty/s120/rpk120.py
        --test C:/kyty/s120/test_rpk120.py --mutants C:/kyty/s120/mut_rpk120.py --control --no-memo
        --work-dir C:/kyty/s120/mutwork_rpk120 --cache-dir C:/kyty/s120/mutcache_rpk120 --out C:/kyty/s120/mut_rpk120.draft.txt
Every anchor occurs exactly once in rpk120.py (LF).  Must-haves of the designs / reviews / ROADMAP s120 items 4-5 are
marked [MH]; the rest is one mutant per formula term, threshold comparison, window edge, unit conversion, correctness
rule, identity, bound, sampler and admission check.  The loop below is the old-style draft check only."""
import subprocess
import sys
from pathlib import Path

STAGE = Path('C:/kyty/s120/work_mut_rpk120')
SRC = Path('C:/kyty/s120/rpk120.py').read_text(encoding='utf-8')
# Removed as exact equivalents (round 1, mutlib v4.1): gate_before (dropping `frame < START` in gate_lines_ok: a
# frame below START gives a negative block, never in `blocks`, so `block not in blocks` rejects the line anyway) and
# skip_start_lt (`frame < START` for `frame <= START` in skip_in_window: frame == START gives block -1, never in
# `blocks`).  Both conditions are defence in depth with no observable effect.
# Removed as an exact equivalent (s120 item 6 run, mutlib v4.1): sum_open_pkg_ignored (`elif open_m:` for
# `elif open_m or pk_v == 'OPEN':` in summary_of): with no OPEN member and the package OPEN the fall-through
# `summary = pk_v` gives 'OPEN' as well, and `carrying` is computed outside the branch - same result for every input.
MUTANTS = [
    # ---- constants: run shape, window, thresholds, units
    ('hold_s', 'HOLD_S = 300', 'HOLD_S = 299'),
    ('period', 'PERIOD = 90\n', 'PERIOD = 91\n'),
    ('start', 'START = 1800', 'START = 1710'),
    ('keep_lo9', 'KEEP = (10, 89)', 'KEEP = (9, 89)'),
    ('keep_lo11', 'KEEP = (10, 89)', 'KEEP = (11, 89)'),
    ('keep_hi90', 'KEEP = (10, 89)', 'KEEP = (10, 90)'),
    ('keep_hi88', 'KEEP = (10, 89)', 'KEEP = (10, 88)'),
    ('window_0_88', 'KEEP = (10, 89)', 'KEEP = (0, 89)'),                                          # [MH r1.md]
    ('draws_min_2999', 'DRAWS_MIN = 3000', 'DRAWS_MIN = 2999'),
    ('draws_min_3001', 'DRAWS_MIN = 3000', 'DRAWS_MIN = 3001'),
    ('abba', 'ABBA = (0, 1, 1, 0)', 'ABBA = (0, 1, 0, 1)'),
    ('arm_text_p', "ARM_TEXT = ('r1cen=2 r2cen=2 spcen=1", "ARM_TEXT = ('r1cen=2 r2cen=1 spcen=1"),
    ('arm_text_m', "            'r1cen=0 r2cen=1 spcen=0 bindlap=1 pathlap=1 mutsite=1')",
     "            'r1cen=0 r2cen=0 spcen=0 bindlap=1 pathlap=1 mutsite=1')"),
    ('min_pairs_29', 'MIN_PAIRS = 30', 'MIN_PAIRS = 29'),
    ('min_pairs_31', 'MIN_PAIRS = 30', 'MIN_PAIRS = 31'),
    ('idle_9', 'IDLE_GPU_MAX = 10', 'IDLE_GPU_MAX = 9'),
    ('idle_11', 'IDLE_GPU_MAX = 10', 'IDLE_GPU_MAX = 11'),
    ('threshold_1000', 'BAR_US = 500.0', 'BAR_US = 1000.0'),                                      # [MH r1 review]
    ('threshold_4999', 'BAR_US = 500.0', 'BAR_US = 499.9'),
    ('ns_per_us_1', 'NS_PER_US = 1000.0', 'NS_PER_US = 1.0'),
    ('ns_per_us_1e6', 'NS_PER_US = 1000.0', 'NS_PER_US = 1000000.0'),
    ('const_b', 'B_NS = 8.49', 'B_NS = 9.49'),
    ('const_b_lo', 'B_LO_NS = 5.0', 'B_LO_NS = 6.0'),
    ('const_t_prime', 'T_PRIME_NS = 15.00 - 3.0', 'T_PRIME_NS = 15.00 - 0.0'),
    ('const_p', 'P_NS = 15.08', 'P_NS = 16.08'),
    ('const_n0', 'N0_NS = 2.0', 'N0_NS = 3.0'),
    ('const_ls', 'LS_NS = 5.0', 'LS_NS = 3.0'),
    ('const_reset', 'R_RESET_NS = 2.0', 'R_RESET_NS = 0.0'),
    ('const_a_tr', 'A_TR_NS = 1.2', 'A_TR_NS = 0.0'),
    ('pc_lo', 'PC_LO_NS = 25.0', 'PC_LO_NS = 25.1'),
    ('pc_hi', 'PC_HI_NS = 90.0', 'PC_HI_NS = 89.9'),
    ('band_hit_lo', 'HIT_BAND = (0.10, 0.15)', 'HIT_BAND = (0.101, 0.15)'),
    ('band_hit_hi', 'HIT_BAND = (0.10, 0.15)', 'HIT_BAND = (0.10, 0.149)'),
    ('band_post_lo', 'POST_BAND = (0.45, 0.55)', 'POST_BAND = (0.451, 0.55)'),
    ('band_post_hi', 'POST_BAND = (0.45, 0.55)', 'POST_BAND = (0.45, 0.549)'),
    ('band_fast_lo', 'FAST_BAND = (0.05, 0.075)', 'FAST_BAND = (0.051, 0.075)'),
    ('band_fast_hi', 'FAST_BAND = (0.05, 0.075)', 'FAST_BAND = (0.05, 0.074)'),
    ('band_self_lo', 'SELF_BAND = (0.012, 0.019)', 'SELF_BAND = (0.0121, 0.019)'),
    ('band_self_hi', 'SELF_BAND = (0.012, 0.019)', 'SELF_BAND = (0.012, 0.0189)'),
    ('band_r2_lo', 'R2_SMP_BAND = (0.10, 0.15)', 'R2_SMP_BAND = (0.101, 0.15)'),
    ('band_r2_hi', 'R2_SMP_BAND = (0.10, 0.15)', 'R2_SMP_BAND = (0.10, 0.149)'),
    ('prepost_019', 'PREPOST_MAX = 0.02', 'PREPOST_MAX = 0.018'),
    ('prepost_021', 'PREPOST_MAX = 0.02', 'PREPOST_MAX = 0.022'),
    ('reset_pct_24', 'RESET_MAX_PCT = 25', 'RESET_MAX_PCT = 24'),
    ('skew_near_7', 'SKEW_NEAR = 8', 'SKEW_NEAR = 7'),
    ('skew_near_9', 'SKEW_NEAR = 8', 'SKEW_NEAR = 9'),
    ('skew_near_old_2', 'SKEW_NEAR = 8', 'SKEW_NEAR = 2'),                                    # [MH ROADMAP s120 6]
    ('skew_far_255', 'SKEW_FAR_ABS = 256', 'SKEW_FAR_ABS = 255'),
    ('skew_far_257', 'SKEW_FAR_ABS = 256', 'SKEW_FAR_ABS = 257'),
    ('skew_far_permille_0', 'SKEW_FAR_PERMILLE = 1', 'SKEW_FAR_PERMILLE = 0'),
    ('skew_far_permille_2', 'SKEW_FAR_PERMILLE = 1', 'SKEW_FAR_PERMILLE = 2'),
    ('bda_new_299', 'BDA_NEW_MAX = 300', 'BDA_NEW_MAX = 299'),
    ('bda_new_301', 'BDA_NEW_MAX = 300', 'BDA_NEW_MAX = 301'),
    ('bda_old_599', 'BDA_OLD_MIN = 600', 'BDA_OLD_MIN = 599'),
    ('bda_old_601', 'BDA_OLD_MIN = 600', 'BDA_OLD_MIN = 601'),
    ('build_sha', "BUILD_SHA = '15cdbfc6", "BUILD_SHA = '25cdbfc6"),
    ('gates_sha', "GATES_SHA = '303a7849", "GATES_SHA = '403a7849"),
    ('gates_file', "GATES_FILE = 'C:/kyty/s120/gates_base.txt'", "GATES_FILE = 'C:/kyty/s119/gates_base.txt'"),
    ('pred_path', "PRED_PATH = 'C:/kyty/s120/pred/01_cen120.md'", "PRED_PATH = 'C:/kyty/s120/pred/02_cen120.md'"),
    ('schedule', "SCHEDULE = '90+1800:' + ARM_TEXT[0] + '|' + ARM_TEXT[1]",
     "SCHEDULE = '90+1800:' + ARM_TEXT[1] + '|' + ARM_TEXT[0]"),
    ('env_markers', "    'KYTY_GPU_MARKERS': '0',\n", "    'KYTY_GPU_MARKERS': '2',\n"),
    ('env_pin_dropped', "    'KYTY_GPU_CLOCK_PIN': '1',\n", ''),
    ('env_abba', "    'KYTY_GATE_SCHEDULE_ABBA': '1',\n", "    'KYTY_GATE_SCHEDULE_ABBA': '0',\n"),
    ('vk_allowed', "VK_ALLOWED = ('VK_SDK_PATH',)", "VK_ALLOWED = ('VK_SDK_PATH', 'VK_LAYER_PATH')"),
    ('marker_hang', "MARKERS = (b'gpuhangabort', ", 'MARKERS = ('),
    ('marker_slow', "b'gpuwaitslow', ", ''),
    ('marker_mhung', "b'gpumarkerhung', ", ''),
    ('marker_ckpt', "b'gpucheckpointhang', ", ''),
    ('marker_lost', "b'errordevicelost',\n", '\n'),
    ('marker_term', "           b'std::terminate', ", '           '),
    ('marker_abort', "b'abort()', ", ''),
    ('marker_fatal', "b'fatal', ", ''),
    ('marker_unh', "b'unhandled exception', ", ''),
    ('marker_err', ", b'--- error ---')", ')'),
    ('skip_text', "SKIPPED_DRAW = b'AsyncPipelines: skipped draw'", "SKIPPED_DRAW = b'AsyncPipelines: skipped draws'"),
    ('r1_mismatch_regex', "R1_MISMATCH = re.compile(rb'R1CenMismatch:')", "R1_MISMATCH = re.compile(rb'R1CenMismatch: x')"),
    ('r2_mismatch_nokey', "R2_MISMATCH = re.compile(rb'R2Mismatch(?:Key)?:')", "R2_MISMATCH = re.compile(rb'R2Mismatch:')"),
    ('r2_diverge_regex', "R2_DIVERGE = re.compile(rb'R2Diverge:')", "R2_DIVERGE = re.compile(rb'R2Diverges:')"),
    ('tables_no_d16', "TABLES = ('w4', 'w8', 'd16')", "TABLES = ('w4', 'w8')"),
    ('tables_no_w8', "TABLES = ('w4', 'w8', 'd16')", "TABLES = ('w4', 'd16')"),
    ('bad_keys_w4', "R1_BAD_KEYS = ('r1_w4_bad', 'r1_w8_bad', 'r1_d16_bad')", "R1_BAD_KEYS = ('r1_w8_bad', 'r1_d16_bad')"),
    ('bad_keys_w8', "R1_BAD_KEYS = ('r1_w4_bad', 'r1_w8_bad', 'r1_d16_bad')", "R1_BAD_KEYS = ('r1_w4_bad', 'r1_d16_bad')"),
    ('bad_keys_d16', "R1_BAD_KEYS = ('r1_w4_bad', 'r1_w8_bad', 'r1_d16_bad')", "R1_BAD_KEYS = ('r1_w4_bad', 'r1_w8_bad')"),
    ('ne_keys_incl', "R1_NE_KEYS = ('r1_incl', 'r1_xthr') + ", "R1_NE_KEYS = ('r1_xthr',) + "),
    ('ne_keys_xthr', "R1_NE_KEYS = ('r1_incl', 'r1_xthr') + ", "R1_NE_KEYS = ('r1_incl',) + "),
    ('ne_keys_w1', "tuple(k for k in R1_KEYS if k.startswith('r1_w1_'))", "tuple(k for k in R1_KEYS if k.startswith('r1_w1_q'))"),
    ('r2_bad_keys_key', "R2_BAD_KEYS = ('r2_bad', 'r2_bad_key')", "R2_BAD_KEYS = ('r2_bad',)"),
    ('r2_bad_keys_bad', "R2_BAD_KEYS = ('r2_bad', 'r2_bad_key')", "R2_BAD_KEYS = ('r2_bad_key',)"),
    ('rm_keys_n', "R2_RM_KEYS = ('r2_rm_ns', 'r2_rm_sl', 'r2_rm_n')", "R2_RM_KEYS = ('r2_rm_ns', 'r2_rm_sl')"),
    # ---- identities (window sums; NEAR +-8 by ROADMAP s120 item 6, FAR 0.1 %)
    ('id_hn_rhs', "('r1_hn=tex_hits', (ARM_P,), ('r1_hn',), ('tex_hits',), 'far')",
     "('r1_hn=tex_hits', (ARM_P,), ('r1_hn',), ('r1_hn',), 'far')"),
    ('id_hn_near', "('r1_hn=tex_hits', (ARM_P,), ('r1_hn',), ('tex_hits',), 'far')",
     "('r1_hn=tex_hits', (ARM_P,), ('r1_hn',), ('tex_hits',), 'near')"),
    ('id_mn_no_empty', "('r1_mn',), ('texmemo_collide', 'texmemo_empty'), 'far')", "('r1_mn',), ('texmemo_collide',), 'far')"),
    ('id_sn_rhs', "('r1_sn',), ('texmemo_stale',), 'far')", "('r1_sn',), ('r1_sn',), 'far')"),
    ('id_btexn_no_tnull', "('r1_hn', 'r1_mn', 'r1_sn', 'tnull_hit', 'tnull_miss'), 'far')",
     "('r1_hn', 'r1_mn', 'r1_sn', 'tnull_hit'), 'far')"),
    ('id_pb_far', "('r1_pb_n',), ('r1_self_h_n',), 'near')", "('r1_pb_n',), ('r1_self_h_n',), 'far')"),
    ('id_stg_m_only', "('r2_stg=bl_prep_n', (ARM_P, ARM_M),", "('r2_stg=bl_prep_n', (ARM_M,),"),
    ('id_stg_p_only', "('r2_stg=bl_prep_n', (ARM_P, ARM_M),", "('r2_stg=bl_prep_n', (ARM_P,),"),
    ('id_slots_no_nul', "('r2_cl_sl', 'r2_cl_nul', 'r2_mx_sl', 'r2_ot_sl'), ('bl_res_n',), 'far')",
     "('r2_cl_sl', 'r2_mx_sl', 'r2_ot_sl'), ('bl_res_n',), 'far')"),
    ('id_slots_p_only', "('r2_slots=bl_res_n', (ARM_P, ARM_M),", "('r2_slots=bl_res_n', (ARM_P,),"),
    ('id_rep_far', "('r2_rep',), ('r2_cl', 'r2_mx'), 'near')", "('r2_rep',), ('r2_cl', 'r2_mx'), 'far')"),
    ('id_rep_no_mx', "('r2_rep',), ('r2_cl', 'r2_mx'), 'near')", "('r2_rep',), ('r2_cl',), 'near')"),
    ('id_rep_m_only', "('r2_rep=cl+mx', (ARM_P, ARM_M),", "('r2_rep=cl+mx', (ARM_M,),"),
    ('id_nul_no_wo', "('r2_wr_n', 'r2_wo_n'), ('r2_nul_n',), 'near')", "('r2_wr_n',), ('r2_nul_n',), 'near')"),
    ('id_nul_far', "('r2_wr_n', 'r2_wo_n'), ('r2_nul_n',), 'near')", "('r2_wr_n', 'r2_wo_n'), ('r2_nul_n',), 'far')"),
    ('id_nul_p_only', "('r2_wr+wo=nul', (ARM_P, ARM_M),", "('r2_wr+wo=nul', (ARM_P,),"),
    ('id_rm_no_nul', "('r2_rm_sl',), ('r2_s_cl_sl', 'r2_s_cl_nul'), 'far')", "('r2_rm_sl',), ('r2_s_cl_sl',), 'far')"),
    ('r1_ids_no_hn', "R1_IDS = ('r1_hn=tex_hits', ", 'R1_IDS = ('),
    ('r1_ids_no_pb', " 'r1_pb_n=self_h_n')\n# R2 class bounds", ")\n# R2 class bounds"),
    ('r1_ids_no_btexn', "'r1_sn=stale', 'b_texn=lookups+null', ", "'r1_sn=stale', "),
    ('r2_ids_name', "for name, *_ in IDENTITIES if name.startswith('r2_')", "for name, *_ in IDENTITIES if name.startswith('r2_s')"),
    # ---- R2 class bounds
    ('bnd_rep', "    ('rep<=prog', ('r2_rep',), ('r2_prog',)),\n", ''),
    ('bnd_prog_noimg', "('r2_prog', 'r2_noimg', 'r2_big', 'r2_odd'), ('r2_stg',)", "('r2_prog', 'r2_big', 'r2_odd'), ('r2_stg',)"),
    ('bnd_prog_big', "('r2_prog', 'r2_noimg', 'r2_big', 'r2_odd'), ('r2_stg',)", "('r2_prog', 'r2_noimg', 'r2_odd'), ('r2_stg',)"),
    ('bnd_prog_odd', "('r2_prog', 'r2_noimg', 'r2_big', 'r2_odd'), ('r2_stg',)", "('r2_prog', 'r2_noimg', 'r2_big'), ('r2_stg',)"),
    ('bnd_prog_prog', "('r2_prog', 'r2_noimg', 'r2_big', 'r2_odd'), ('r2_stg',)", "('r2_noimg', 'r2_big', 'r2_odd'), ('r2_stg',)"),
    ('bnd_mx_eq', "    ('mx_eq<=mx_sl', ('r2_mx_eq',), ('r2_mx_sl',)),\n", ''),
    ('bnd_sl_hit', "    ('sl_hit<=sl_eq', ('r2_sl_hit',), ('r2_sl_eq',)),\n", ''),
    ('bnd_R_cl_sl', "('r2_cl_sl', 'r2_cl_nul', 'r2_mx_eq'), ('r2_sl_hit',)", "('r2_cl_nul', 'r2_mx_eq'), ('r2_sl_hit',)"),
    ('bnd_R_cl_nul', "('r2_cl_sl', 'r2_cl_nul', 'r2_mx_eq'), ('r2_sl_hit',)", "('r2_cl_sl', 'r2_mx_eq'), ('r2_sl_hit',)"),
    ('bnd_R_mx_eq', "('r2_cl_sl', 'r2_cl_nul', 'r2_mx_eq'), ('r2_sl_hit',)", "('r2_cl_sl', 'r2_cl_nul'), ('r2_sl_hit',)"),
    ('bnd_lod', "    ('lod<=cl_sl', ('r2_cl_lod',), ('r2_cl_sl',)),\n", ''),
    ('bnd_dcc', "    ('dcc<=cl_sl', ('r2_cl_dcc',), ('r2_cl_sl',)),\n", ''),
    ('bnd_bc', "    ('bc<=cl_sl', ('r2_cl_bc',), ('r2_cl_sl',)),\n", ''),
    ('bnd_tick', "    ('tick<=cl', ('r2_cl_tick',), ('r2_cl',)),\n", ''),
    ('bnd_meta', "    ('meta<=cl', ('r2_cl_meta',), ('r2_cl',)),\n", ''),
    ('bnd_s_cl_ns', "    ('s_cl_ns<=cl_ns', ('r2_s_cl_ns',), ('r2_cl_ns',)),\n", ''),
    ('bnd_s_cl_sl', "    ('s_cl_sl<=cl_sl', ('r2_s_cl_sl',), ('r2_cl_sl',)),\n", ''),
    ('bnd_s_cl_nul', "    ('s_cl_nul<=cl_nul', ('r2_s_cl_nul',), ('r2_cl_nul',)),\n", ''),
    ('bnd_s_mx_ns', "    ('s_mx_ns<=mx_ns', ('r2_s_mx_ns',), ('r2_mx_ns',)),\n", ''),
    ('bnd_s_mx_sl', "    ('s_mx_sl<=mx_sl', ('r2_s_mx_sl',), ('r2_mx_sl',)),\n", ''),
    ('bnd_s_ot_ns', "    ('s_ot_ns<=ot_ns', ('r2_s_ot_ns',), ('r2_ot_ns',)),\n", ''),
    ('bnd_s_ot_sl', "    ('s_ot_sl<=ot_sl', ('r2_s_ot_sl',), ('r2_ot_sl',)),\n", ''),
    ('bnd_guard_dropped', '        if lhs > rhs and not within_far(lhs - rhs, rhs):', '        if not within_far(lhs - rhs, rhs):'),
    ('bnd_no_tolerance', '        if lhs > rhs and not within_far(lhs - rhs, rhs):', '        if lhs > rhs:'),
    ('bnd_p_dropped', "    fails += r2_bound_failures(est_p, 'P')\n", ''),
    ('bnd_m_dropped', "    fails += r2_bound_failures(est_m, 'M')\n", ''),
    # ---- consequences (ROADMAP s120 item 4 quotes)
    ('csq_closed_text', "    'CLOSED': ('CLOSED - \"верхний", "    'CLOSED': ('NOT_OPENED - \"верхний"),
    ('csq_open_text', "    'OPEN': ('OPEN - \"точечный", "    'OPEN': ('OPEN - \"верхний"),
    ('csq_fail_text', "    'FAIL': ('FAIL - \"любой", "    'FAIL': ('FAIL - \"провал"),
    ('csq_ne_text', "    'NOT_EVALUABLE': ('NOT_EVALUABLE - \"провал", "    'NOT_EVALUABLE': ('NOT_EVALUABLE - \"любой"),
    ('csq_na_text', "    'NOT_ADMITTED': ('NOT_ADMITTED - \"повтор", "    'NOT_ADMITTED': ('NOT_ADMITTED - \"граница"),
    ('csq_border_text', "    'NOT_OPENED': ('NOT_OPENED - \"граница", "    'NOT_OPENED': ('NOT_OPENED - \"повтор"),
    # ---- small helpers
    ('marker_case', '    return any(k in low for k in MARKERS)', '    return any(k in line for k in MARKERS)'),
    ('idle_lt', '    return isinstance(v, (int, float)) and v <= IDLE_GPU_MAX', '    return isinstance(v, (int, float)) and v < IDLE_GPU_MAX'),
    ('ratio_zero', '    return None if den == 0 else num / den', '    return 0.0 if den == 0 else num / den'),
    ('two_se_1se', '    return 2.0 * statistics.stdev(values) / math.sqrt(len(values))',
     '    return statistics.stdev(values) / math.sqrt(len(values))'),
    ('two_se_pstdev', '    return 2.0 * statistics.stdev(values) / math.sqrt(len(values))',
     '    return 2.0 * statistics.pstdev(values) / math.sqrt(len(values))'),
    ('two_se_none_ok', '    if len(values) < 2 or any(v is None for v in values):',
     '    values = [v for v in values if v is not None]\n    if len(values) < 2:'),
    ('two_se_one_pair', '    if len(values) < 2 or any(v is None for v in values):', '    if len(values) < 1 or any(v is None for v in values):'),
    ('far_lt', '    return 1000 * abs(res) <= max(1000 * SKEW_FAR_ABS, SKEW_FAR_PERMILLE * abs(ref))',
     '    return 1000 * abs(res) < max(1000 * SKEW_FAR_ABS, SKEW_FAR_PERMILLE * abs(ref))'),
    ('far_signed', '    return 1000 * abs(res) <= max(1000 * SKEW_FAR_ABS, SKEW_FAR_PERMILLE * abs(ref))',
     '    return 1000 * res <= max(1000 * SKEW_FAR_ABS, SKEW_FAR_PERMILLE * abs(ref))'),
    ('far_abs_only', '    return 1000 * abs(res) <= max(1000 * SKEW_FAR_ABS, SKEW_FAR_PERMILLE * abs(ref))',
     '    return 1000 * abs(res) <= 1000 * SKEW_FAR_ABS'),
    ('regime_new_lt', '    if v <= BDA_NEW_MAX:', '    if v < BDA_NEW_MAX:'),
    ('regime_old_gt', '    if v >= BDA_OLD_MIN:', '    if v > BDA_OLD_MIN:'),
    ('regime_mixed', "    return 'MIXED'", "    return 'NEW'"),
    # ---- admission: GateArm / Gate lines
    ('arms_none_skip', '        if g is None:\n            return False, {}', '        if g is None:\n            continue'),
    ('arms_count', "        if arms != 2 or period != PERIOD or abba != 1 or arm not in (0, 1) or text != ARM_TEXT[arm]:",
     "        if period != PERIOD or abba != 1 or arm not in (0, 1) or text != ARM_TEXT[arm]:"),
    ('arms_period', "        if arms != 2 or period != PERIOD or abba != 1 or arm not in (0, 1) or text != ARM_TEXT[arm]:",
     "        if arms != 2 or abba != 1 or arm not in (0, 1) or text != ARM_TEXT[arm]:"),
    ('arms_abba', "        if arms != 2 or period != PERIOD or abba != 1 or arm not in (0, 1) or text != ARM_TEXT[arm]:",
     "        if arms != 2 or period != PERIOD or arm not in (0, 1) or text != ARM_TEXT[arm]:"),
    ('arms_text', "        if arms != 2 or period != PERIOD or abba != 1 or arm not in (0, 1) or text != ARM_TEXT[arm]:",
     "        if arms != 2 or period != PERIOD or abba != 1 or arm not in (0, 1):"),
    ('arms_frame', '        if frame != START + PERIOD * block or ABBA[block % 4] != arm or block in blocks:',
     '        if ABBA[block % 4] != arm or block in blocks:'),
    ('arms_order', '        if frame != START + PERIOD * block or ABBA[block % 4] != arm or block in blocks:',
     '        if frame != START + PERIOD * block or block in blocks:'),
    ('arms_dup', '        if frame != START + PERIOD * block or ABBA[block % 4] != arm or block in blocks:',
     '        if frame != START + PERIOD * block or ABBA[block % 4] != arm:'),
    ('arms_gap', '    ok = bool(blocks) and sorted(blocks) == list(range(len(blocks)))', '    ok = bool(blocks)'),
    ('gate_malformed_skip', '        if m is None:\n            return False\n        name = m.group(1).decode()',
     '        if m is None:\n            continue\n        name = m.group(1).decode()'),
    ('gate_name', "        if name not in ARM_VALUES[0] or (frame - START) % PERIOD != 0 or frame < START:",
     "        if (frame - START) % PERIOD != 0 or frame < START:"),
    ('gate_offblock', "        if name not in ARM_VALUES[0] or (frame - START) % PERIOD != 0 or frame < START:",
     "        if name not in ARM_VALUES[0] or frame < START:"),
    ('gate_block', "        if block not in blocks or m.group(2).decode() != ARM_VALUES[blocks[block]][name]:",
     "        if block in blocks and m.group(2).decode() != ARM_VALUES[blocks[block]][name]:"),
    ('gate_value', "        if block not in blocks or m.group(2).decode() != ARM_VALUES[blocks[block]][name]:",
     "        if block not in blocks:"),
    # ---- arm assertions (texts + gates_base)
    ('first_wins', '            out.setdefault(k, v)', '            out[k] = v'),
    ('eff_base_first', '        return a.get(name, g.get(name))', '        return g.get(name, a.get(name))'),
    ('assert_bindlap', "    ok = eff('bindlap') == '1'", '    ok = True'),
    ('assert_texmemo2', "    ok = ok and eff('texmemo2') == '0'\n", ''),
    ('assert_texfastcheck', "    ok = ok and eff('texfastcheck') == '0'\n", ''),
    ('assert_m4baton', "    ok = ok and eff('m4baton') == '0'\n", ''),
    ('assert_fslean', "    ok = ok and eff('fslean') == '0'\n", ''),
    ('assert_bindpack', "    ok = ok and eff('bindpack') in (None, '1')", "    ok = ok and eff('bindpack') in (None, '0', '1')"),
    ('assert_bindpack_absent', "    ok = ok and eff('bindpack') in (None, '1')", "    ok = ok and eff('bindpack') == '1'"),
    ('assert_bindwit', "    for name in ('bindwit', 'bindalt', 'blmove', 'bindfloor', 'cbmove'):",
     "    for name in ('bindalt', 'blmove', 'bindfloor', 'cbmove'):"),
    ('assert_bindalt', "    for name in ('bindwit', 'bindalt', 'blmove', 'bindfloor', 'cbmove'):",
     "    for name in ('bindwit', 'blmove', 'bindfloor', 'cbmove'):"),
    ('assert_blmove', "    for name in ('bindwit', 'bindalt', 'blmove', 'bindfloor', 'cbmove'):",
     "    for name in ('bindwit', 'bindalt', 'bindfloor', 'cbmove'):"),
    ('assert_bindfloor', "    for name in ('bindwit', 'bindalt', 'blmove', 'bindfloor', 'cbmove'):",
     "    for name in ('bindwit', 'bindalt', 'blmove', 'cbmove'):"),
    ('assert_cbmove', "    for name in ('bindwit', 'bindalt', 'blmove', 'bindfloor', 'cbmove'):",
     "    for name in ('bindwit', 'bindalt', 'blmove', 'bindfloor'):"),
    ('assert_absent_req', "        ok = ok and eff(name) in (None, '0')", "        ok = ok and eff(name) == '0'"),
    ('assert_r1cen', "    ok = ok and eff('r1cen') == ('2' if arm == ARM_P else '0')\n", ''),
    ('assert_r2cen', "    ok = ok and eff('r2cen') == ('2' if arm == ARM_P else '1')\n", ''),
    ('assert_r2cen_m2', "    ok = ok and eff('r2cen') == ('2' if arm == ARM_P else '1')", "    ok = ok and eff('r2cen') in ('1', '2')"),
    ('assert_one_arm', '    if not texts.get(ARM_P) or not texts.get(ARM_M):\n        return False\n', ''),
    ('assert_r1_ne_dropped', "    if not asserts_ok:\n        r1_ne.append('arm_asserts')\n", ''),
    ('assert_r2_ne_dropped', "    if not asserts_ok:\n        r2_ne.append('arm_asserts')\n", ''),
    # ---- parse_log
    ('parse_skip_attr', '                skipped.append(None if last_main is None else last_main + 1)',
     '                skipped.append(None if last_main is None else last_main)'),
    ('parse_r1_mismatch_match', '            if R1_MISMATCH.search(line):', '            if R1_MISMATCH.match(line):'),
    ('parse_r2_mismatch_dropped', "            if R2_MISMATCH.search(line):\n                lines['r2_mismatch'] += 1\n", ''),
    ('parse_pin_malformed', '                pins.append(int(mp.group(1)) if mp else -1)', '                pins.append(int(mp.group(1)) if mp else 1)'),
    ('parse_raw_main', "                if kind == 'x':\n                    for k in raw:", "                if kind == 'main':\n                    for k in raw:"),
    ('parse_dups', '                if n in seen[kind]:\n                    dups.add(n)\n', ''),
    ('parse_stdout_markers', "    if stdout_path is not None and Path(stdout_path).is_file():", "    if False:"),
    ('parse_marker_all_lines', '            if is_marker(line):\n                markers.append(line[:200].decode(\'utf-8\', \'replace\').strip())\n            if SKIPPED_DRAW',
     '            if SKIPPED_DRAW'),
    # ---- selection, streams, skip window
    ('select_arm_label', "        if all(complete(n) and seen['main'][n]['arm'] == arm and seen['main'][n]['blk'] == b for n in frames):",
     "        if all(complete(n) and seen['main'][n]['blk'] == b for n in frames):"),
    ('select_blk_label', "        if all(complete(n) and seen['main'][n]['arm'] == arm and seen['main'][n]['blk'] == b for n in frames):",
     "        if all(complete(n) and seen['main'][n]['arm'] == arm for n in frames):"),
    ('select_draws_ge', "est=[r for r in win if r['draws'] > DRAWS_MIN]", "est=[r for r in win if r['draws'] >= DRAWS_MIN]"),
    ('select_est_all', "est=[r for r in win if r['draws'] > DRAWS_MIN]", 'est=win'),
    ('select_dups', '        return n not in dups and all(seen[k].get(n) is not None for k in seen)',
     '        return all(seen[k].get(n) is not None for k in seen)'),
    ('streams_last_exempt', "            if n not in seen['main'] or n == parsed['last_main']:", "            if n not in seen['main']:"),
    ('streams_dups', '            if n in dups or any(seen[k].get(n) is None for k in seen):',
     '            if any(seen[k].get(n) is None for k in seen):'),
    ('streams_window_all', '        for n in block_frames(b)[KEEP[0]:KEEP[1]]:', '        for n in block_frames(b):'),
    ('skip_hi_le', '    return b in blocks and KEEP[0] <= pos < KEEP[1]', '    return b in blocks and KEEP[0] <= pos <= KEEP[1]'),
    ('skip_lo_lt', '    return b in blocks and KEEP[0] <= pos < KEEP[1]', '    return b in blocks and KEEP[0] < pos < KEEP[1]'),
    ('skip_any_block', '    return b in blocks and KEEP[0] <= pos < KEEP[1]', '    return KEEP[0] <= pos < KEEP[1]'),
    # ---- identity / partition machinery
    ('id_arm_filter', "            if blk['arm'] not in arms or name not in names:", '            if name not in names:'),
    ('id_near_lt', '                fine = abs(res) <= SKEW_NEAR', '                fine = abs(res) < SKEW_NEAR'),
    ('id_near_signed', '                fine = abs(res) <= SKEW_NEAR', '                fine = res <= SKEW_NEAR'),
    ('id_exact_per_frame', '                fine = abs(res) <= SKEW_NEAR',
     "                fine = all(sum(r[k] for k in left) == sum(r[k] for k in right) for r in blk['ident'])"),
    ('id_est_rows', "            lhs = sum(r[k] for r in blk['ident'] for k in left)", "            lhs = sum(r[k] for r in blk['est'] for k in left)"),
    ('ns_unit', "        ref = 1000 * sum(r['bl_res_us'] for r in blk['ident'])", "        ref = sum(r['bl_res_us'] for r in blk['ident'])"),
    ('ns_top_no_rounding', "        top = res - 1000 * len(blk['ident'])", '        top = res'),
    ('ns_low_dropped', '        if (res < 0 and not within_far(res, ref)) or (top > 0 and not within_far(top, ref)):',
     '        if top > 0 and not within_far(top, ref):'),
    ('ns_top_dropped', '        if (res < 0 and not within_far(res, ref)) or (top > 0 and not within_far(top, ref)):',
     '        if res < 0 and not within_far(res, ref):'),
    ('ns_partition_dropped', '    r2_ne += ns_partition_failures(done)\n', ''),
    # ---- R1 terms (design120 s2)
    ('r1_t_hit_hn', "    t_hit = ratio(s['r1_hit_ns'], s['r1_hit_t'])", "    t_hit = ratio(s['r1_hit_ns'], s['r1_hn'])"),
    ('r1_t_miss_all', "    t_miss = ratio(s['r1_mp_ns'], s['r1_mp'])", "    t_miss = ratio(s['r1_miss_ns'], s['r1_mn'])"),
    ('r1_t_fast_rb', "    t_fast = ratio(s['r1_rbf_ns'], s['r1_rbf_n'])", "    t_fast = ratio(s['r1_rb_ns'], s['r1_rb_n'])"),
    ('r1_t_ham_am', "    t_ham = ratio(s['r1_ham_ns'], s['r1_ham_t'])", "    t_ham = ratio(s['r1_ham_ns'], s['r1_am_n'])"),
    ('r1_pre_unscaled', "    pre = s['r1_mn'] - s['r1_mp']", "    pre = s['r1_mn']"),
    ('r1_look_no_sn', "    look = s['r1_hn'] + s['r1_mn'] + s['r1_sn']\n    out.update(",
     "    look = s['r1_hn'] + s['r1_mn']\n    out.update("),
    ('r1_look_hn_only', "    look = s['r1_hn'] + s['r1_mn'] + s['r1_sn']\n    out.update(", "    look = s['r1_hn']\n    out.update("),
    ('r1_lookups_unit', 'lookups=None if nf == 0 else look / nf,', 'lookups=None if nf == 0 else look,'),
    ('r1_nost_ns', "nost=None if nf == 0 else s['r1_nost'] / nf,", "nost=None if nf == 0 else s['r1_nost_ns'] / nf,"),
    ('r1_t_nost', "t_nost=ratio(s['r1_nost_ns'], s['r1_nost']))", "t_nost=ratio(s['r1_nost_ns'], s['r1_mn']))"),
    ('r1_guard_pre', " or pre == 0 or s['r1_mn'] == 0 or", ' or'),
    ('r1_guard_pb', " or s['r1_pb_n'] == 0 or nf == 0:", ' or nf == 0:'),
    ('r1_tT_all_misses', "        t_t = ratio(s['r1_%s_pns' % t], s['r1_%s_p' % t])", "        t_t = ratio(s['r1_miss_ns'], s['r1_mn'])"),  # [MH r1.md]
    ('r1_tT_pre_half', "        t_t = ratio(s['r1_%s_pns' % t], s['r1_%s_p' % t])", "        t_t = ratio(s['r1_%s_qns' % t], s['r1_%s_q' % t])"),
    ('r1_W_unscaled', "        w = s['r1_%s_q' % t] * s['r1_mn'] / pre", "        w = s['r1_%s_q' % t] + s['r1_%s_p' % t]"),     # [MH r1.md]
    ('r1_W_post', "        w = s['r1_%s_q' % t] * s['r1_mn'] / pre", "        w = s['r1_%s_p' % t] * s['r1_mn'] / pre"),
    ('r1_A_gross', '        a = w * (t_t - t_hit)', '        a = w * t_t'),
    ('r1_L_tmiss', "max(0.0, min(t_t, t_miss) - t_hit)", "max(0.0, t_miss - t_hit)"),                                  # [MH r1 review]
    ('r1_L_max', "max(0.0, min(t_t, t_miss) - t_hit)", "max(0.0, max(t_t, t_miss) - t_hit)"),
    ('r1_L_unclamped', "max(0.0, min(t_t, t_miss) - t_hit)", "(min(t_t, t_miss) - t_hit)"),
    ('r1_L_d16_guard', "        l_ = 0.0 if t == 'd16' else s['r1_%s_lose' % t]", "        l_ = s['r1_%s_lose' % t]"),
    ('r1_R_rb_price', "        r = s['r1_%s_rbns' % t] - s['r1_%s_rb' % t] * t_fast",
     "        r = s['r1_%s_rb' % t] * (s['r1_rb_ns'] / s['r1_rb_n'] - t_fast)"),                                         # [MH r1 review]
    ('r1_R_no_fast', "        r = s['r1_%s_rbns' % t] - s['r1_%s_rb' % t] * t_fast", "        r = s['r1_%s_rbns' % t]"),   # [MH r1.md]
    ('r1_E_unclamped', "        e = max(0.0, t_ham - t_hit) * s['r1_am_n'] * w / s['r1_mn']",
     "        e = (t_ham - t_hit) * s['r1_am_n'] * w / s['r1_mn']"),                                                      # [MH r1 review]
    ('r1_E_no_share', "        e = max(0.0, t_ham - t_hit) * s['r1_am_n'] * w / s['r1_mn']",
     "        e = max(0.0, t_ham - t_hit) * s['r1_am_n']"),
    ('r1_E_vs_miss', "        e = max(0.0, t_ham - t_hit) * s['r1_am_n'] * w / s['r1_mn']",
     "        e = max(0.0, t_ham - t_miss) * s['r1_am_n'] * w / s['r1_mn']"),
    ('r1_P_unclamped', "look * max(0.0, (s['r1_%s_pb_ns' % t] - s['r1_pb0_ns']) / s['r1_pb_n'])",
     "look * ((s['r1_%s_pb_ns' % t] - s['r1_pb0_ns']) / s['r1_pb_n'])"),
    ('r1_P_no_null', "look * max(0.0, (s['r1_%s_pb_ns' % t] - s['r1_pb0_ns']) / s['r1_pb_n'])",
     "look * max(0.0, s['r1_%s_pb_ns' % t] / s['r1_pb_n'])"),
    ('r1_P_d16_guard', "        p = 0.0 if t == 'd16' else look *", '        p = look *'),
    ('r1_C_no_P', '                         C=(a - l_ + r + e - p) / nf / NS_PER_US,', '                         C=(a - l_ + r + e) / nf / NS_PER_US,'),  # [MH]
    ('r1_C_no_L', '                         C=(a - l_ + r + e - p) / nf / NS_PER_US,', '                         C=(a + r + e - p) / nf / NS_PER_US,'),      # [MH r1.md]
    ('r1_C_plus_L', '                         C=(a - l_ + r + e - p) / nf / NS_PER_US,', '                         C=(a + l_ + r + e - p) / nf / NS_PER_US,'),  # [MH r1.md]
    ('r1_C_no_R', '                         C=(a - l_ + r + e - p) / nf / NS_PER_US,', '                         C=(a - l_ + e - p) / nf / NS_PER_US,'),
    ('r1_C_no_E', '                         C=(a - l_ + r + e - p) / nf / NS_PER_US,', '                         C=(a - l_ + r - p) / nf / NS_PER_US,'),
    ('r1_C_no_nf', '                         C=(a - l_ + r + e - p) / nf / NS_PER_US,', '                         C=(a - l_ + r + e - p) / NS_PER_US,'),
    ('r1_CnoE_with_E', 'C_noE=(a - l_ + r - p) / nf / NS_PER_US,', 'C_noE=(a - l_ + r + e - p) / nf / NS_PER_US,'),
    ('r1_W_report_unit', '        tables[t] = dict(W=w / nf, t_T=t_t,', '        tables[t] = dict(W=w, t_T=t_t,'),
    ('r1_A_unit', 'A=a / nf / NS_PER_US, L=l_ / nf / NS_PER_US,', 'A=a / nf, L=l_ / nf / NS_PER_US,'),
    ('r1_L_unit', 'A=a / nf / NS_PER_US, L=l_ / nf / NS_PER_US,', 'A=a / nf / NS_PER_US, L=l_ / nf,'),
    ('r1_R_unit', ' R=r / nf / NS_PER_US,\n', ' R=r / nf,\n'),
    ('r1_E_unit', '                         E=e / nf / NS_PER_US, P=p / nf / NS_PER_US,', '                         E=e / nf, P=p / nf / NS_PER_US,'),
    ('r1_P_unit', '                         E=e / nf / NS_PER_US, P=p / nf / NS_PER_US,', '                         E=e / nf / NS_PER_US, P=p / nf,'),
    ('r1_warm_sign', '                         warm_ns=None if t_pre is None else t_pre - t_t)', '                         warm_ns=None if t_pre is None else t_t - t_pre)'),
    ('r1_argmax_min', "    best = max(TABLES, key=lambda t: tables[t]['C'])", "    best = min(TABLES, key=lambda t: tables[t]['C'])"),
    ('r1_argmax_d16', "    best = max(TABLES, key=lambda t: tables[t]['C'])", "    best = 'd16'"),                                    # [MH r1.md]
    ('r1_argmax_noE', "    best = max(TABLES, key=lambda t: tables[t]['C'])", "    best = max(TABLES, key=lambda t: tables[t]['C_noE'])"),
    # ---- R1 controls (F1 arming, F3 samplers, F4 pre/post, F5 bounds, M-arm zeros)
    ('smp_band_lo_le', '        if v is None or v < band[0] or v > band[1]:', '        if v is None or v <= band[0] or v > band[1]:'),
    ('smp_band_hi_ge', '        if v is None or v < band[0] or v > band[1]:', '        if v is None or v < band[0] or v >= band[1]:'),
    ('smp_hit_den', "    for name, num, den, band in (('hit', s['r1_hit_t'], s['r1_hn'], HIT_BAND),",
     "    for name, num, den, band in (('hit', s['r1_hit_t'], s['r1_hn'] + s['r1_mn'], HIT_BAND),"),
    ('smp_post_den', "                                 ('post', s['r1_mp'], s['r1_mn'], POST_BAND),",
     "                                 ('post', s['r1_mp'], s['r1_mn'] + s['r1_sn'], POST_BAND),"),
    ('smp_fast_den', "                                 ('fast', s['r1_rbf_n'], s['texfast_ok'], FAST_BAND),",
     "                                 ('fast', s['r1_rbf_n'], s['texfast_no'], FAST_BAND),"),
    ('smp_self_no_s', "    selfn = s['r1_self_h_n'] + s['r1_self_m_n'] + s['r1_self_s_n']", "    selfn = s['r1_self_h_n'] + s['r1_self_m_n']"),
    ('smp_self_no_m', "    selfn = s['r1_self_h_n'] + s['r1_self_m_n'] + s['r1_self_s_n']", "    selfn = s['r1_self_h_n'] + s['r1_self_s_n']"),
    ('smp_self_look_no_sn', "    look = s['r1_hn'] + s['r1_mn'] + s['r1_sn']\n    selfn", "    look = s['r1_hn'] + s['r1_mn']\n    selfn"),
    ('bound_qp_ge', "        if s['r1_%s_q' % t] + s['r1_%s_p' % t] > s['r1_mn']:", "        if s['r1_%s_q' % t] + s['r1_%s_p' % t] >= s['r1_mn']:"),
    ('bound_qp_q_only', "        if s['r1_%s_q' % t] + s['r1_%s_p' % t] > s['r1_mn']:", "        if s['r1_%s_q' % t] > s['r1_mn']:"),
    ('bound_pns_ge', "        if s['r1_%s_pns' % t] > s['r1_mp_ns']:", "        if s['r1_%s_pns' % t] >= s['r1_mp_ns']:"),
    ('bound_lose_ge', "        if t != 'd16' and s['r1_%s_lose' % t] > s['r1_hn']:", "        if t != 'd16' and s['r1_%s_lose' % t] >= s['r1_hn']:"),
    ('bound_rb_ge', "        if s['r1_%s_rb' % t] > s['r1_%s_q' % t] + s['r1_%s_p' % t]:", "        if s['r1_%s_rb' % t] >= s['r1_%s_q' % t] + s['r1_%s_p' % t]:"),
    ('bound_rbn_ge', "    if s['r1_rb_n'] > s['texfast_no']:", "    if s['r1_rb_n'] >= s['texfast_no']:"),
    ('bound_rbn_dropped', "    if s['r1_rb_n'] > s['texfast_no']:\n        fails.append('bound_rb_n')\n", ''),
    ('prepost_rq_den', "            rq = ratio(bs['r1_%s_q' % t], bs['r1_mn'] - bs['r1_mp'])", "            rq = ratio(bs['r1_%s_q' % t], bs['r1_mn'])"),
    ('prepost_se_only', '        if se2 is None or abs(mean(diffs)) > max(se2, PREPOST_MAX):', '        if se2 is None or abs(mean(diffs)) > se2:'),
    ('prepost_floor_only', '        if se2 is None or abs(mean(diffs)) > max(se2, PREPOST_MAX):', '        if se2 is None or abs(mean(diffs)) > PREPOST_MAX:'),
    ('prepost_signed', '        if se2 is None or abs(mean(diffs)) > max(se2, PREPOST_MAX):', '        if se2 is None or mean(diffs) > max(se2, PREPOST_MAX):'),
    ('prepost_dropped', "            fails.append('prepost_' + t)\n", '            pass\n'),                                                    # [MH r1.md F4]
    ('armed_lt', '        if not est_p or any(r[k] <= 0 for r in est_p):', '        if not est_p or any(r[k] < 0 for r in est_p):'),
    ('armed_by_sum', '        if not est_p or any(r[k] <= 0 for r in est_p):', '        if not est_p or sum(r[k] for r in est_p) <= 0:'),
    ('armed_no_mp', "    for k in ('r1_hn', 'r1_mn', 'r1_hit_t', 'r1_mp'):", "    for k in ('r1_hn', 'r1_mn', 'r1_hit_t'):"),
    ('m_leak_dropped', "        fails.append('m_leak')\n", '        pass\n'),
    ('m_leak_rows_p', '    sm = ksum(est_m, R1_KEYS)\n', '    sm = ksum(est_m[:0], R1_KEYS)\n'),
    # ---- R2 terms (design120 s3; r2_s_* are subsets)
    ('r2_z_den', "    z = ratio(s['r2_nul_ns'], s['r2_nul_n'])", "    z = ratio(s['r2_nul_ns'], s['r2_wr_n'] + s['r2_wo_n'] + 1)"),
    ('r2_wrep_wo', "    w_rep = ratio(s['r2_wr_ns'], s['r2_wr_n'])", "    w_rep = ratio(s['r2_wo_ns'], s['r2_wo_n'])"),
    ('r2_woth_wr', "    w_oth = ratio(s['r2_wo_ns'], s['r2_wo_n'])", "    w_oth = ratio(s['r2_wr_ns'], s['r2_wr_n'])"),
    ('r2_st_den', "    st_bar = ratio(s['r2_st_ns'], s['r2_st_n'])", "    st_bar = ratio(s['r2_st_ns'], s['r2_nul_n'])"),
    ('r2_su_all', "    su = s['r2_cl_sl'] - s['r2_s_cl_sl']", "    su = s['r2_cl_sl']"),
    ('r2_zu_all', "    zu = s['r2_cl_nul'] - s['r2_s_cl_nul']", "    zu = s['r2_cl_nul']"),
    ('r2_s_disjoint', "    t_star = (s['r2_cl_ns'] - s['r2_s_cl_ns']) * (s['r2_cl_sl'] + s['r2_cl_nul']) / (su + zu) / nf",
     "    t_star = s['r2_cl_ns'] * (s['r2_cl_sl'] + s['r2_cl_nul'] + s['r2_s_cl_sl'] + s['r2_s_cl_nul']) / (s['r2_cl_sl'] + s['r2_cl_nul']) / nf"),  # [MH review r2]
    ('r2_tstar_all_clean', "    t_star = (s['r2_cl_ns'] - s['r2_s_cl_ns']) * (s['r2_cl_sl'] + s['r2_cl_nul']) / (su + zu) / nf",
     "    t_star = s['r2_cl_ns'] / nf"),                                                                                  # [MH r2 C10]
    ('r2_tstar_sampled', "    t_star = (s['r2_cl_ns'] - s['r2_s_cl_ns']) * (s['r2_cl_sl'] + s['r2_cl_nul']) / (su + zu) / nf",
     "    t_star = s['r2_s_cl_ns'] * (s['r2_cl_sl'] + s['r2_cl_nul']) / (s['r2_s_cl_sl'] + s['r2_s_cl_nul']) / nf"),
    ('r2_tstar_unscaled', "    t_star = (s['r2_cl_ns'] - s['r2_s_cl_ns']) * (s['r2_cl_sl'] + s['r2_cl_nul']) / (su + zu) / nf",
     "    t_star = (s['r2_cl_ns'] - s['r2_s_cl_ns']) / nf"),
    ('r2_tstar_S_only', "    t_star = (s['r2_cl_ns'] - s['r2_s_cl_ns']) * (s['r2_cl_sl'] + s['r2_cl_nul']) / (su + zu) / nf",
     "    t_star = (s['r2_cl_ns'] - s['r2_s_cl_ns']) * s['r2_cl_sl'] / su / nf"),
    ('r2_S_sl_hit', "    S = s['r2_cl_sl'] / nf", "    S = s['r2_sl_hit'] / nf"),                                                 # [MH r2.md]
    ('r2_Z_forgotten', "    Z = s['r2_cl_nul'] / nf", '    Z = 0.0'),                                                               # [MH r2.md]
    ('r2_L_bc', "    L = s['r2_cl_lod'] / nf", "    L = s['r2_cl_bc'] / nf"),
    ('r2_rep_cl', "    rep = s['r2_rep'] / nf", "    rep = s['r2_cl'] / nf"),
    ('r2_nonrep_noimg', "    nonrep = (s['r2_stg'] - s['r2_noimg'] - s['r2_big'] - s['r2_odd'] - s['r2_rep']) / nf",
     "    nonrep = (s['r2_stg'] - s['r2_big'] - s['r2_odd'] - s['r2_rep']) / nf"),
    ('r2_nonrep_big', "    nonrep = (s['r2_stg'] - s['r2_noimg'] - s['r2_big'] - s['r2_odd'] - s['r2_rep']) / nf",
     "    nonrep = (s['r2_stg'] - s['r2_noimg'] - s['r2_odd'] - s['r2_rep']) / nf"),
    ('r2_nonrep_odd', "    nonrep = (s['r2_stg'] - s['r2_noimg'] - s['r2_big'] - s['r2_odd'] - s['r2_rep']) / nf",
     "    nonrep = (s['r2_stg'] - s['r2_noimg'] - s['r2_big'] - s['r2_rep']) / nf"),
    ('r2_nonrep_rep', "    nonrep = (s['r2_stg'] - s['r2_noimg'] - s['r2_big'] - s['r2_odd'] - s['r2_rep']) / nf",
     "    nonrep = (s['r2_stg'] - s['r2_noimg'] - s['r2_big'] - s['r2_odd']) / nf"),
    ('r2_W_rep_no_z', '    W = (w_rep - z) * rep + (w_oth - z) * nonrep', '    W = w_rep * rep + (w_oth - z) * nonrep'),          # [MH r2 C10]
    ('r2_W_oth_no_z', '    W = (w_rep - z) * rep + (w_oth - z) * nonrep', '    W = (w_rep - z) * rep + w_oth * nonrep'),
    ('r2_W_weights_swapped', '    W = (w_rep - z) * rep + (w_oth - z) * nonrep', '    W = (w_rep - z) * nonrep + (w_oth - z) * rep'),
    ('r2_W_rep_only', '    W = (w_rep - z) * rep + (w_oth - z) * nonrep', '    W = (w_rep - z) * rep'),
    ('r2_ST_no_z', '    ST = (st_bar - z) * nonrep', '    ST = st_bar * nonrep'),
    ('r2_ST_rep', '    ST = (st_bar - z) * nonrep', '    ST = (st_bar - z) * rep'),
    ('r2_Cup_B', '    c_up = t_star - B_LO_NS * (S + Z) + R_RESET_NS * (S + Z) - W - ST', '    c_up = t_star - B_NS * (S + Z) + R_RESET_NS * (S + Z) - W - ST'),
    ('r2_Cup_reset_sign', '    c_up = t_star - B_LO_NS * (S + Z) + R_RESET_NS * (S + Z) - W - ST', '    c_up = t_star - B_LO_NS * (S + Z) - R_RESET_NS * (S + Z) - W - ST'),
    ('r2_Cup_S_only', '    c_up = t_star - B_LO_NS * (S + Z) + R_RESET_NS * (S + Z) - W - ST', '    c_up = t_star - B_LO_NS * S + R_RESET_NS * S - W - ST'),
    ('r2_Cup_no_W', '    c_up = t_star - B_LO_NS * (S + Z) + R_RESET_NS * (S + Z) - W - ST', '    c_up = t_star - B_LO_NS * (S + Z) + R_RESET_NS * (S + Z) - ST'),  # [MH r2.md]
    ('r2_Cup_no_ST', '    c_up = t_star - B_LO_NS * (S + Z) + R_RESET_NS * (S + Z) - W - ST', '    c_up = t_star - B_LO_NS * (S + Z) + R_RESET_NS * (S + Z) - W'),  # [MH r2.md]
    ('r2_Cup_play', '    c_up = t_star - B_LO_NS * (S + Z) + R_RESET_NS * (S + Z) - W - ST',
     '    c_up = t_star - B_LO_NS * (S + Z) + R_RESET_NS * (S + Z) - W - ST - A_TR_NS * (2 * S + Z)'),
    ('r2_CupB_lo', '    c_up_b = t_star - B_NS * (S + Z) + R_RESET_NS * (S + Z) - W - ST', '    c_up_b = t_star - B_LO_NS * (S + Z) + R_RESET_NS * (S + Z) - W - ST'),
    ('r2_Cpt_tr_play', '    c_pt_tr = t_star - ((B_NS + T_PRIME_NS) * S + (B_NS + N0_NS) * Z + LS_NS * L) - W - ST\n',
     '    c_pt_tr = t_star - ((B_NS + T_PRIME_NS) * S + (B_NS + N0_NS) * Z + LS_NS * L) - W - ST - A_TR_NS * (2 * S + Z)\n'),
    ('r2_Cpt_SZ', '    c_pt = t_star - ((B_NS + T_PRIME_NS) * S + (B_NS + N0_NS) * Z + LS_NS * L) - W - ST - A_TR_NS * (2 * S + Z)',
     '    c_pt = t_star - ((B_NS + T_PRIME_NS) * (S + Z) + LS_NS * L) - W - ST - A_TR_NS * (2 * S + Z)'),
    ('r2_Cpt_no_N0', '    c_pt = t_star - ((B_NS + T_PRIME_NS) * S + (B_NS + N0_NS) * Z + LS_NS * L) - W - ST - A_TR_NS * (2 * S + Z)',
     '    c_pt = t_star - ((B_NS + T_PRIME_NS) * S + B_NS * Z + LS_NS * L) - W - ST - A_TR_NS * (2 * S + Z)'),
    ('r2_Cpt_no_L', '    c_pt = t_star - ((B_NS + T_PRIME_NS) * S + (B_NS + N0_NS) * Z + LS_NS * L) - W - ST - A_TR_NS * (2 * S + Z)',
     '    c_pt = t_star - ((B_NS + T_PRIME_NS) * S + (B_NS + N0_NS) * Z) - W - ST - A_TR_NS * (2 * S + Z)'),
    ('r2_Cpt_atr_SZ', '    c_pt = t_star - ((B_NS + T_PRIME_NS) * S + (B_NS + N0_NS) * Z + LS_NS * L) - W - ST - A_TR_NS * (2 * S + Z)',
     '    c_pt = t_star - ((B_NS + T_PRIME_NS) * S + (B_NS + N0_NS) * Z + LS_NS * L) - W - ST - A_TR_NS * (S + Z)'),
    ('r2_Cpt_no_W', '    c_pt = t_star - ((B_NS + T_PRIME_NS) * S + (B_NS + N0_NS) * Z + LS_NS * L) - W - ST - A_TR_NS * (2 * S + Z)',
     '    c_pt = t_star - ((B_NS + T_PRIME_NS) * S + (B_NS + N0_NS) * Z + LS_NS * L) - ST - A_TR_NS * (2 * S + Z)'),
    ('r2_Cpt_no_ST', '    c_pt = t_star - ((B_NS + T_PRIME_NS) * S + (B_NS + N0_NS) * Z + LS_NS * L) - W - ST - A_TR_NS * (2 * S + Z)',
     '    c_pt = t_star - ((B_NS + T_PRIME_NS) * S + (B_NS + N0_NS) * Z + LS_NS * L) - W - A_TR_NS * (2 * S + Z)'),
    ('r2_Clo_no_P', '    c_lo = t_star - ((B_NS + T_PRIME_NS + P_NS) * S + (B_NS + N0_NS) * Z + LS_NS * L) - W - ST - A_TR_NS * (2 * S + Z)',
     '    c_lo = t_star - ((B_NS + T_PRIME_NS) * S + (B_NS + N0_NS) * Z + LS_NS * L) - W - ST - A_TR_NS * (2 * S + Z)'),
    ('r2_Clo_no_atr', '    c_lo = t_star - ((B_NS + T_PRIME_NS + P_NS) * S + (B_NS + N0_NS) * Z + LS_NS * L) - W - ST - A_TR_NS * (2 * S + Z)',
     '    c_lo = t_star - ((B_NS + T_PRIME_NS + P_NS) * S + (B_NS + N0_NS) * Z + LS_NS * L) - W - ST'),
    ('r2_pc_S', '    p_c = t_star / (S + Z)', '    p_c = t_star / S'),
    ('r2_ext_mx_sl', "    c_ext = c_pt + s['r2_mx_eq'] / nf * (p_c - B_NS - T_PRIME_NS)", "    c_ext = c_pt + s['r2_mx_sl'] / nf * (p_c - B_NS - T_PRIME_NS)"),
    ('r2_ext_no_T', "    c_ext = c_pt + s['r2_mx_eq'] / nf * (p_c - B_NS - T_PRIME_NS)", "    c_ext = c_pt + s['r2_mx_eq'] / nf * (p_c - B_NS)"),
    ('r2_ext_from_up', "    c_ext = c_pt + s['r2_mx_eq'] / nf * (p_c - B_NS - T_PRIME_NS)", "    c_ext = c_up + s['r2_mx_eq'] / nf * (p_c - B_NS - T_PRIME_NS)"),
    ('r2_ft_slots_sl', "    s_slots = s['r2_s_cl_sl'] + s['r2_s_cl_nul']", "    s_slots = s['r2_s_cl_sl']"),
    ('r2_ft_sign', "(s['r2_cl_ns'] - s['r2_s_cl_ns']) / (su + zu) - s['r2_s_cl_ns'] / s_slots",
     "s['r2_s_cl_ns'] / s_slots - (s['r2_cl_ns'] - s['r2_s_cl_ns']) / (su + zu)"),
    ('r2_rp_z_m', "        zp = ratio(sp['r2_nul_ns'], sp['r2_nul_n'])", '        zp = z'),
    ('r2_rp_no_z', "            per_slot = (sp['r2_rm_ns'] - zp * sp['r2_rm_n']) / sp['r2_rm_sl']", "            per_slot = sp['r2_rm_ns'] / sp['r2_rm_sl']"),
    ('r2_rp_S_only', '            c_rp = (per_slot * (S + Z) - W - ST) / NS_PER_US', '            c_rp = (per_slot * S - W - ST) / NS_PER_US'),
    ('r2_rp_no_W', '            c_rp = (per_slot * (S + Z) - W - ST) / NS_PER_US', '            c_rp = (per_slot * (S + Z) - ST) / NS_PER_US'),
    ('r2_krp_per_slot', "            k_rp = p_c - sp['r2_rm_ns'] / sp['r2_rm_sl']", '            k_rp = p_c - per_slot'),
    ('r2_krp_gt', '               K_rp_ok=None if k_rp is None else k_rp >= B_NS)', '               K_rp_ok=None if k_rp is None else k_rp > B_NS)'),
    ('r2_dcc_den', "dcc_share=ratio(s['r2_cl_dcc'], s['r2_cl_sl']))", "dcc_share=ratio(s['r2_cl_dcc'], s['r2_cl']))"),
    ('r2_guard_su', " or su + zu == 0 or nf == 0:", ' or nf == 0:'),
    ('r2_guard_SZ', '    if S + Z == 0:\n        return out\n', ''),
    ('r2_Tstar_unit', "    out.update(ok=True, S=S, Z=Z, L=L, rep=rep, nonrep=nonrep, T_star=t_star / NS_PER_US, W=W / NS_PER_US,",
     "    out.update(ok=True, S=S, Z=Z, L=L, rep=rep, nonrep=nonrep, T_star=t_star, W=W / NS_PER_US,"),
    ('r2_W_unit', 'T_star=t_star / NS_PER_US, W=W / NS_PER_US,', 'T_star=t_star / NS_PER_US, W=W,'),
    ('r2_ST_unit', '               ST=ST / NS_PER_US, p_c=p_c,', '               ST=ST, p_c=p_c,'),
    ('r2_Cup_unit', ' C_up=c_up / NS_PER_US, C_pt=c_pt / NS_PER_US,', ' C_up=c_up, C_pt=c_pt / NS_PER_US,'),
    ('r2_Cpt_unit', ' C_up=c_up / NS_PER_US, C_pt=c_pt / NS_PER_US,', ' C_up=c_up / NS_PER_US, C_pt=c_pt,'),
    ('r2_Clo_unit', ' C_lo=c_lo / NS_PER_US,\n', ' C_lo=c_lo,\n'),
    ('r2_Cext_unit', '               C_ext=c_ext / NS_PER_US, C_rp=c_rp,', '               C_ext=c_ext, C_rp=c_rp,'),
    ('r2_Crp_unit', '            c_rp = (per_slot * (S + Z) - W - ST) / NS_PER_US', '            c_rp = per_slot * (S + Z) - W - ST'),
    # ---- R2 controls (C2(b) arming, sampler, sanity)
    ('r2_armed_m', "    if sm['r2_stg'] <= 0 or sp['r2_stg'] <= 0:", "    if sp['r2_stg'] <= 0:"),
    ('r2_armed_p', "    if sm['r2_stg'] <= 0 or sp['r2_stg'] <= 0:", "    if sm['r2_stg'] <= 0:"),
    ('r2_m_replay_ns_only', '    if any(sm[k] != 0 for k in R2_RM_KEYS):', "    if sm['r2_rm_ns'] != 0:"),
    ('r2_m_replay_dropped', "        fails.append('m_replay')\n", '        pass\n'),
    ('r2_armed_replay_dropped', "        fails.append('armed_replay')\n", '        pass\n'),
    ('r2_smp_lo_le', '        if v is None or v < R2_SMP_BAND[0] or v > R2_SMP_BAND[1]:', '        if v is None or v <= R2_SMP_BAND[0] or v > R2_SMP_BAND[1]:'),
    ('r2_smp_hi_ge', '        if v is None or v < R2_SMP_BAND[0] or v > R2_SMP_BAND[1]:', '        if v is None or v < R2_SMP_BAND[0] or v >= R2_SMP_BAND[1]:'),
    ('r2_smp_no_big', "        v = ratio(s['r2_nul_n'], s['r2_stg'] - s['r2_noimg'] - s['r2_big'])", "        v = ratio(s['r2_nul_n'], s['r2_stg'] - s['r2_noimg'])"),
    ('r2_smp_no_noimg', "        v = ratio(s['r2_nul_n'], s['r2_stg'] - s['r2_noimg'] - s['r2_big'])", "        v = ratio(s['r2_nul_n'], s['r2_stg'] - s['r2_big'])"),
    ('r2_smp_odd', "        v = ratio(s['r2_nul_n'], s['r2_stg'] - s['r2_noimg'] - s['r2_big'])",
     "        v = ratio(s['r2_nul_n'], s['r2_stg'] - s['r2_noimg'] - s['r2_big'] - s['r2_odd'])"),
    ('r2_smp_p_only', "    for name, s in (('P', sp), ('M', sm)):", "    for name, s in (('P', sp),):"),
    ('r2_smp_m_only', "    for name, s in (('P', sp), ('M', sm)):", "    for name, s in (('M', sm),):"),
    ('r2_pc_open', '        if not PC_LO_NS <= terms[\'p_c\'] <= PC_HI_NS:', '        if not PC_LO_NS < terms[\'p_c\'] < PC_HI_NS:'),
    ('r2_order_lo_dropped', "        if not terms['C_lo'] <= terms['C_pt'] <= terms['C_up']:", "        if not terms['C_pt'] <= terms['C_up']:"),
    ('r2_order_up_dropped', "        if not terms['C_lo'] <= terms['C_pt'] <= terms['C_up']:", "        if not terms['C_lo'] <= terms['C_pt']:"),
    # ---- verdict ladder (s6)
    ('v_open_gt', '    if point >= BAR_US:', '    if point > BAR_US:'),
    ('v_closed_le', '    if upper + se2 < BAR_US:', '    if upper + se2 <= BAR_US:'),
    ('v_closed_minus_se', '    if upper + se2 < BAR_US:', '    if upper - se2 < BAR_US:'),                                          # [MH r1.md]
    ('v_closed_no_se', '    if upper + se2 < BAR_US:', '    if upper < BAR_US:'),
    ('v_closed_point', '    if upper + se2 < BAR_US:', '    if point + se2 < BAR_US:'),
    ('v_se_none_ok', '    if not_evaluable or point is None or upper is None or se2 is None:', '    if not_evaluable or point is None or upper is None:'),
    ('v_ne_over_fail', "    if fail:\n        return 'FAIL'\n    if not_evaluable or",
     "    if not_evaluable:\n        return 'NOT_EVALUABLE'\n    if fail:\n        return 'FAIL'\n    if not_evaluable or"),
    # ---- pre-registration
    ('pred_draft_checked', '    if draft:\n        return True, True\n', ''),
    ('pred_path_raw', "    path_ok = str(prereg.get('path') or '').replace('\\\\', '/') == PRED_PATH",
     "    path_ok = str(prereg.get('path') or '') == PRED_PATH"),
    ('pred_path_any', "    path_ok = str(prereg.get('path') or '').replace('\\\\', '/') == PRED_PATH", '    path_ok = True'),
    ('pred_file_sha', '    sha_ok = (hashlib.sha256(data).hexdigest() == pred_sha and len(data) == pred_bytes',
     '    sha_ok = (len(data) == pred_bytes'),
    ('pred_file_len', '    sha_ok = (hashlib.sha256(data).hexdigest() == pred_sha and len(data) == pred_bytes',
     '    sha_ok = (hashlib.sha256(data).hexdigest() == pred_sha'),
    ('pred_json_sha', "              and prereg.get('sha256') == pred_sha and prereg.get('bytes') == pred_bytes)",
     "              and prereg.get('bytes') == pred_bytes)"),
    ('pred_json_bytes', "              and prereg.get('sha256') == pred_sha and prereg.get('bytes') == pred_bytes)",
     "              and prereg.get('sha256') == pred_sha)"),
    ('pred_defaults_ignored', '    pred_sha = PRED_SHA if pred_sha is None else pred_sha', '    pred_sha = PRED_SHA'),
    # ---- admission checks
    ('chk_binary', "        binary=meta.get('binary_sha256') == BUILD_SHA,", '        binary=True,'),
    ('chk_installed', '        installed_now=installed_sha == BUILD_SHA,', '        installed_now=True,'),
    ('chk_pin_env', "        pinned=env.get('KYTY_GPU_CLOCK_PIN') == '1' and parsed['pins'] == [1],", "        pinned=parsed['pins'] == [1],"),
    ('chk_pin_lines', "        pinned=env.get('KYTY_GPU_CLOCK_PIN') == '1' and parsed['pins'] == [1],",
     "        pinned=env.get('KYTY_GPU_CLOCK_PIN') == '1' and 1 in parsed['pins'],"),
    ('chk_env_kyty', "        env_exact=kyty_env == ENV_EXPECT and meta.get('schedule') == SCHEDULE,", "        env_exact=meta.get('schedule') == SCHEDULE,"),
    ('chk_env_schedule', "        env_exact=kyty_env == ENV_EXPECT and meta.get('schedule') == SCHEDULE,", '        env_exact=kyty_env == ENV_EXPECT,'),
    ('chk_env_vk', '        env_vk=all(k in VK_ALLOWED for k in vk_env),', '        env_vk=True,'),
    ('chk_hold', "        hold=draft or meta.get('hold_s') == HOLD_S,", "        hold=meta.get('hold_s') == HOLD_S,"),
    ('chk_hold_any', "        hold=draft or meta.get('hold_s') == HOLD_S,", '        hold=True,'),
    ('chk_attempts_n', '        one_ok_attempt=len(atts) == 1 and len(ok_att) == 1,', '        one_ok_attempt=len(ok_att) == 1,'),
    ('chk_attempts_ok', '        one_ok_attempt=len(atts) == 1 and len(ok_att) == 1,', '        one_ok_attempt=len(atts) == 1,'),
    ('chk_ok_att_exit', "    ok_att = [a for a in atts if a.get('outcome') == 'ok' and a.get('hold_exit') is None]",
     "    ok_att = [a for a in atts if a.get('outcome') == 'ok']"),
    ('chk_prereg', '        prereg=prereg_ok,', '        prereg=True,'),
    ('chk_prereg_sha', '        prereg_sha=prereg_sha_ok,', '        prereg_sha=True,'),
    ('chk_gates_sha', "        gates_exact=(Path(gates_file).is_file() and sha_file(gates_file) == GATES_SHA and gates_text == base_text),",
     "        gates_exact=(Path(gates_file).is_file() and gates_text == base_text),"),
    ('chk_gates_text', "        gates_exact=(Path(gates_file).is_file() and sha_file(gates_file) == GATES_SHA and gates_text == base_text),",
     "        gates_exact=(Path(gates_file).is_file() and sha_file(gates_file) == GATES_SHA),"),
    ('chk_gates_ws', "    gates_text = ' '.join((meta.get('gates') or '').split())", "    gates_text = meta.get('gates') or ''"),
    ('chk_gate_lines', "        gate_lines=gate_lines_ok(parsed['gate_lines'], blocks),", '        gate_lines=True,'),
    ('chk_arms', '        arms=arms_fine,', '        arms=True,'),
    ('chk_marker', "        no_marker=not parsed['markers'],", '        no_marker=True,'),
    ('chk_skip', '        no_skip_window=not skipped_in,', '        no_skip_window=True,'),
    ('chk_streams', '        streams=streams_ok(parsed, blocks),', '        streams=True,'),
    ('chk_pairs_draft', '        pairs=draft or len(pairs) >= min_pairs,', '        pairs=len(pairs) >= min_pairs,'),
    ('chk_pairs_gt', '        pairs=draft or len(pairs) >= min_pairs,', '        pairs=draft or len(pairs) > min_pairs,'),
    ('chk_idle', '        idle=idle_ok(meta))', '        idle=True)'),
    ('chk_admitted_any', '    admitted = all(checks.values())', '    admitted = any(checks.values())'),
    ('na_r1_dropped', "    if not admitted:\n        r1_ne.append('not_admitted')\n", ''),
    ('na_r2_dropped', "    if not admitted:\n        r2_ne.append('not_admitted')\n", ''),
    # ---- R1 member: rows, resets, correctness, pairs
    ('r1_incl_gt', "    if any(parsed['raw'][k] != 0 for k in R1_NE_KEYS):", "    if any(parsed['raw'][k] > 0 for k in R1_NE_KEYS):"),
    ('r1_incl_dropped', "        r1_ne.append('incl_xthr_w1')\n", '        pass\n'),
    ('r1_resets_ge', '    if 100 * len(reset_blocks) > RESET_MAX_PCT * len(p_blocks):', '    if 100 * len(reset_blocks) >= RESET_MAX_PCT * len(p_blocks):'),
    ('r1_resets_dropped', "        r1_ne.append('resets')\n", '        pass\n'),
    ('r1_reset_est_rows', "    reset_blocks = [b for b in p_blocks if sum(r['r1_reset'] for r in done[b]['ident']) > 0]",
     "    reset_blocks = [b for b in p_blocks if sum(r['r1_reset'] for r in done[b]['ident']) > 1]"),
    ('r1_pairs_all', '    r1_pairs = [pr for pr in pairs if not any(b in reset_blocks for b in pr)]', '    r1_pairs = pairs'),
    ('r1_terms_all_p', '    r1 = r1_terms(ksum(est_p1, X_FIELDS + DRAW_FIELDS), len(est_p1))', '    r1 = r1_terms(ksum(est_p, X_FIELDS + DRAW_FIELDS), len(est_p))'),
    ('r1_ids_dropped', '    r1_ne += identity_failures(done, R1_IDS)\n', ''),
    ('r1_controls_dropped', '    r1_ne += r1_controls(done, r1_p, est_p1, est_m)\n', ''),
    ('r1_zero_den_dropped', "    if not r1['ok']:\n        r1_ne.append('zero_den')\n", ''),
    ('r1_pair_own_argmax', "        r1_pair_vals.append(t['tables'][r1['argmax']]['C'] if t['ok'] and r1['ok'] else None)",
     "        r1_pair_vals.append(t['C_R1'] if t['ok'] and r1['ok'] else None)"),
    ('r1_pair_m_block', "        pb = [b for b in pr if done[b]['arm'] == ARM_P][0]\n        t = r1_terms(",
     "        pb = [b for b in pr if done[b]['arm'] == ARM_M][0]\n        t = r1_terms("),
    ('r1_bad_windowed', "    r1_fail = sum(parsed['raw'][k] for k in R1_BAD_KEYS) > 0 or parsed['lines']['r1_mismatch'] > 0",
     "    r1_fail = sum(r[k] for r in est_p1 for k in R1_BAD_KEYS) > 0 or parsed['lines']['r1_mismatch'] > 0"),   # [MH r1 review]
    ('r1_bad_no_lines', "    r1_fail = sum(parsed['raw'][k] for k in R1_BAD_KEYS) > 0 or parsed['lines']['r1_mismatch'] > 0",
     "    r1_fail = sum(parsed['raw'][k] for k in R1_BAD_KEYS) > 0"),
    ('r1_bad_ignored', "    r1_fail = sum(parsed['raw'][k] for k in R1_BAD_KEYS) > 0 or parsed['lines']['r1_mismatch'] > 0",
     "    r1_fail = parsed['lines']['r1_mismatch'] > 0"),                                                                  # [MH r1.md]
    # ---- R2 member
    ('r2_tstar_from_p', '    r2 = r2_terms(ksum(est_m, R2_KEYS), len(est_m), ksum(est_p, R2_KEYS))',
     '    r2 = r2_terms(ksum(est_p, R2_KEYS), len(est_p), ksum(est_p, R2_KEYS))'),                                          # [MH ROADMAP item 5]
    ('r2_replay_from_m', '    r2 = r2_terms(ksum(est_m, R2_KEYS), len(est_m), ksum(est_p, R2_KEYS))',
     '    r2 = r2_terms(ksum(est_m, R2_KEYS), len(est_m), ksum(est_m, R2_KEYS))'),
    ('r2_ids_dropped', "    r2_ne += identity_failures(done, tuple(name for name, *_ in IDENTITIES if name.startswith('r2_')))\n", ''),
    ('r2_controls_dropped', '    r2_ne += r2_controls(done, est_p, est_m, r2)\n', ''),
    ('r2_zero_den_dropped', "    if not r2['ok']:\n        r2_ne.append('zero_den')\n", ''),
    ('r2_pair_p_block', "        mb = [b for b in pr if done[b]['arm'] == ARM_M][0]\n        t = r2_terms(",
     "        mb = [b for b in pr if done[b]['arm'] == ARM_P][0]\n        t = r2_terms("),
    ('r2_pair_up_is_pt', "        r2_pair_up.append(t['C_up'] if t['ok'] else None)", "        r2_pair_up.append(t['C_pt'] if t['ok'] else None)"),
    ('r2_se_of_pt', '    r2_se2 = two_se(r2_pair_up)', '    r2_se2 = two_se(r2_pair_pt)'),
    ('r2_bad_windowed', "    r2_fail = sum(parsed['raw'][k] for k in R2_BAD_KEYS) > 0 or parsed['lines']['r2_mismatch'] > 0",
     "    r2_fail = sum(r[k] for r in est_p + est_m for k in R2_BAD_KEYS) > 0 or parsed['lines']['r2_mismatch'] > 0"),
    ('r2_bad_no_lines', "    r2_fail = sum(parsed['raw'][k] for k in R2_BAD_KEYS) > 0 or parsed['lines']['r2_mismatch'] > 0",
     "    r2_fail = sum(parsed['raw'][k] for k in R2_BAD_KEYS) > 0"),
    ('r2_bad_ignored', "    r2_fail = sum(parsed['raw'][k] for k in R2_BAD_KEYS) > 0 or parsed['lines']['r2_mismatch'] > 0",
     "    r2_fail = parsed['lines']['r2_mismatch'] > 0"),                                                                  # [MH r2.md]
    ('r2_verdict_swapped', "    r2_v = verdict(r2_fail, bool(r2_ne), r2.get('C_pt'), r2.get('C_up'), r2_se2)",
     "    r2_v = verdict(r2_fail, bool(r2_ne), r2.get('C_up'), r2.get('C_pt'), r2_se2)"),
    ('r2_verdict_point_lo', "    r2_v = verdict(r2_fail, bool(r2_ne), r2.get('C_pt'), r2.get('C_up'), r2_se2)",
     "    r2_v = verdict(r2_fail, bool(r2_ne), r2.get('C_lo'), r2.get('C_up'), r2_se2)"),
    # ---- package R
    ('pk_pair_pt', '            pk_vals.append(None if a is None or r2_pair_up[i] is None else a + r2_pair_up[i])',
     '            pk_vals.append(None if a is None or r2_pair_pt[i] is None else a + r2_pair_pt[i])'),
    ('pk_se_added', '    pk_se2 = two_se(pk_vals)', '    pk_se2 = None if r1_se2 is None or r2_se2 is None else r1_se2 + r2_se2'),     # [MH r2 C10]
    ('pk_se_r2_only', '    pk_se2 = two_se(pk_vals)', '    pk_se2 = r2_se2'),
    ('pk_point_up', "    pk_point = None if r1_point is None or r2.get('C_pt') is None else r1_point + r2['C_pt']",
     "    pk_point = None if r1_point is None or r2.get('C_pt') is None else r1_point + r2['C_up']"),
    ('pk_upper_pt', "    pk_upper = None if r1_point is None or r2.get('C_up') is None else r1_point + r2['C_up']",
     "    pk_upper = None if r1_point is None or r2.get('C_up') is None else r1_point + r2['C_pt']"),
    ('pk_fail_r1_only', '    pk_v = verdict(r1_fail or r2_fail, bool(r1_ne or r2_ne), pk_point, pk_upper, pk_se2)',
     '    pk_v = verdict(r1_fail, bool(r1_ne or r2_ne), pk_point, pk_upper, pk_se2)'),
    ('pk_ne_r1_only', '    pk_v = verdict(r1_fail or r2_fail, bool(r1_ne or r2_ne), pk_point, pk_upper, pk_se2)',
     '    pk_v = verdict(r1_fail or r2_fail, bool(r1_ne), pk_point, pk_upper, pk_se2)'),
    ('pk_ne_r2_only', '    pk_v = verdict(r1_fail or r2_fail, bool(r1_ne or r2_ne), pk_point, pk_upper, pk_se2)',
     '    pk_v = verdict(r1_fail or r2_fail, bool(r2_ne), pk_point, pk_upper, pk_se2)'),
    # ---- reported only: price, BDA
    ('price_sign', '            diffs.append(None if mp_ is None or mm_ is None else mp_ - mm_)',
     '            diffs.append(None if mp_ is None or mm_ is None else mm_ - mp_)'),
    ('price_se_none', "        price[key] = dict(pair_mean=mean([d for d in diffs if d is not None]), two_se=two_se(diffs),",
     "        price[key] = dict(pair_mean=mean([d for d in diffs if d is not None]), two_se=None,"),
    ('price_arm_means', "                          P=mean([r[key] for r in est_p]), M=mean([r[key] for r in est_m]))",
     "                          P=mean([r[key] for r in est_m]), M=mean([r[key] for r in est_p]))"),
    ('bda_arms', "    bda = dict(P=mean([r['bda_scan'] for r in est_p]), M=mean([r['bda_scan'] for r in est_m]))",
     "    bda = dict(P=mean([r['bda_scan'] for r in est_m]), M=mean([r['bda_scan'] for r in est_p]))"),
    ('bda_regime_arm', "    bda.update(P_regime=regime(bda['P']), M_regime=regime(bda['M']))", "    bda.update(P_regime=regime(bda['M']), M_regime=regime(bda['M']))"),
    # ---- report and consequences
    ('csq_fail_after_na', "    if v == 'FAIL':\n        return 'CONSEQUENCE: %s %s' % (name, CONSEQUENCE['FAIL'])\n    if not res['admitted']:\n        return 'CONSEQUENCE: %s %s' % (name, CONSEQUENCE['NOT_ADMITTED'])",
     "    if not res['admitted']:\n        return 'CONSEQUENCE: %s %s' % (name, CONSEQUENCE['NOT_ADMITTED'])\n    if v == 'FAIL':\n        return 'CONSEQUENCE: %s %s' % (name, CONSEQUENCE['FAIL'])"),
    ('csq_na_ignored', "    if not res['admitted']:\n        return 'CONSEQUENCE: %s %s' % (name, CONSEQUENCE['NOT_ADMITTED'])\n", ''),
    ('rep_draft_line', "    if res['draft']:\n        out.append('DRAFT", "    if False:\n        out.append('DRAFT"),
    ('rep_na_line', "    if not res['admitted']:\n        out.append('REPORT OF A NOT_ADMITTED", "    if False:\n        out.append('REPORT OF A NOT_ADMITTED"),
    ('rep_member_upper', "        out.append('MEMBER %s: %s point=%s upper=%s 2se=%s' % (name, m['verdict'], fmt(m['point']), fmt(m['upper']),",
     "        out.append('MEMBER %s: %s point=%s upper=%s 2se=%s' % (name, m['verdict'], fmt(m['point']), fmt(m['point']),"),
    ('rep_package_label', "    out.append('PACKAGE R: %s point=%s upper=%s 2se=%s' % (p['verdict'], fmt(p['point']), fmt(p['upper']),",
     "    out.append('MEMBER R: %s point=%s upper=%s 2se=%s' % (p['verdict'], fmt(p['point']), fmt(p['upper']),"),
    ('rep_verdict_failed', "    out.append('VERDICT: %s%s%s' % (res['verdict'], ' failed=' + ','.join(failed) if failed else '',",
     "    out.append('VERDICT: %s%s%s' % (res['verdict'], '',"),
    ('rep_ext_gt', 'if ext is not None and ext >= BAR_US else', 'if ext is not None and ext > BAR_US + 20 else'),
    ('rep_ext_any_verdict', "    out.append(consequence('R2', res['R2']['verdict'], res, per_slot if res['R2']['verdict'] == 'CLOSED' else ''))",
     "    out.append(consequence('R2', res['R2']['verdict'], res, ''))"),
    ('rep_table_dropped', "                           ' Table %s.' % t1['argmax'] if res['R1']['verdict'] == 'OPEN' else ''))",
     "                           ''))"),
    ('rep_open_members_dropped', "        carry = ' Open members: %s.' % sm['carrying']", "        carry = ''"),
    ('rep_superseded_dropped', "    if p['verdict'] != 'OPEN' and sm['verdict'] == 'OPEN':", "    if False:"),
    ('rep_superseded_always', "    if p['verdict'] != 'OPEN' and sm['verdict'] == 'OPEN':", "    if sm['verdict'] == 'OPEN':"),
    ('rep_superseded_any', "    if p['verdict'] != 'OPEN' and sm['verdict'] == 'OPEN':", "    if p['verdict'] != 'OPEN':"),
    ('rep_summary_tail_dropped', "        tail = ' Open: %s.' % sm['carrying']", "        tail = ''"),
    ('rep_summary_perslot_dropped', "    elif sm['verdict'] == 'CLOSED':\n        tail = per_slot\n", ''),
    ('rep_summary_line_dropped', "    out.append('CONSEQUENCE: %s%s' % (CONSEQUENCE[sm['verdict']], tail))\n", ''),
    ('rep_summary_pkg_verdict', "    out.append('CONSEQUENCE: %s%s' % (CONSEQUENCE[sm['verdict']], tail))",
     "    out.append('CONSEQUENCE: %s%s' % (CONSEQUENCE[p['verdict']], tail))"),
    # ---- the summary consequence (ROADMAP s120 item 4 addendum): FAIL > NOT_ADMITTED > OPEN (names) > package
    ('sum_fail_dropped', "    if r1_fail or r2_fail:\n        summary = 'FAIL'", "    if False:\n        summary = 'FAIL'"),
    ('sum_fail_r1_only', "    if r1_fail or r2_fail:\n        summary = 'FAIL'", "    if r1_fail:\n        summary = 'FAIL'"),
    ('sum_fail_r2_only', "    if r1_fail or r2_fail:\n        summary = 'FAIL'", "    if r2_fail:\n        summary = 'FAIL'"),
    ('sum_na_dropped', "    elif not admitted:\n        summary = 'NOT_ADMITTED'", "    elif False:\n        summary = 'NOT_ADMITTED'"),
    ('sum_na_before_fail', "    if r1_fail or r2_fail:\n        summary = 'FAIL'\n    elif not admitted:\n        summary = 'NOT_ADMITTED'",
     "    if not admitted:\n        summary = 'NOT_ADMITTED'\n    elif r1_fail or r2_fail:\n        summary = 'FAIL'"),
    ('sum_open_members_ignored', "    elif open_m or pk_v == 'OPEN':", "    elif pk_v == 'OPEN':"),
    ('sum_open_before_na', "    elif not admitted:\n        summary = 'NOT_ADMITTED'\n    elif open_m or pk_v == 'OPEN':\n        summary = 'OPEN'",
     "    elif open_m or pk_v == 'OPEN':\n        summary = 'OPEN'\n    elif not admitted:\n        summary = 'NOT_ADMITTED'"),
    ('sum_open_pkg_closed', "    elif open_m or pk_v == 'OPEN':", "    elif open_m or pk_v == 'CLOSED':"),
    ('sum_names_not_opened', "    open_m = [n for n, v in (('R1', r1_v), ('R2', r2_v)) if v == 'OPEN']",
     "    open_m = [n for n, v in (('R1', r1_v), ('R2', r2_v)) if v in ('OPEN', 'NOT_OPENED')]"),
    ('sum_name_r2_from_r1', "    open_m = [n for n, v in (('R1', r1_v), ('R2', r2_v)) if v == 'OPEN']",
     "    open_m = [n for n, v in (('R1', r1_v), ('R2', r1_v)) if v == 'OPEN']"),
    ('sum_name_r1_from_r2', "    open_m = [n for n, v in (('R1', r1_v), ('R2', r2_v)) if v == 'OPEN']",
     "    open_m = [n for n, v in (('R1', r2_v), ('R2', r2_v)) if v == 'OPEN']"),
    ('sum_together_dropped', "('R1+R2 (together)' if pk_v == 'OPEN' else '')", "('' if pk_v == 'OPEN' else '')"),
    ('sum_together_always', "('R1+R2 (together)' if pk_v == 'OPEN' else '')", "('R1+R2 (together)' if True else '')"),
    ('sum_else_not_pk', "    else:\n        summary = pk_v\n", "    else:\n        summary = 'NOT_OPENED'\n"),
    ('sum_not_stored', '               summary=summary, price=price, bda_scan=bda)',
     "               summary=dict(verdict=pk_v, carrying='', open_members=[]), price=price, bda_scan=bda)"),
    ('rep_pkg_closed_perslot', '    elif p[\'verdict\'] == \'CLOSED\':\n        carry = per_slot\n', ''),
    ('rep_bda_regime', "    out.append('bda_scan P %s (%s) M %s (%s)' % (fmt(res['bda_scan']['P']), res['bda_scan']['P_regime'],",
     "    out.append('bda_scan P %s (%s) M %s (%s)' % (fmt(res['bda_scan']['P']), res['bda_scan']['M_regime'],"),
    ('rep_krp_label', "('kept' if t2['K_rp_ok'] else 'rejected (K_rp < B)')", "('kept' if t2['K_rp'] else 'rejected (K_rp < B)')"),
]
if __name__ == '__main__':
    STAGE.mkdir(parents=True, exist_ok=True)
    killed = 0
    for name, old, new in MUTANTS:
        if SRC.count(old) != 1:
            print('%-26s ANCHOR x%d' % (name, SRC.count(old)))
            continue
        path = STAGE / ('mut_rpk120_%s.py' % name)
        path.write_bytes(SRC.replace(old, new).encode('utf-8'))
        r = subprocess.run([sys.executable, 'C:/kyty/s120/test_rpk120.py', str(path)], capture_output=True, text=True)
        killed += r.returncode != 0
        print('%-26s %s' % (name, 'killed' if r.returncode != 0 else 'SURVIVED'))
        path.unlink()
    print('killed %d of %d' % (killed, len(MUTANTS)))
