"""Session 115: mutants of check115.py (from the sealed mut_check114.py by make_check115.py) - each must be killed by
test_check115.py; run through mutlib v2 (frozen copy) --control --no-memo on the sealed copy."""
import subprocess
import sys
from pathlib import Path

STAGE = Path('C:/kyty/s106_stage')
SRC = Path('C:/kyty/s115/check115.py').read_text(encoding='utf-8')
MUTANTS = [
    ('frames', 'MIN_FRAMES = 3000', 'MIN_FRAMES = 2999'),
    ('rows', 'MIN_ROWS = 1000', 'MIN_ROWS = 999'),
    ('pin_count', 'pins == 1 and pin1 == 1', 'pin1 >= 1'),
    ('pin_mode', "pin1 += int(line.startswith(b'GpuClockPin: mode 1'))", 'pin1 += 1'),
    ('pin_env', "env.get('KYTY_GPU_CLOCK_PIN') == '1' and ", ''),
    ('rec', "recorded=bool(env.get('KYTY_REC')),", 'recorded=True,'),
    ('sched', "no_schedule='KYTY_GATE_SCHEDULE' not in env,", 'no_schedule=True,'),
    ('ckpt', "no_checkpoints='KYTY_GPU_CHECKPOINTS' not in env,", 'no_checkpoints=True,'),
    ('att_len', 'len(atts) == 1 and ', ''),
    ('def_daslot', "' daslot=' not in gates and ", ''),
    ('def_daguard', "' daguard=' not in gates and ", ''),
    ('def_cspfree', "' daguard=' not in gates and ' cspfree=' not in gates", "' daguard=' not in gates"),
    ('glitch', "int(mg.group(1)) == 0", "int(mg.group(1)) <= 1"),
    ('missing', 'rows >= MIN_ROWS and missing == 0', 'rows >= MIN_ROWS'),
    ('free', "tot['da_q_free'] > 0 and ", ''),
    ('noguard', " and tot['da_q_noguard'] == 0,", ','),
    ('slot_bad', "slot_no_bad=tot['da_slot_bad'] == 0,", 'slot_no_bad=True,'),
    ('hit', "tot['cspfree_hit'] > 0 and ", ''),
    ('free_bad', " and tot['cspfree_bad'] == 0,", ','),
    ('guard', "guard=tot['cs_sync_new'] == 0,", 'guard=True,'),
    ('stdout', "    if so.is_file():", "    if False:"),
    ('stable', 'int(m.group(1)) >= stable', 'int(m.group(1)) >= 0'),
    ('marker_fatal', "b'fatal', ", ''),
    ('installed', 'installed_now=installed_sha == BUILD_SHA,', 'installed_now=True,'),
    ('def_bdanarrow', "and ' bdanarrow=' not in gates)", 'and True)'),
    ('shift', "no_shift='KYTY_BUFFER_GC_TRIGGER_SHIFT_MB' not in env,", 'no_shift=True,'),
    ('nskip', "tot['bda_nskip'] == 0 and ", ''),
    ('would', " and tot['bda_nwould'] == 0,", ','),
    ('gc_count', 'len(gc_lines) == 1 and ', ''),
    ('gc_shift', " and gc_lines[0].endswith(' shift_mb=0'),", ','),
    ('gc_collect', "gc_lines.append(line[:200].decode('utf-8', 'replace').strip())", 'pass'),
    ('title_knob', "no_title_knob=' titleasync=' not in gates,", 'no_title_knob=True,'),
    ('no_hold', "no_hold='KYTY_PREPARE_HOLD_MS' not in env,", 'no_hold=True,'),
    ('title_n', "(tot['pres_title_n'] > 0", '(True'),
    ('title_cap', 'TITLE_WALL_MAX_NS = 60000', 'TITLE_WALL_MAX_NS = 60001'),
    ('title_cap_lt', "<= TITLE_WALL_MAX_NS * tot['pres_title_n']", "< TITLE_WALL_MAX_NS * tot['pres_title_n']"),
    ('title_wall', "and tot['pres_title_ns'] <= TITLE_WALL_MAX_NS * tot['pres_title_n']),", 'and True),'),
    ('ov_sum', "tot['present_overlap'] == 0 and ", ''),
    ('ov_lines', " and overlap_lines == 0,", ','),
    ('ov_collect', '                overlap_lines += 1', '                overlap_lines += 0'),
    ('all_merge', "res['checks'].update(boot['checks'])", 'pass'),
    ('all_verdict', "res['verdict'] = 'PASS' if all(res['checks'].values()) else 'FAIL'", "res['verdict'] = res['verdict']"),
    ('vid_binary', "binary=meta.get('binary_sha256') == BUILD_SHA,", 'binary=True,'),
    ('vid_ok_exit', "ok_att = [a for a in atts if a.get('outcome') == 'ok' and a.get('hold_exit') is None]", "ok_att = [a for a in atts if a.get('outcome') == 'ok']"),
    ('ov_mid', "if line.find(b'PresentOverlap:') >= 0:", "if line.startswith(b'PresentOverlap:'):"),
    ('adm_idle_vid', 'adm_idle_vid=idle_ok(meta))', 'adm_idle_vid=True)'),
    ('idle_max', 'IDLE_GPU_MAX = 10', 'IDLE_GPU_MAX = 11'),
    ('idle_le', 'v <= IDLE_GPU_MAX', 'v < IDLE_GPU_MAX'),
    ('idle_type', 'isinstance(v, (int, float)) and ', ''),
    ('hold_ms', 'HOLD_MS = 10000', 'HOLD_MS = 9999'),
    ('adm_verdict', "    if not res['admitted']:", '    if False:'),
    ('adm_filter', "k.startswith('adm_')", "k.startswith('adm_x')"),
    ('bt_tags', "BOOT_TAGS = ('boot115a', 'boot115b', 'boot115c')", "BOOT_TAGS = ('boot115a', 'boot115b')"),
    ('bt_control_tag', "BOOT_CONTROL = 'boot115b'", "BOOT_CONTROL = 'boot115a'"),
    ('bt_ship_tag', "BOOT_SHIP = 'boot115c'", "BOOT_SHIP = 'boot115a'"),
    ('bt_control', 'control = tag == BOOT_CONTROL', 'control = tag == BOOT_SHIP'),
    ('bt_binary', "p + '_binary': bmeta.get('binary_sha256') == BUILD_SHA,", "p + '_binary': True,"),
    ('bt_pin_list', 'else bpin == [True]', 'else True in bpin'),
    ('bt_ctl_pin', 'bpin in ([], [True])', 'bpin == [True]'),
    ('bt_ctl_pin_any', 'bpin in ([], [True])', 'True'),
    ('bt_ctl_prefix', "p = 'adm_' + x if control else x", 'p = x'),
    ('bt_pin_mode', "bpin.append(line.startswith(b'GpuClockPin: mode 1'))", 'bpin.append(True)'),
    ('bt_pin_env', " and benv.get('KYTY_GPU_CLOCK_PIN') == '1',", ','),
    ('bt_hold_env', "p + '_hold_env': benv.get('KYTY_PREPARE_HOLD_MS') == str(HOLD_MS),", "p + '_hold_env': True,"),
    ('bt_sched', "p + '_no_schedule': 'KYTY_GATE_SCHEDULE' not in benv,", "p + '_no_schedule': True,"),
    ('bt_ckpt', "p + '_no_checkpoints': 'KYTY_GPU_CHECKPOINTS' not in benv,", "p + '_no_checkpoints': True,"),
    ('bt_shift', "p + '_no_shift': 'KYTY_BUFFER_GC_TRIGGER_SHIFT_MB' not in benv,", "p + '_no_shift': True,"),
    ('bt_defaults', "p + '_default_runs': all(' %s=' % k not in bgates for k in BOOT_DEFAULTS),", "p + '_default_runs': True,"),
    ('bt_def_daslot', "('daslot', 'daguard',", "('daguard',"),
    ('bt_def_daguard', "'daslot', 'daguard', 'cspfree'", "'daslot', 'cspfree'"),
    ('bt_def_cspfree', "'daguard', 'cspfree', 'bdanarrow'", "'daguard', 'bdanarrow'"),
    ('bt_def_bdanarrow', "'cspfree', 'bdanarrow', 'titleasync'", "'cspfree', 'titleasync'"),
    ('bt_def_titleasync', "'bdanarrow', 'titleasync')", "'bdanarrow')"),
    ('bt_hold_line', "bholds == ['PrepareHold: ms=%d' % HOLD_MS]", 'len(bholds) == 1'),
    ('bt_hold_collect', "bholds.append(line.decode('utf-8', 'replace').strip())", 'pass'),
    ('bt_knob_ship', "benv.get('KYTY_TITLE_ASYNC') == '1' if tag == BOOT_SHIP", 'True if tag == BOOT_SHIP'),
    ('bt_knob_other', "else 'KYTY_TITLE_ASYNC' not in benv", 'else True'),
    ('bt_main_ctl', "benv.get('KYTY_PREPARE_MAIN_PRESENT') == '1' if control", 'True if control'),
    ('bt_main_fix', "else 'KYTY_PREPARE_MAIN_PRESENT' not in benv", 'else True'),
    ('bt_idle', "'adm_idle_' + x: idle_ok(bmeta)}", "'adm_idle_' + x: True}"),
    ('bt_ctl_main', "bmains == ['PrepareMainPresent: mode 1']", 'True'),
    ('bt_ctl_main_collect', "bmains.append(line.decode('utf-8', 'replace').strip())", 'pass'),
    ('bt_ctl_fatal', "'adm_' + x + '_fatal': bfatal_after_hold,", "'adm_' + x + '_fatal': True,"),
    ('bt_ctl_nowait', "'adm_' + x + '_no_wait': not bwaits}", "'adm_' + x + '_no_wait': True}"),
    ('bt_fatal_after', 'bfatal_after_hold |= bool(bholds)', 'bfatal_after_hold |= True'),
    ('bt_fatal_mid', 'if FATAL_SITE in line:', 'if line.startswith(FATAL_SITE):'),
    ('bt_fatal_site', "FATAL_SITE = b'commandRecorder.cpp:326'", "FATAL_SITE = b'commandRecorder.cpp:999'"),
    ('bt_att_len', 'len(batts) == 1 and ', ''),
    ('bt_att_ok', ' and len(bok) == 1,', ','),
    ('bt_att_exit', "bok = [a for a in batts if a.get('outcome') == 'ok' and a.get('hold_exit') is None]", "bok = [a for a in batts if a.get('outcome') == 'ok']"),
    ('bt_one', 'one = len(bwaits) == 1', 'one = len(bwaits) >= 1'),
    ('bt_wait_gt', 'bwaits[0][0] >= HOLD_MS', 'bwaits[0][0] > HOLD_MS'),
    ('bt_wait_any', 'bwaits[0][0] >= HOLD_MS', 'bwaits[0][0] >= 0'),
    ('bt_pmain', 'bwaits[0][2] == 0', 'bwaits[0][2] is not None'),
    ('bt_pmain_le', 'bwaits[0][2] == 0', 'bwaits[0][2] <= 1'),
    ('bt_pother_gt', 'bwaits[0][1] >= PRESENTS_MIN', 'bwaits[0][1] > PRESENTS_MIN'),
    ('bt_pother_c', 'PRESENTS_MIN = 300', 'PRESENTS_MIN = 299'),
    ('bt_pother_none', 'bwaits[0][1] is not None and ', ''),
    ('bt_no_main_line', "x + '_no_main_line': not bmains,", "x + '_no_main_line': True,"),
    ('bt_no_fatal', "x + '_no_fatal': not bfatal_any,", "x + '_no_fatal': True,"),
    ('bt_no_overlap', "x + '_no_overlap': bov_lines == 0,", "x + '_no_overlap': True,"),
    ('bt_ov_mid', "if b'PresentOverlap:' in line:", "if line.startswith(b'PresentOverlap:'):"),
    ('bt_no_marker', "x + '_no_marker': not bmarkers}", "x + '_no_marker': True}"),
    ('bt_stdout', '    if bso.is_file():', '    if False:'),
]
killed = 0
for name, old, new in MUTANTS:
    if SRC.count(old) != 1:
        print('%-14s ANCHOR x%d' % (name, SRC.count(old)))
        continue
    path = STAGE / ('mut_check115_%s.py' % name)
    path.write_text(SRC.replace(old, new), encoding='utf-8', newline='\n')
    r = subprocess.run([sys.executable, 'C:/kyty/s115/test_check115.py', str(path)], capture_output=True, text=True)
    killed += r.returncode != 0
    print('%-14s %s' % (name, 'killed' if r.returncode != 0 else 'SURVIVED'))
    path.unlink()
print('killed %d of %d' % (killed, len(MUTANTS)))
