import json,csv,statistics as S,hashlib
from pathlib import Path
from collections import Counter,defaultdict
O=Path('C:/kyty/s99/r6_raw/life_analysis');R=O.parents[1]
ww=json.loads((O/'windows.json').read_text());events=list(csv.DictReader((O/'events.csv').open()))
for e in events:
 for k in ['frame','fmt','w','h','mips','bytes','logline','line','address_seen','prior_free_frame','event_idx','block']:
  if e.get(k):e[k]=int(e[k])
text=['# Causal composition (diagnostic only)','', 'GC is mapped from reported operator():3402, confirmed at textureCache.cpp:3402. The baseline printed-name assumption was corrected explicitly. No change of acceptance rules.','']
text+=['## Coverage and exclusion of an armed-interior eviction storm','', 'Whole raw SHA256 matches fd5f717d1b9ecdc0ee70b4e4c24a9607f96cfc3fffab895b4c2de8128a7172d5. 64,121 events =32,652 creates+31,469 frees. Sum img_new32,593 differs by59, exactly55 creates before first draw snapshot plus4 after last. Sum img_free31,465 differs by4 terminal frees at frame6210. Thus there is no unexplained global create/free deficit. First/last FrameTrace n=2/6210.','', 'All31,469 frees are assigned:15,942 before gates,15,446 unarmed,81 armed boundary, ZERO armed interior. GC subset10,581=6,679 pregate+3,901 unarmed+1 armed boundary+ZERO armed interior. Interior conservatively means event_idx2..87 so both +/-1 boundary placements stay armed. Free reasons:depth overlap15,535; GC10,581; overlap5,348; DeleteImage3; FindImage2. No armed-interior GC-loss storm is present in this complete event stream.','', 'The81 armed-boundary frees are depth52 at idx0+24 at idx1, overlap4 at idx0, GC1 at idx0. The lone GC free is rawline886697, frame4770/block33/rising idx0, BC5 2048x2048, last_frame4759. None of the recovery GC candidates point to it. Its boundary phase remains uncertain; the analysis does not claim that every possible boundary eviction is excluded.','']
for sh in [-1,0,1]:
 text +=[f'## Event.frame = row.n {sh:+d}','']
 for kind in ['fall','sameU']:
  wins=[w for w in ww if w['kind']==kind and w['shift']==sh];cc=[e for w in wins for e in w['creates']];new=[e for e in cc if e['class']=='first_observed_signature'];gc=[(w,e) for w in wins for e in w['creates'] if e['class']=='prior_free_RunGarbageCollector']
  text +=[f'{kind}: new printed signatures={len(new)}; first-ever addresses={sum(not e["address_seen"] for e in new)}, earlier address with different printed signature={sum(bool(e["address_seen"]) for e in new)}. GC candidates={len(gc)}, before current floor start={sum(e["prior_free_frame"]<1800+(w["block"]-(2 if kind=="fall" else 3))*90 for w,e in gc)}.','', 'Top new-signature shapes (w,h,mips,fmt,bytes): '+str(Counter((e['w'],e['h'],e['mips'],e['fmt'],e['bytes']) for e in new).most_common(8))+'.','']
text+=['## Whole block classification by event.frame (no first3 slicing)','', '|block|arm|events creates|classes|','|---|---|---|---|']
for b in sorted({e['block'] for e in events if isinstance(e.get('block'),int)}):
 cc=[e for e in events if e.get('block')==b and e['event']=='create'];phase=Counter(e['phase'] for e in cc)
 text.append(f'|{b}|{dict(phase)}|{len(cc)}|{dict(Counter(e["class"] for e in cc))}|')
text+=['','## Interpretation and next concrete engineering step','', 'The excess is overwhelmingly first observed compressed texture signatures plus recreation candidates last freed by ordinary unarmed GC BEFORE the current floor began. At the complete-count -1 alignment, first-signature excess287 and old-GC-candidate excess151 dominate net402 extra inserts (other classes offset36). At nominal alignment the same two classes give252+125 of net406. First-signature textures are chiefly BC5_UNORM mip chains (fmt141); BC4_UNORM is fmt139 (Vulkan SDK vulkan_core.h:1989,1987). Recovery has ZERO fmt0 stencil bookkeeping in all three alignments; there are only5 such creates in the entire process.','', 'This supports deferred materialization/rebinding of sampled texture requests skipped during mode2, and contradicts the specific hypothesis that the floor evicted live images in its armed interior. It does not certify legitimacy of every requested new texture: guest generation, full samples/layout and stable host ImageId are absent; old-signature recreation is a candidate rather than proven same object. Fresh-address samples cannot be recreation of an earlier printed address in this process. The shift+1 windows exclude much of the actual burst; they remain reported, never chosen to reduce R6.','', 'For the next implementation, distinguish loss of live pre-floor cache entries from legitimate requests after return. A direct pre-floor ImageId/generation membership witness with free reason/phase and per-create previous-membership output is narrowly sufficient; keep explicit uncertain/new-signature counts. This can support a separately sealed replacement for an overbroad total-insert proxy while still detecting the historical1000-image cache-loss storm. Do not increase50 to52 and do not alter recycle-pool policy to reduce img_new: pool reuse occurs after the insertion counter and changes backing allocation, not insertion count. All old failures remain failures.','']
for sh in [-1,0,1]:
 for kind in ['fall','sameU']:
  cc=[e for w in ww if w['kind']==kind and w['shift']==sh for e in w['creates']]
  first=next((e for e in cc if e['class']=='first_observed_signature'),None);gc=next((e for e in cc if e['class']=='prior_free_RunGarbageCollector'),None)
  text +=[f'Example {kind} shift{sh}: firstsignature rawline{first["logline"] if first else None}; priorGC recreation rawline{gc["logline"] if gc else None}, previous free rawline{gc["prior_free_line"] if gc else None}.']
(O/'FINDINGS.md').write_text('\n'.join(text));print('\n'.join(text[:20]))
