"""Session 121: mutants of vfy121.py (seal 01, the texmemo8 verify run) - each must be killed by test_vfy121.py.  Run
through the frozen mutlib v4.1, FULL (never --changed-from):
    python C:/kyty/KytyPS5/docs/session-116/mutlib_v41/mutlib.py --scorer C:/kyty/s121/vfy121.py
        --test C:/kyty/s121/test_vfy121.py --mutants C:/kyty/s121/mut_vfy121.py --control --no-memo
        --work-dir C:/kyty/s121/mutwork_vfy121 --cache-dir C:/kyty/s121/mutcache_vfy121
        --out C:/kyty/s121/mut_vfy121.draft.txt
Every anchor occurs exactly once in vfy121.py (LF).  Must-haves of ROADMAP s121 items 3-4 and the review RC1/RC8 are
marked [MH]: correctness counters windowed instead of all rows, a mode-2/3 fatal marker demoted to NOT_ADMITTED, the
positive control, the arming, NEAR as FAR and FAR as NEAR, the ratio bands, the video.
Removed as exact equivalents (no input can tell them apart): `frame < START or` in gate_lines_ok (a frame below START
gives a negative block, never in `blocks`); `sorted(MODE_OF_ARM) != [0, 1, 2, 3]` in arm_asserts (a constant; the
MODE_OF_ARM mutants are killed through the fixtures); `n > last: break` -> `continue` in streams_ok (every later window
frame is past the last main line too); `frame <= START` -> `frame < START` in block_of (frame START gives block -1,
never in `blocks`)."""
import subprocess
import sys
from pathlib import Path

STAGE = Path('C:/kyty/s121/work_mut_vfy121')
SRC = Path('C:/kyty/s121/vfy121.py').read_text(encoding='utf-8')
MUTANTS = [
    # ---- constants: run shape, window, thresholds, units
    ('hold_239', 'HOLD_S = 240', 'HOLD_S = 239'),
    ('hold_300', 'HOLD_S = 240', 'HOLD_S = 300'),
    ('period_91', 'PERIOD = 90\n', 'PERIOD = 91\n'),
    ('start_1710', 'START = 1800', 'START = 1710'),
    ('keep_lo9', 'KEEP = (10, 89)', 'KEEP = (9, 89)'),
    ('keep_lo11', 'KEEP = (10, 89)', 'KEEP = (11, 89)'),
    ('keep_hi88', 'KEEP = (10, 89)', 'KEEP = (10, 88)'),
    ('keep_hi90', 'KEEP = (10, 89)', 'KEEP = (10, 90)'),
    ('window_0_88', 'KEEP = (10, 89)', 'KEEP = (0, 89)'),
    ('window_60_88', 'KEEP = (10, 89)', 'KEEP = (60, 89)'),
    ('draws_min_2999', 'DRAWS_MIN = 3000', 'DRAWS_MIN = 2999'),
    ('draws_min_3001', 'DRAWS_MIN = 3000', 'DRAWS_MIN = 3001'),
    ('arms_3', 'ARMS = 4', 'ARMS = 3'),
    ('arm_text_0', "ARM_TEXT = ('texmemo8=2 texfastcheck=1',", "ARM_TEXT = ('texmemo8=2 texfastcheck=0',"),
    ('arm_text_1', "            'texmemo8=1 texfastcheck=1',\n", "            'texmemo8=1 texfastcheck=0',\n"),
    ('arm_text_2', "            'texmemo8=0 texfastcheck=1',\n", "            'texmemo8=1 texfastcheck=1',\n"),
    ('arm_text_3', "            'texmemo8=3 texfastcheck=1')", "            'texmemo8=2 texfastcheck=1')"),
    ('mode_of_arm_swap01', 'MODE_OF_ARM = (2, 1, 0, 3)', 'MODE_OF_ARM = (1, 2, 0, 3)'),
    ('mode_of_arm_swap23', 'MODE_OF_ARM = (2, 1, 0, 3)', 'MODE_OF_ARM = (2, 1, 3, 0)'),
    ('min_blocks_7', 'MIN_BLOCKS = 8', 'MIN_BLOCKS = 7'),
    ('min_blocks_9', 'MIN_BLOCKS = 8', 'MIN_BLOCKS = 9'),
    ('idle_9', 'IDLE_GPU_MAX = 10', 'IDLE_GPU_MAX = 9'),
    ('idle_11', 'IDLE_GPU_MAX = 10', 'IDLE_GPU_MAX = 11'),
    ('skew_near_7', 'SKEW_NEAR = 8', 'SKEW_NEAR = 7'),
    ('skew_near_9', 'SKEW_NEAR = 8', 'SKEW_NEAR = 9'),
    ('skew_near_80', 'SKEW_NEAR = 8', 'SKEW_NEAR = 80'),                                               # [MH RC1]
    ('far_abs_63', 'SKEW_FAR_ABS = 64', 'SKEW_FAR_ABS = 63'),
    ('far_abs_65', 'SKEW_FAR_ABS = 64', 'SKEW_FAR_ABS = 65'),
    ('far_abs_256', 'SKEW_FAR_ABS = 64', 'SKEW_FAR_ABS = 256'),
    ('far_permille_2', 'SKEW_FAR_PERMILLE = 1', 'SKEW_FAR_PERMILLE = 2'),
    ('far_permille_0', 'SKEW_FAR_PERMILLE = 1', 'SKEW_FAR_PERMILLE = 0'),
    ('ratio_lo_79', 'RATIO_BAND = (1 / 80, 1 / 50)', 'RATIO_BAND = (1 / 79, 1 / 50)'),          # [MH RC8]
    ('ratio_lo_81', 'RATIO_BAND = (1 / 80, 1 / 50)', 'RATIO_BAND = (1 / 81, 1 / 50)'),
    ('ratio_hi_51', 'RATIO_BAND = (1 / 80, 1 / 50)', 'RATIO_BAND = (1 / 80, 1 / 51)'),
    ('ratio_hi_49', 'RATIO_BAND = (1 / 80, 1 / 50)', 'RATIO_BAND = (1 / 80, 1 / 49)'),
    ('arm_hits_299', 'ARM_HITS_MIN = 300.0', 'ARM_HITS_MIN = 299.0'),
    ('arm_hits_301', 'ARM_HITS_MIN = 300.0', 'ARM_HITS_MIN = 301.0'),
    ('arm_keys_299', 'ARM_KEYS_MIN = 300.0', 'ARM_KEYS_MIN = 299.0'),
    ('arm_keys_301', 'ARM_KEYS_MIN = 300.0', 'ARM_KEYS_MIN = 301.0'),
    ('gain_band_lo', 'GAIN_BAND = (600.0, 2000.0)', 'GAIN_BAND = (601.0, 2000.0)'),
    ('gain_band_hi', 'GAIN_BAND = (600.0, 2000.0)', 'GAIN_BAND = (600.0, 1999.0)'),
    ('vid_tol_119', 'VID_TOL_ABS = 120', 'VID_TOL_ABS = 119'),
    ('vid_tol_121', 'VID_TOL_ABS = 120', 'VID_TOL_ABS = 121'),
    ('vid_permille_19', 'VID_TOL_PERMILLE = 20', 'VID_TOL_PERMILLE = 19'),
    ('vid_permille_21', 'VID_TOL_PERMILLE = 20', 'VID_TOL_PERMILLE = 21'),
    ('ns_per_us_1', 'NS_PER_US = 1000.0', 'NS_PER_US = 1.0'),
    ('ns_per_us_1e6', 'NS_PER_US = 1000.0', 'NS_PER_US = 1000000.0'),
    ('bda_new_299', 'BDA_NEW_MAX = 300', 'BDA_NEW_MAX = 299'),
    ('bda_new_301', 'BDA_NEW_MAX = 300', 'BDA_NEW_MAX = 301'),
    ('bda_old_599', 'BDA_OLD_MIN = 600', 'BDA_OLD_MIN = 599'),
    ('bda_old_601', 'BDA_OLD_MIN = 600', 'BDA_OLD_MIN = 601'),
    ('schedule_start', "SCHEDULE = '90+1800:' + '|'.join(ARM_TEXT)", "SCHEDULE = '90+1810:' + '|'.join(ARM_TEXT)"),
    ('vk_allowed', "VK_ALLOWED = ('VK_SDK_PATH',)", "VK_ALLOWED = ('VK_SDK_PATH', 'VK_LAYER_PATH')"),
    ('pins_mutsite', "'m4baton': '0', 'mutsite': '0',", "'m4baton': '0',"),
    ('pins_shadow', "             'shadowresolve': '0'}", "             'shadowresolve': '1'}"),
    ('absent_r1cen', "BASE_ABSENT = ('texmemo8', 'r1cen', ", "BASE_ABSENT = ('texmemo8', "),
    ('absent_pathlap', "'slicecen', 'spine', 'bindlap', 'pathlap')", "'slicecen', 'spine', 'bindlap')"),
    ('markers_error', "b'unhandled exception', b'--- error ---')", "b'unhandled exception')"),
    ('markers_fatal', "b'abort()', b'fatal', ", "b'abort()', "),
    ('markers_waitslow', "(b'gpuhangabort', b'gpuwaitslow', ", "(b'gpuhangabort', "),
    ('markers_terminate', "b'std::terminate', b'abort()', ", "b'abort()', "),
    ('skipped_text', "SKIPPED_DRAW = b'AsyncPipelines: skipped draw'", "SKIPPED_DRAW = b'AsyncPipelines: skipped draws'"),
    ('line_verify_text', "('verify_mismatch', b'Tm8VerifyMismatch:')", "('verify_mismatch', b'Tm8VerifyMismatch: kind=ctl')"),
    ('line_rebind_text', "('rebind_mismatch', b'Tm8RebindMismatch:')", "('rebind_mismatch', b'Tm8RebindMismatch: x')"),
    ('line_texfast_text', "b'TexFastVerify: MISMATCH'", "b'TexFastVerify: MISMATCH!'"),
    ('line_injected_text', "('verify_injected', b'Tm8VerifyInjected:')", "('verify_injected', b'Tm8VerifyInjected: x')"),
    ('line_rbinjected_text', "('rebind_injected', b'Tm8RebindInjected:')", "('rebind_injected', b'Tm8RebindInjected: x')"),
    ('per_lookup_from10', 'PER_LOOKUP = TM8[9:]', 'PER_LOOKUP = TM8[10:]'),
    ('per_lookup_from8', 'PER_LOOKUP = TM8[9:]', 'PER_LOOKUP = TM8[8:]'),
    ('hard_no_texfast', "'tm8_rbbad', 'texfast_bad')\n", "'tm8_rbbad')\n"),                         # [MH item 4]
    ('hard_no_relive', "HARD_ZERO = ('tm8_bad', 'tm8_vctl_bad', 'tm8_relive', ", "HARD_ZERO = ('tm8_bad', 'tm8_vctl_bad', "),
    ('hard_no_vctl_bad', "HARD_ZERO = ('tm8_bad', 'tm8_vctl_bad', ", "HARD_ZERO = ('tm8_bad', "),
    ('hard_no_bad', "HARD_ZERO = ('tm8_bad', ", "HARD_ZERO = ("),
    ('hard_no_rbbad', "'tm8_relive', 'tm8_rbbad', 'texfast_bad')", "'tm8_relive', 'texfast_bad')"),
    ('struct_no_dcc', "STRUCT_ZERO = ('tm8_inject_miss', 'tm8_rbinject_miss', 'tm8_dcc_chg')",
     "STRUCT_ZERO = ('tm8_inject_miss', 'tm8_rbinject_miss')"),
    ('struct_no_inject_miss', "STRUCT_ZERO = ('tm8_inject_miss', ", "STRUCT_ZERO = ("),
    ('config_no_cenoff', "CONFIG_ZERO = ('tm8_x2', 'tm8_cenoff')", "CONFIG_ZERO = ('tm8_x2',)"),
    ('config_no_x2', "CONFIG_ZERO = ('tm8_x2', 'tm8_cenoff')", "CONFIG_ZERO = ('tm8_cenoff',)"),
    ('field_no_negative', "FIELD = re.compile(rb' (\\w+)=(-?\\d+)')", "FIELD = re.compile(rb' (\\w+)=(\\d+)')"),
    # ---- identities (RC1) and ratios (RC8)
    ('id_look_no_stale', "(('tm8_hit', 1), ('tm8_miss', 1), ('tm8_stale', 1)), 'near'),",
     "(('tm8_hit', 1), ('tm8_miss', 1)), 'near'),"),
    ('id_look_far', "(('tm8_hit', 1), ('tm8_miss', 1), ('tm8_stale', 1)), 'near'),",
     "(('tm8_hit', 1), ('tm8_miss', 1), ('tm8_stale', 1)), 'far'),"),                              # [MH RC1]
    ('id_vchk_far', "('vchk=gain', ('tm8_vchk',), (('tm8_gain', 1),), 'near'),",
     "('vchk=gain', ('tm8_vchk',), (('tm8_gain', 1),), 'far'),"),
    ('id11_near', "     (('tm8_hit', 1), ('tm8_bad', -1), ('tm8_vctl_bad', -1), ('tm8_relive', -1)), 'far'),",
     "     (('tm8_hit', 1), ('tm8_bad', -1), ('tm8_vctl_bad', -1), ('tm8_relive', -1)), 'near'),"),     # [MH RC1]
    ('id11_bad_sign', "(('tm8_hit', 1), ('tm8_bad', -1), ", "(('tm8_hit', 1), ('tm8_bad', 1), "),
    ('id11_vctl_sign', "('tm8_vctl_bad', -1), ('tm8_relive', -1)), 'far'),", "('tm8_vctl_bad', 1), ('tm8_relive', -1)), 'far'),"),
    ('id11_relive_sign', "('tm8_vctl_bad', -1), ('tm8_relive', -1)), 'far'),", "('tm8_vctl_bad', -1), ('tm8_relive', 1)), 'far'),"),
    ('id13_no_empty', "(('texmemo_collide', 1), ('texmemo_empty', 1)), 'far'),", "(('texmemo_collide', 1),), 'far'),"),
    ('id13_near', "(('texmemo_collide', 1), ('texmemo_empty', 1)), 'far'),",
     "(('texmemo_collide', 1), ('texmemo_empty', 1)), 'near'),"),
    ('id1_no_stale', "('texmemo_stale', 1), ('tm8_bad', 1), ", "('tm8_bad', 1), "),
    ('id1_no_empty', "     (('texmemo_collide', 1), ('texmemo_empty', 1), ('texmemo_stale', 1), ",
     "     (('texmemo_collide', 1), ('texmemo_stale', 1), "),
    ('id1_no_bad', "('texmemo_stale', 1), ('tm8_bad', 1), ('tm8_vctl_bad', 1),", "('texmemo_stale', 1), ('tm8_vctl_bad', 1),"),
    ('id1_no_vctl_bad', "('tm8_bad', 1), ('tm8_vctl_bad', 1),\n", "('tm8_bad', 1),\n"),
    ('id1_no_relive', "('tm8_vctl_bad', 1),\n      ('tm8_relive', 1)), 'far_le'),", "('tm8_vctl_bad', 1)), 'far_le'),"),
    ('id1_two_sided', "      ('tm8_relive', 1)), 'far_le'),", "      ('tm8_relive', 1)), 'far'),"),
    ('ratio_vctl_no_gain', "(('tm8_hit', 1), ('tm8_gain', -1))),", "(('tm8_hit', 1),)),"),
    ('ratio_pb_hit', "          ('pb_n/look', 'tm8_pb_n', (('tm8_look', 1),)))", "          ('pb_n/look', 'tm8_pb_n', (('tm8_hit', 1),)))"),
    # ---- helpers
    ('env_rec_fixed', "rec_%s.mp4' % tag,\n", "rec_vfy121.mp4',\n"),
    ('env_markers_2', "            'KYTY_GPU_MARKERS': '0'}", "            'KYTY_GPU_MARKERS': '2'}"),
    ('env_trace_full', "    return {'KYTY_FRAME_TRACE': 'lite',", "    return {'KYTY_FRAME_TRACE': '1',"),
    ('marker_case', '    low = line.lower()\n', '    low = line\n'),
    ('idle_bool', 'isinstance(v, (int, float)) and not isinstance(v, bool) and ', 'isinstance(v, (int, float)) and '),
    ('idle_lt', 'v <= IDLE_GPU_MAX', 'v < IDLE_GPU_MAX'),
    ('regime_new_lt', '    if v <= BDA_NEW_MAX:', '    if v < BDA_NEW_MAX:'),
    ('regime_old_gt', '    if v >= BDA_OLD_MIN:', '    if v > BDA_OLD_MIN:'),
    ('first_values_last_wins', '            out.setdefault(k, v)', '            out[k] = v'),
    ('aa_no_len', '    if len(texts) != ARMS or len(MODE_OF_ARM) != ARMS or ', '    if len(MODE_OF_ARM) != ARMS or '),
    ('aa_no_mode', "        if v.get('texmemo8') != str(MODE_OF_ARM[i]) or ", "        if v.get('texmemo8') is None or "),
    ('aa_no_fastcheck', " or v.get('texfastcheck') != '1':", ':'),
    ('bn_no_pins', '    if any(g.get(k) != v for k, v in BASE_PINS.items()) or any(k in g for k in BASE_ABSENT):',
     '    if any(k in g for k in BASE_ABSENT):'),
    ('bn_no_absent', '    if any(g.get(k) != v for k, v in BASE_PINS.items()) or any(k in g for k in BASE_ABSENT):',
     '    if any(g.get(k) != v for k, v in BASE_PINS.items()):'),
    ('bn_texts_texmemo8', "for k in BASE_ABSENT if k != 'texmemo8')", "for k in BASE_ABSENT)"),
    ('bn_texts_ignored', 'for t in texts for k in BASE_ABSENT', 'for t in texts[:0] for k in BASE_ABSENT'),
    ('arms_garbled_skip', "        if g is None:\n            return False, {}\n        arm, arms",
     "        if g is None:\n            continue\n        arm, arms"),
    ('arms_count', '        if arms != ARMS or period != PERIOD', '        if period != PERIOD'),
    ('arms_period', 'or period != PERIOD or abba != 0', 'or abba != 0'),
    ('arms_abba', 'abba != 0 or arm >= ARMS', 'arm >= ARMS'),
    ('arms_range', 'or arm >= ARMS or text != ARM_TEXT[arm]:', 'or text != ARM_TEXT[arm]:'),
    ('arms_text', 'or text != ARM_TEXT[arm]:', 'or False:'),
    ('arms_frame', '        if frame != START + PERIOD * block or ', '        if '),
    ('arms_order', ' or block % ARMS != arm or ', ' or '),
    ('arms_dup', ' or block in blocks:\n', ':\n'),
    ('arms_consecutive', 'ok = bool(blocks) and sorted(blocks) == list(range(len(blocks)))', 'ok = bool(blocks)'),
    ('gl_garbled', '        if m is None:\n            return False\n        name', '        if m is None:\n            continue\n        name'),
    ('gl_name', "        if name not in ARM_VALUES[0] or frame < START", "        if frame < START"),
    ('gl_modulo', ' or (frame - START) % PERIOD != 0:', ':'),
    ('gl_value', "m.group(2).decode() != ARM_VALUES[blocks[block]][name]:", "False:"),
    ('gl_block', '        if block not in blocks or ', '        if '),
    ('rr_missing', 'x_missing += int(any(k.encode() not in got for k in ALL_ROW))', 'x_missing += 0'),
    ('rr_all_rows_last', 'all_rows[k] += int(got.get(k.encode(), 0))', 'all_rows[k] = int(got.get(k.encode(), 0))'),
    ('rr_all_rows_window', "                        for k in ALL_ROW:\n                            all_rows[k] +=",
     "                        for k in ALL_ROW[:0] if n <= START else ALL_ROW:\n                            all_rows[k] +="),  # [MH]
    ('rr_dups', '                    if n in seen[kind]:\n                        dups.add(n)',
     '                    if False:\n                        dups.add(n)'),
    ('rr_partial_rows', 'seen[kind][n] = rec if len(rec) == len(names) else None', 'seen[kind][n] = rec'),
    ('rr_last_main_x', "                    if kind == 'main':\n                        last_main = n",
     "                    if kind == 'x':\n                        last_main = n"),
    ('rr_skip_frame', 'skipped.append(None if last_main is None else last_main + 1)',
     'skipped.append(None if last_main is None else last_main)'),
    ('rr_log_marker_none', "markers.append((None if quit_seen else arm_now, 'log', ", "markers.append((None, 'log', "),  # [MH item 3(б)]
    ('rr_quit_ignored', "markers.append((None if quit_seen else arm_now, 'log', ", "markers.append((arm_now, 'log', "),
    ('rr_quit_never', '                quit_seen = True', '                quit_seen = False'),
    ('rr_quit_midline', '            if line.startswith(QUIT):', '            if QUIT in line:'),
    ('rr_quit_text', "QUIT = b'Event: quit'", "QUIT = b'Event: quit!'"),
    ('rr_twin_skip_removed', '                if any(t.startswith(text) for t in log_texts):\n                    continue',
     '                if False:\n                    continue'),                                        # [review finding 1]
    ('rr_twin_reversed', 'any(t.startswith(text) for t in log_texts)', 'any(text.startswith(t) for t in log_texts)'),
    ('rr_twin_equal', 'any(t.startswith(text) for t in log_texts)', 'any(t == text for t in log_texts)'),
    ('rr_twin_any_stdout', 'any(t.startswith(text) for t in log_texts)', 'any(True for t in log_texts)'),
    ('rr_log_slow_false', '                                is_slow(line)))', '                                False))'),
    ('rr_stdout_slow_false', "markers.append((arm_now, 'stdout', text, is_slow(line)))",
     "markers.append((arm_now, 'stdout', text, False))"),
    ('slow_markers_empty', "SLOW_MARKERS = (b'gpuwaitslow',)", 'SLOW_MARKERS = ()'),
    ('slow_markers_case', '    return any(k in line.lower() for k in SLOW_MARKERS)', '    return any(k in line for k in SLOW_MARKERS)'),
    ('slow_markers_error', "SLOW_MARKERS = (b'gpuwaitslow',)", "SLOW_MARKERS = (b'gpuwaitslow', b'--- error ---')"),
    ('rr_stdout_marker_none', "markers.append((arm_now, 'stdout', ", "markers.append((None, 'stdout', "),
    ('rr_garbled_keeps_arm', 'arm_now = None if mg is None else int(mg.group(1))',
     'arm_now = arm_now if mg is None else int(mg.group(1))'),
    ('rr_no_stdout', '    if stdout_path is not None and Path(stdout_path).is_file():', '    if False:'),
    ('mode_of_arm_range', '0 <= arm < ARMS else None', '0 <= arm <= ARMS else None'),
    ('select_no_labels', " and seen['main'][n]['arm'] == arm and seen['main'][n]['blk'] == b)", ')'),
    ('select_no_dups', '        return (n not in dups and all(', '        return (all('),
    ('select_window_only', '        if all(complete(n, arm, b) for n in frames):',
     '        if all(complete(n, arm, b) for n in frames[KEEP[0]:KEEP[1]]):'),
    ('select_win_all', "for n in frames[KEEP[0]:KEEP[1]]]", "for n in frames]"),
    ('select_draws_ge', "r['draws'] > DRAWS_MIN", "r['draws'] >= DRAWS_MIN"),
    ('ident_est', "s = ksum(blk['win'], keys)", "s = ksum(blk['est'], keys)"),                          # [review finding 3]
    ('ratio_est', "s = ksum(blk['win'], TM8)", "s = ksum(blk['est'], TM8)"),
    ('wsum_est', "for r in mode_rows(done, m, 'win')", "for r in mode_rows(done, m, 'est')"),
    ('m1fill_est', "sum(r['tm8_fill'] for r in blk['win'])", "sum(r['tm8_fill'] for r in blk['est'])"),
    ('rr_dups_x_only', '                    if n in seen[kind]:', "                    if kind == 'x' and n in seen[kind]:"),
    ('rr_dups_not_main', '                    if n in seen[kind]:', "                    if kind != 'main' and n in seen[kind]:"),
    ('rr_line_key_start', '                if text in line:', '                if line.startswith(text):'),
    ('rb_strict', "out[b] = 0 < s['tm8_rbchk'] <= s['texfast_ok'] + s['texfast_no']",
     "out[b] = 0 < s['tm8_rbchk'] < s['texfast_ok'] + s['texfast_no']"),
    ('rb_no_zero', "out[b] = 0 < s['tm8_rbchk'] <= s['texfast_ok'] + s['texfast_no']",
     "out[b] = s['tm8_rbchk'] <= s['texfast_ok'] + s['texfast_no']"),
    ('rb_no_no', "out[b] = 0 < s['tm8_rbchk'] <= s['texfast_ok'] + s['texfast_no']",
     "out[b] = 0 < s['tm8_rbchk'] <= s['texfast_ok']"),
    ('streams_none_true', '    if last is None:\n        return not blocks', '    if last is None:\n        return True'),
    ('streams_exempt_any', "            if n == last and (seen['draw'].get(n) is None or seen['x'].get(n) is None):",
     '            if n == last:'),
    ('streams_all_frames', '        for n in block_frames(b)[KEEP[0]:KEEP[1]]:', '        for n in block_frames(b):'),
    ('streams_no_labels', "            if main['arm'] != arm or main['blk'] != b:", '            if False:'),
    ('far_lhs_only', 'max(abs(lhs), abs(rhs))', 'abs(lhs)'),
    ('far_signed', '    return 1000 * abs(res) <= max(', '    return 1000 * res <= max('),
    ('far_strict', '    return 1000 * abs(res) <= max(', '    return 1000 * abs(res) < max('),
    ('id_mode2_only', "        if blk['mode'] not in (2, 3):\n            continue\n        s = ksum(blk['win'], keys)",
     "        if blk['mode'] not in (2,):\n            continue\n        s = ksum(blk['win'], keys)"),
    ('id_near_as_far', '                fine = abs(res) <= SKEW_NEAR', '                fine = within_far(res, lhs, rhs)'),  # [MH RC1]
    ('id_far_as_near', "            elif cls == 'far':\n                fine = within_far(res, lhs, rhs)",
     "            elif cls == 'far':\n                fine = abs(res) <= SKEW_NEAR"),                                  # [MH RC1]
    ('id_bound_two_sided', '                fine = res <= 0 or within_far(res, lhs, rhs)', '                fine = within_far(res, lhs, rhs)'),
    ('id_bound_true', '                fine = res <= 0 or within_far(res, lhs, rhs)', '                fine = True'),
    ('id_all_blocks', "        if blk['mode'] not in (2, 3):\n            continue\n        s = ksum(blk['win'], keys)",
     "        if False:\n            continue\n        s = ksum(blk['win'], keys)"),
    ('ratio_mode2_only', "        if blk['mode'] not in (2, 3):\n            continue\n        s = ksum(blk['win'], TM8)",
     "        if blk['mode'] not in (2,):\n            continue\n        s = ksum(blk['win'], TM8)"),
    ('ratio_lo_le', 'v < RATIO_BAND[0] or', 'v <= RATIO_BAND[0] or'),
    ('ratio_hi_ge', 'v > RATIO_BAND[1]:', 'v >= RATIO_BAND[1]:'),
    ('ratio_none_ok', '            if v is None or v < RATIO_BAND[0]', '            if v is not None and v < RATIO_BAND[0]'),
    ('report_key_collide', "sum(r['texmemo_collide'] + r['texmemo_empty'] for r in est)", "sum(r['texmemo_collide'] for r in est)"),
    ('report_probe_no_clamp', 't_pb = None if pn == 0 else max(0.0, (', 't_pb = None if pn == 0 else ((('),
    ('report_probe_pb0_sign', "- sum(r['tm8_pb0_ns'] for r in est)) / pn)", "+ sum(r['tm8_pb0_ns'] for r in est)) / pn)"),
    ('report_probe_units', "else t_pb * out['tm8_look'] / NS_PER_US)", "else t_pb * out['tm8_look'])"),
    ('report_blocks_est', "out['blocks'] = sum(1 for blk in done.values() if blk['mode'] == mode and blk['est'])",
     "out['blocks'] = sum(1 for blk in done.values() if blk['mode'] == mode)"),
    ('glitch_args', "'4', '12', str(out_dir)", "'5', '12', str(out_dir)"),
    ('glitch_path', "    path = Path(root) / ('%s_glitch.txt' % tag)", "    path = Path(root) / ('%s.glitch.txt' % tag)"),
    ('video_run_always', "    if report_path is None and out['exists']:", '    if report_path is None:'),
    ('video_events_ignored', 'parsed=len(events) == int(mc.group(1)),', 'parsed=True,'),
    ('video_names_any', "split('/')[-1] == 'rec_%s.mp4' % tag)", "split('/')[-1] != '')"),
    ('video_names_endswith', "names=mh.group(1).replace('\\\\', '/').split('/')[-1] == 'rec_%s.mp4' % tag)",
     "names=mh.group(1).endswith('rec_%s.mp4' % tag))"),
    ('video_names_backslash',"names=mh.group(1).replace('\\\\', '/').split('/')[-1]", "names=mh.group(1).split('/')[-1]"),
    ('video_index_any', "out['index_ok'] = out['frames'] == out['index']", "out['index_ok'] = True"),
    ('video_tol_abs_only', "max(VID_TOL_ABS, VID_TOL_PERMILLE * last_main / 1000)", 'VID_TOL_ABS'),
    ('video_tol_signed', "abs(out['frames'] - last_main) <= out['tol']", "(out['frames'] - last_main) <= out['tol']"),
    ('video_tol_strict', "abs(out['frames'] - last_main) <= out['tol']", "abs(out['frames'] - last_main) < out['tol']"),
    # ---- evaluate: admission
    ('ev_min_blocks', 'min_blocks = MIN_BLOCKS if min_blocks is None else min_blocks',
     'min_blocks = 1 if min_blocks is None else min_blocks'),
    ('ev_pred_default', '(PRED_SHA, PRED_BYTES) if pred_want is _UNSET else pred_want', '(PRED_SHA, PRED_BYTES)'),
    ('ev_hold_exit', "if a.get('outcome') == 'ok' and a.get('hold_exit') is None]", "if a.get('outcome') == 'ok']"),
    ('ev_attempts_one', 'one_ok_attempt=len(atts) == 1 and len(ok_att) == 1', 'one_ok_attempt=len(ok_att) == 1'),
    ('ev_prereg_none_ok', '        prereg_ok = (want_sha is not None and want_bytes is not None\n                     and ',
     '        prereg_ok = ('),
    ('ev_prereg_path', "                     and str(prereg.get('path') or '').replace('\\\\', '/') == pred_path\n", ''),
    ('ev_prereg_meta_sha', "                     and prereg.get('sha256') == want_sha and prereg.get('bytes') == want_bytes\n",
     "                     and prereg.get('bytes') == want_bytes\n"),
    ('ev_prereg_meta_bytes', "                     and prereg.get('sha256') == want_sha and prereg.get('bytes') == want_bytes\n",
     "                     and prereg.get('sha256') == want_sha\n"),
    ('ev_prereg_now_sha', '                     and now[0] == want_sha and now[1] == want_bytes)',
     '                     and now[1] == want_bytes)'),
    ('ev_prereg_now_bytes', '                     and now[0] == want_sha and now[1] == want_bytes)',
     '                     and now[0] == want_sha)'),
    ('ev_draft_checks_prereg', '    if draft:\n        prereg_ok = None', '    if False:\n        prereg_ok = None'),
    ('ev_verify_markers_mode2', 'verify_markers = [m for m in markers if m[3] in (2, 3) and',
     'verify_markers = [m for m in markers if m[3] in (2,) and'),
    ('ev_marker_demoted', 'verify_markers = [m for m in markers if m[3] in (2, 3) and not m[4]]',
     'verify_markers = []'),                                                                           # [MH item 3(б)]
    ('ev_other_markers_no_mode1', 'other_markers = [m for m in markers if not (m[3] in (2, 3) and not m[4])]',
     'other_markers = [m for m in markers if not (m[3] in (1, 2, 3) and not m[4])]'),
    ('ev_verify_slow_fatal', 'verify_markers = [m for m in markers if m[3] in (2, 3) and not m[4]]',
     'verify_markers = [m for m in markers if m[3] in (2, 3)]'),                                    # [MH item 3(б)]
    ('ev_other_slow_ignored', 'other_markers = [m for m in markers if not (m[3] in (2, 3) and not m[4])]',
     'other_markers = [m for m in markers if m[3] not in (2, 3)]'),
    ('ev_skip_edge', 'and KEEP[0] <= (f - START - 1) % PERIOD < KEEP[1]]', 'and KEEP[0] <= (f - START - 1) % PERIOD <= KEEP[1]]'),
    ('ev_skip_no_block', "if f is not None and block_of(f) in blocks\n", "if f is not None and block_of(f) is not None\n"),
    ('ev_modes_no_est', "sum(1 for blk in done.values() if blk['mode'] == m and blk['est']) for m in range(4)}",
     "sum(1 for blk in done.values() if blk['mode'] == m) for m in range(4)}"),
    ('ck_binary', "        binary=meta.get('binary_sha256') == BUILD_SHA,", '        binary=True,'),
    ('ck_installed', '        installed_now=installed_sha == BUILD_SHA,', '        installed_now=True,'),
    ('ck_pinned_any', "parsed['pins'] == [1],", "1 in parsed['pins'],"),
    ('ck_pinned_env', "        pinned=env.get('KYTY_GPU_CLOCK_PIN') == '1' and ", '        pinned='),
    ('ck_env', '        env_exact=kyty_env == env_expect(tag) and ', '        env_exact='),
    ('ck_env_schedule', "and meta.get('schedule') == SCHEDULE,", 'and True,'),
    ('ck_env_vk', '        env_vk=all(k in VK_ALLOWED for k in vk_env),', '        env_vk=True,'),
    ('ck_hold', '        hold=meta.get(\'hold_s\') == HOLD_S,', '        hold=True,'),
    ('ck_gates_sha', 'gf.is_file() and sha_file(gf) == GATES_SHA and gates_text == base_text', 'gf.is_file() and gates_text == base_text'),
    ('ck_gates_text', 'gf.is_file() and sha_file(gf) == GATES_SHA and gates_text == base_text', 'gf.is_file() and sha_file(gf) == GATES_SHA'),
    ('ck_base_names', '        base_names=base_names_ok(gates_text, ARM_TEXT),', '        base_names=True,'),
    ('ck_gate_lines', "        gate_lines=gate_lines_ok(parsed['gate_lines'], blocks),", '        gate_lines=True,'),
    ('ck_arms', '        arms=arms_fine,', '        arms=True,'),
    ('ck_modes_gt', 'modes=all(per_mode_blocks[m] >= min_blocks for m in range(4)),', 'modes=all(per_mode_blocks[m] > min_blocks for m in range(4)),'),
    ('ck_modes_3', 'modes=all(per_mode_blocks[m] >= min_blocks for m in range(4)),', 'modes=all(per_mode_blocks[m] >= min_blocks for m in range(3)),'),
    ('ck_no_marker', '        no_marker=not other_markers,', '        no_marker=True,'),
    ('ck_no_skip', '        no_skip_window=not skipped_in,', '        no_skip_window=True,'),
    ('ck_streams', '        streams=streams_ok(parsed, blocks),', '        streams=True,'),
    ('ck_fields_zero_rows', "fields_all_rows=parsed['x_lines'] > 0 and parsed['x_missing'] == 0,", "fields_all_rows=parsed['x_missing'] == 0,"),
    ('ck_fields', "fields_all_rows=parsed['x_lines'] > 0 and parsed['x_missing'] == 0,", "fields_all_rows=parsed['x_lines'] > 0,"),
    ('ck_idle', '        idle=idle_ok(meta),', '        idle=True,'),
    ('ck_video_exists', "        video=(video['exists'] and video['parsed']", "        video=(video['parsed']"),
    ('ck_video_parsed', "video['exists'] and video['parsed'] and video['names']", "video['exists'] and video['names']"),
    ('ck_video_names', "video['parsed'] and video['names'] and video['index_ok']", "video['parsed'] and video['index_ok']"),
    ('ck_video_index', "video['names'] and video['index_ok'] and video['count_ok']", "video['names'] and video['count_ok']"),
    ('ck_video_count', "video['index_ok'] and video['count_ok']))", "video['index_ok']))"),
    ('ck_admitted_draft', 'admitted = all(v is not False for v in checks.values())', 'admitted = all(checks.values())'),
    # ---- evaluate: hard FAIL, soft FAIL, verdict order
    ('hd_zero', '        hard_zero=all(ar[k] == 0 for k in HARD_ZERO),', '        hard_zero=True,'),              # [MH item 4]
    ('hd_zero_window', '        hard_zero=all(ar[k] == 0 for k in HARD_ZERO),',
     "        hard_zero=all(r[k] == 0 for blk in done.values() for r in blk['win'] for k in HARD_ZERO),"),  # [MH]
    ('hd_struct', '        struct_zero=all(ar[k] == 0 for k in STRUCT_ZERO),', '        struct_zero=True,'),
    ('hd_mismatch_verify', "        no_mismatch=(parsed['lines']['verify_mismatch'] == 0 and ", '        no_mismatch=('),
    ('hd_mismatch_rebind', "parsed['lines']['rebind_mismatch'] == 0\n", 'True\n'),
    ('hd_mismatch_texfast', "                     and parsed['lines']['texfast_mismatch'] == 0),", '                     ),'),
    ('hd_marker', '        verify_marker=not verify_markers,', '        verify_marker=True,'),                    # [MH item 3(б)]
    ('hd_glitch', "        no_glitch=not (video['parsed'] and video['names'] and video['glitches'] > 0))", '        no_glitch=True)'),
    ('hd_glitch_any_file', "        no_glitch=not (video['parsed'] and video['names'] and video['glitches'] > 0))",
     "        no_glitch=not (video['parsed'] and video['glitches'] > 0))"),
    ('hd_glitch_ge', "video['glitches'] > 0))", "video['glitches'] >= 0))"),
    ('dh_sign', "              else reports[1]['tex_hits'] - reports[0]['tex_hits'])", "              else reports[0]['tex_hits'] - reports[1]['tex_hits'])"),
    ('dk_sign', "              else reports[1]['key_miss'] - reports[0]['key_miss'])", "              else reports[0]['key_miss'] - reports[1]['key_miss'])"),
    ('sf_config', '        config_zero=all(ar[k] == 0 for k in CONFIG_ZERO),', '        config_zero=True,'),
    ('sf_ctl_inject', "        control_alive=(wsum((3,), ('tm8_inject',)) > 0 and ", '        control_alive=('),       # [MH]
    ('sf_ctl_rbinject', "wsum((3,), ('tm8_rbinject',)) > 0\n", 'True\n'),
    ('sf_ctl_vline', "                       and parsed['lines']['verify_injected'] > 0 and ", '                       and '),
    ('sf_ctl_rline', " and parsed['lines']['rebind_injected'] > 0),", '),'),
    ('sf_ctl_mode2', "        control_alive=(wsum((3,), ('tm8_inject',))", "        control_alive=(wsum((2, 3), ('tm8_inject',))"),
    ('sf_leak_mode2', "control_leak=wsum((0, 1, 2), ('tm8_inject', 'tm8_rbinject')) == 0,", "control_leak=wsum((0, 1), ('tm8_inject', 'tm8_rbinject')) == 0,"),
    ('sf_leak_rbinject', "control_leak=wsum((0, 1, 2), ('tm8_inject', 'tm8_rbinject')) == 0,", "control_leak=wsum((0, 1, 2), ('tm8_inject',)) == 0,"),
    ('sf_alive_mode3', "> 0 for m in (2, 3)),", '> 0 for m in (2,)),'),
    ('sf_alive_vchk', "        verify_alive=all(wsum((m,), ('tm8_vchk',)) > 0 and ", '        verify_alive=all('),
    ('sf_alive_gain', " and wsum((m,), ('tm8_gain',)) > 0 for m in (2, 3)),", ' for m in (2, 3)),'),
    ('sf_dark_mode0', "        dark_01=all(wsum((0, 1), (k,)) == 0 for k in PER_LOOKUP),", "        dark_01=all(wsum((1,), (k,)) == 0 for k in PER_LOOKUP),"),
    ('sf_dark_mode1', "        dark_01=all(wsum((0, 1), (k,)) == 0 for k in PER_LOOKUP),", "        dark_01=all(wsum((0,), (k,)) == 0 for k in PER_LOOKUP),"),
    ('sf_dark_first', "        dark_01=all(wsum((0, 1), (k,)) == 0 for k in PER_LOOKUP),", "        dark_01=all(wsum((0, 1), (k,)) == 0 for k in PER_LOOKUP[:1]),"),
    ('sf_m1_none', "        m1_fill=bool(m1_blocks) and all(", '        m1_fill=all('),
    ('sf_m1_any', "and all(sum(r['tm8_fill'] for r in blk['win']) > 0 for blk in m1_blocks),", "and any(sum(r['tm8_fill'] for r in blk['win']) > 0 for blk in m1_blocks),"),
    ('sf_m0', "        m0_fill=wsum((0,), ('tm8_fill',)) == 0,", '        m0_fill=True,'),
    ('sf_hits_gt', 'armed_hits=d_hits is not None and d_hits >= ARM_HITS_MIN,', 'armed_hits=d_hits is not None and d_hits > ARM_HITS_MIN,'),
    ('sf_keys_lt', 'armed_keys=d_keys is not None and d_keys <= -ARM_KEYS_MIN,', 'armed_keys=d_keys is not None and d_keys < -ARM_KEYS_MIN,'),
    ('sf_keys_sign', 'armed_keys=d_keys is not None and d_keys <= -ARM_KEYS_MIN,', 'armed_keys=d_keys is not None and d_keys <= ARM_KEYS_MIN,'),
    ('sf_hits_true', 'armed_hits=d_hits is not None and d_hits >= ARM_HITS_MIN,', 'armed_hits=True,'),         # [MH]
    ('sf_keys_true', 'armed_keys=d_keys is not None and d_keys <= -ARM_KEYS_MIN,', 'armed_keys=True,'),
    ('sf_identities', '        identities=not id_bad,', '        identities=True,'),
    ('sf_ratios', '        ratios=not ratio_bad)', '        ratios=True)'),                                          # [MH RC8]
    ('vd_na_first', "    if hard_bad:\n        verdict = 'FAIL'\n    elif not admitted:\n        verdict = 'NOT_ADMITTED'",
     "    if not admitted:\n        verdict = 'NOT_ADMITTED'\n    elif hard_bad:\n        verdict = 'FAIL'"),
    ('vd_soft_ignored', "    elif soft_bad:\n        verdict = 'FAIL'", "    elif False:\n        verdict = 'FAIL'"),
    ('vd_soft_na', "    elif soft_bad:\n        verdict = 'FAIL'", "    elif soft_bad:\n        verdict = 'NOT_ADMITTED'"),
    ('vd_gain_band_lt', 'GAIN_BAND[0] <= g <= GAIN_BAND[1]', 'GAIN_BAND[0] < g < GAIN_BAND[1]'),
    # ---- report and main
    ('rep_na_banner', "    if not res['admitted']:\n        out.append('REPORT OF A NOT_ADMITTED", "    if res['draft']:\n        out.append('REPORT OF A NOT_ADMITTED"),
    ('rep_why_hard', "        why.append('hard: ' + ','.join(res['hard_bad']))", '        pass'),
    ('rep_why_admission', "        why.append('admission: ' + ','.join(res['failed']))", '        pass'),
    ('rep_why_evidence', "        why.append('evidence: ' + ','.join(res['soft_bad']))", '        pass'),
    ('rep_draft_suffix', "' DRAFT' if res['draft'] else ''", "''"),
    ('rep_consequence', "    out.append('CONSEQUENCE: %s' % CONSEQUENCE[res['verdict']])", "    out.append('CONSEQUENCE: %s' % CONSEQUENCE['FAIL'])"),
    ('rep_note', "    out.append('  ' + NOTE)", '    pass'),
    ('rep_probe_ns', "(fmt(r['t_pb_ns'], 2),", "(fmt(r['t_pb_ns'] and r['t_pb_ns'] * 1000, 2),"),
    ('rep_glitch_lines', "        out.append('    glitch video %d present %d' % (vid, present))", '        pass'),
    ('main_tag_check', '    if tag not in TAGS and not draft:', '    if False:'),
    ('main_rc', '        return 2\n', '        return 3\n'),
]
if __name__ == '__main__':
    STAGE.mkdir(parents=True, exist_ok=True)
    killed = 0
    for name, old, new in MUTANTS:
        if SRC.count(old) != 1:
            print('%-26s ANCHOR x%d' % (name, SRC.count(old)))
            continue
        path = STAGE / ('mut_vfy121_%s.py' % name)
        path.write_bytes(SRC.replace(old, new).encode('utf-8'))
        r = subprocess.run([sys.executable, 'C:/kyty/s121/test_vfy121.py', str(path)], capture_output=True, text=True)
        killed += r.returncode != 0
        print('%-26s %s' % (name, 'killed' if r.returncode != 0 else 'SURVIVED'))
        path.unlink()
    print('killed %d of %d' % (killed, len(MUTANTS)))
