"""Session 121: mutants of shp121.py - each must be killed by test_shp121.py.  Run through the frozen mutlib v4.1 FULL,
exactly this command (default --workers = cpu_count - 4, no --timeout; the first draft run of this round's predecessor
added `--workers 12 --timeout 900`, which changes scheduling only):
    python C:/kyty/KytyPS5/docs/session-116/mutlib_v41/mutlib.py --scorer C:/kyty/s121/shp121.py
        --test C:/kyty/s121/test_shp121.py --mutants C:/kyty/s121/mut_shp121.py --control --no-memo
        --work-dir C:/kyty/s121/mutwork_shp121 --cache-dir C:/kyty/s121/mutcache_shp121 --out C:/kyty/s121/mut_shp121.draft.txt
Mutants marked [pre-seal ...] answer the pre-seal check (RC8 ceiling; window rows vs estimator rows m6/m7/m12/m15;
duplicates in the correctness sums m16; hold == 300 m24).
Every anchor occurs exactly once in shp121.py (LF).  The mutants texmemo8.md section 8.4 lists are marked [MH]; the
rest is one mutant per constant, threshold comparison, window edge, unit conversion, admission check, correctness key,
leak key, identity term / class / relation, verify-result field, verdict branch and report line.
Left out as exact equivalents (the reason each): `frame < START` dropped in gate_lines_ok (a frame below START gives a
negative block, never in `blocks`); `frame <= START` -> `frame < START` in skip_in_window (frame START gives block -1);
`res <= 0` -> `res < 0` in identity_failures (a zero residual is within every tolerance); `cls == 'far'` dropped from
the run-total test (no NEAR equality exists).  The loop below is the old-style draft check only."""
import subprocess
import sys
from pathlib import Path

STAGE = Path('C:/kyty/s121/work_mut_shp121')
SRC = Path('C:/kyty/s121/shp121.py').read_text(encoding='utf-8')
MUTANTS = [
    # ---- constants: run shape, window, thresholds, units
    ('hold_s', 'HOLD_S = 300', 'HOLD_S = 299'),
    ('period', 'PERIOD = 90\n', 'PERIOD = 91\n'),
    ('start', 'START = 1800', 'START = 1710'),
    ('keep_lo9', 'KEEP = (10, 89)', 'KEEP = (9, 89)'),
    ('keep_lo11', 'KEEP = (10, 89)', 'KEEP = (11, 89)'),
    ('keep_hi90', 'KEEP = (10, 89)', 'KEEP = (10, 90)'),                                           # [MH 10-89]
    ('keep_hi88', 'KEEP = (10, 89)', 'KEEP = (10, 88)'),
    ('window_0_88', 'KEEP = (10, 89)', 'KEEP = (0, 89)'),                                          # [MH]
    ('window_60_88', 'KEEP = (10, 89)', 'KEEP = (60, 89)'),                                        # [MH]
    ('draws_min_2999', 'DRAWS_MIN = 3000', 'DRAWS_MIN = 2999'),
    ('draws_min_3001', 'DRAWS_MIN = 3000', 'DRAWS_MIN = 3001'),
    ('abba', 'ABBA = (0, 1, 1, 0)', 'ABBA = (0, 1, 0, 1)'),
    ('arms_swapped', 'ARM_P = 0\nARM_M = 1', 'ARM_P = 1\nARM_M = 0'),                              # [MH sign]
    ('arm_text_p', "ARM_TEXT = ('texmemo8=1', 'texmemo8=0')", "ARM_TEXT = ('texmemo8=2', 'texmemo8=0')"),
    ('arm_text_m', "ARM_TEXT = ('texmemo8=1', 'texmemo8=0')", "ARM_TEXT = ('texmemo8=1', 'texmemo8=0 r1cen=0')"),
    ('min_pairs_29', 'MIN_PAIRS = 30', 'MIN_PAIRS = 29'),
    ('min_pairs_31', 'MIN_PAIRS = 30', 'MIN_PAIRS = 31'),
    ('idle_9', 'IDLE_GPU_MAX = 10', 'IDLE_GPU_MAX = 9'),
    ('idle_11', 'IDLE_GPU_MAX = 10', 'IDLE_GPU_MAX = 11'),
    ('arm_min_299', 'ARM_MIN = 300.0 ', 'ARM_MIN = 299.0 '),
    ('arm_min_301', 'ARM_MIN = 300.0 ', 'ARM_MIN = 301.0 '),
    ('arm_min_800', 'ARM_MIN = 300.0 ', 'ARM_MIN = 800.0 '),                                        # [MH bands]
    ('census_arm', 'CENSUS_ARM = 1190.0', 'CENSUS_ARM = 1259.0'),
    ('pred_us', 'PRED_US = -350.0', 'PRED_US = -300.0'),
    ('pred_lo', 'PRED_LO = -500.0', 'PRED_LO = -400.0'),
    ('pred_hi', 'PRED_HI = -250.0', 'PRED_HI = -200.0'),
    ('game_frame', 'GAME_FRAME_US = 16667.0', 'GAME_FRAME_US = 16666.0'),
    ('ns_per_us_1', 'NS_PER_US = 1000.0', 'NS_PER_US = 1.0'),                                      # [MH ns as us]
    ('ns_per_us_1e6', 'NS_PER_US = 1000.0', 'NS_PER_US = 1000000.0'),
    ('skew_near_7', 'SKEW_NEAR = 8 ', 'SKEW_NEAR = 7 '),
    ('skew_near_80', 'SKEW_NEAR = 8 ', 'SKEW_NEAR = 80 '),                                         # [MH +-80]
    ('skew_near_removed', 'SKEW_NEAR = 8 ', 'SKEW_NEAR = 10 ** 9 '),                               # [MH removed]
    ('skew_far_abs_63', 'SKEW_FAR_ABS = 64 ', 'SKEW_FAR_ABS = 63 '),
    ('skew_far_abs_65', 'SKEW_FAR_ABS = 64 ', 'SKEW_FAR_ABS = 65 '),
    ('skew_far_abs_256', 'SKEW_FAR_ABS = 64 ', 'SKEW_FAR_ABS = 256 '),
    ('skew_far_permille_2', 'SKEW_FAR_PERMILLE = 1', 'SKEW_FAR_PERMILLE = 2'),
    ('skew_far_permille_0', 'SKEW_FAR_PERMILLE = 1', 'SKEW_FAR_PERMILLE = 0'),
    ('skew_mean_2', 'SKEW_MEAN_PER10K = 1 ', 'SKEW_MEAN_PER10K = 2 '),
    ('skew_mean_0', 'SKEW_MEAN_PER10K = 1 ', 'SKEW_MEAN_PER10K = 0 '),
    ('bda_new_299', 'BDA_NEW_MAX = 300', 'BDA_NEW_MAX = 299'),
    ('bda_new_301', 'BDA_NEW_MAX = 300', 'BDA_NEW_MAX = 301'),
    ('bda_old_599', 'BDA_OLD_MIN = 600', 'BDA_OLD_MIN = 599'),
    ('bda_old_601', 'BDA_OLD_MIN = 600', 'BDA_OLD_MIN = 601'),
    ('build_sha', "BUILD_SHA = '0bd21ec24e546fbbb9b923c148fb76b57f45389ac166a71bad7410a3add738c7'",
     "BUILD_SHA = '0bd21ec24e546fbbb9b923c148fb76b57f45389ac166a71bad7410a3add738c8'"),
    ('gates_sha', "GATES_SHA = '303a784911cf0ffed238f581e47f98876a0a5164a72a24ca32a17fc67820cbbf'",
     "GATES_SHA = '303a784911cf0ffed238f581e47f98876a0a5164a72a24ca32a17fc67820cbbe'"),
    ('pred_path', "PRED_PATH = 'C:/kyty/s121/pred/02_shp121.md'", "PRED_PATH = 'C:/kyty/s121/pred/01_vfy121.md'"),
    ('installed_path', "'/OneDrive/Desktop/ps5 em/kyty_emulator.exe'", "'/kyty_emulator.exe'"),
    ('gates_file', "GATES_FILE = 'C:/kyty/s121/gates_base.txt'", "GATES_FILE = 'C:/kyty/s120/gates_base.txt'"),
    ('tags', "TAGS = ('shp121', 'shp121r')", "TAGS = ('shp121', 'shp121r', 'cen120')"),
    ('vfy_tags', "VFY_TAGS = ('vfy121', 'vfy121r')", "VFY_TAGS = ('vfy121', 'vfy121r', 'vfy999')"),
    ('vfy_tag', "VFY_TAG = 'vfy121'", "VFY_TAG = 'vfy121r'"),
    ('schedule_start', "SCHEDULE = '90+1800:'", "SCHEDULE = '90+1710:'"),
    ('env_trace', "    'KYTY_FRAME_TRACE': 'lite',", "    'KYTY_FRAME_TRACE': '1',"),
    ('env_hang', "    'KYTY_GPU_HANG_ABORT_S': '8',", "    'KYTY_GPU_HANG_ABORT_S': '0',"),
    ('env_gatefile', "    'KYTY_GATE_FILE': 'C:\\\\kyty\\\\s121\\\\gates.req',",
     "    'KYTY_GATE_FILE': 'C:\\\\kyty\\\\s120\\\\gates.req',"),
    ('env_sample', "    'KYTY_SAMPLE_GATE': 'C:\\\\kyty\\\\s121\\\\sample.req',",
     "    'KYTY_SAMPLE_GATE': 'C:\\\\kyty\\\\s120\\\\sample.req',"),
    ('env_queue', "    'KYTY_QUEUE_TRACE': '1',", "    'KYTY_QUEUE_TRACE': '2',"),
    ('env_guest', "    'KYTY_GUEST_ARGS': '-lvl underwater_aerial_garden',", "    'KYTY_GUEST_ARGS': '-lvl intro_next',"),
    ('env_sched', "    'KYTY_GATE_SCHEDULE': SCHEDULE,", ""),
    ('env_abba', "    'KYTY_GATE_SCHEDULE_ABBA': '1',", "    'KYTY_GATE_SCHEDULE_ABBA': '0',"),
    ('env_pin', "    'KYTY_GPU_CLOCK_PIN': '1',\n    'KYTY_GPU_MARKERS'", "    'KYTY_GPU_CLOCK_PIN': '2',\n    'KYTY_GPU_MARKERS'"),
    ('env_markers', "    'KYTY_GPU_MARKERS': '0',", "    'KYTY_GPU_MARKERS': '2',"),
    ('vk_allowed', "VK_ALLOWED = ('VK_SDK_PATH',)", "VK_ALLOWED = ('VK_SDK_PATH', 'VK_LAYER_PATH')"),
    # ---- the gate-text asserts (ROADMAP s121 item 4)
    ('absent_texmemo2', "BASE_ABSENT_OR_0 = ('texmemo2', 'texfastcheck',", "BASE_ABSENT_OR_0 = ('texfastcheck',"),  # [MH]
    ('absent_texfastcheck', "BASE_ABSENT_OR_0 = ('texmemo2', 'texfastcheck',", "BASE_ABSENT_OR_0 = ('texmemo2',"),
    ('absent_r1cen', "'texfastcheck', 'r1cen', 'r2cen', 'spcen')", "'texfastcheck', 'r2cen', 'spcen')"),
    ('absent_r2cen', "'texfastcheck', 'r1cen', 'r2cen', 'spcen')", "'texfastcheck', 'r1cen', 'spcen')"),
    ('absent_spcen', "'texfastcheck', 'r1cen', 'r2cen', 'spcen')", "'texfastcheck', 'r1cen', 'r2cen')"),
    ('assert_value_any', "        if g.get(name) not in (None, '0'):", "        if g.get(name) is not None:"),
    ('assert_value_dropped', "        if g.get(name) not in (None, '0'):\n            return False",
     "        if False:\n            return False"),
    ('assert_texts_dropped', "            if any(name in first_values(t) for t in texts[arm]):\n                return False",
     "            if False:\n                return False"),
    ('assert_texts_p_only', "        for arm in (ARM_P, ARM_M):\n            if any(", "        for arm in (ARM_P,):\n            if any("),
    ('assert_texts_m_only', "        for arm in (ARM_P, ARM_M):\n            if any(", "        for arm in (ARM_M,):\n            if any("),
    ('assert_needs_p', "    if not texts.get(ARM_P) or not texts.get(ARM_M):\n        return False\n    for name",
     "    if not texts.get(ARM_M):\n        return False\n    for name"),
    ('assert_needs_m', "    if not texts.get(ARM_P) or not texts.get(ARM_M):\n        return False\n    for name",
     "    if not texts.get(ARM_P):\n        return False\n    for name"),
    ('assert_on_base_file', '        arm_asserts=arm_asserts(texts, gates_text),', '        arm_asserts=arm_asserts(texts, base_text),'),
    ('first_value_last_wins', '            out.setdefault(k, v)', '            out[k] = v'),
    # ---- markers and lines
    ('marker_hang', "MARKERS = (b'gpuhangabort', ", "MARKERS = ("),
    ('marker_waitslow', "b'gpuwaitslow', ", ""),
    ('marker_hung', "b'gpumarkerhung', ", ""),
    ('marker_ckpt', "b'gpucheckpointhang', ", ""),
    ('marker_lost', "b'errordevicelost',\n", "\n"),
    ('marker_terminate', "           b'std::terminate', ", "           "),
    ('marker_abort', "b'abort()', ", ""),
    ('marker_fatal', "b'fatal', ", ""),
    ('marker_unhandled', "b'unhandled exception', ", ""),
    ('marker_error', "b'--- error ---')", ")"),
    ('marker_case', '    return any(k in low for k in MARKERS)', '    return any(k in line for k in MARKERS)'),
    ('marker_stdout_dropped', "    if stdout_path is not None and Path(stdout_path).is_file():",
     "    if stdout_path is None and Path(stdout_path).is_file():"),
    ('skipped_text', "SKIPPED_DRAW = b'AsyncPipelines: skipped draw'", "SKIPPED_DRAW = b'AsyncPipelines: skipped draws'"),
    ('skip_attrib', '                skipped.append(None if last_main is None else last_main + 1)',
     '                skipped.append(None if last_main is None else last_main)'),
    ('mismatch_verify', "TM8_MISMATCH = re.compile(rb'Tm8(?:Verify|Rebind)Mismatch:')",
     "TM8_MISMATCH = re.compile(rb'Tm8(?:Rebind)Mismatch:')"),
    ('mismatch_rebind', "TM8_MISMATCH = re.compile(rb'Tm8(?:Verify|Rebind)Mismatch:')",
     "TM8_MISMATCH = re.compile(rb'Tm8(?:Verify)Mismatch:')"),
    ('injected_verify', "TM8_INJECTED = re.compile(rb'Tm8(?:Verify|Rebind)Injected:')",
     "TM8_INJECTED = re.compile(rb'Tm8(?:Rebind)Injected:')"),
    ('injected_rebind', "TM8_INJECTED = re.compile(rb'Tm8(?:Verify|Rebind)Injected:')",
     "TM8_INJECTED = re.compile(rb'Tm8(?:Verify)Injected:')"),
    # ---- counter families
    ('rare_evict_view', "TM8_RARE = ('tm8_fill', 'tm8_evict', 'tm8_evict_view', ", "TM8_RARE = ('tm8_fill', 'tm8_evict', "),
    ('rare_alias', "'tm8_alias', 'tm8_inval', ", "'tm8_inval', "),
    ('rare_renorm', "'tm8_mode', 'tm8_renorm', 'tm8_x2',", "'tm8_mode', 'tm8_x2',"),
    ('verify_look', "TM8_VERIFY = ('tm8_look', ", "TM8_VERIFY = ("),                               # [MH S2]
    ('verify_hit', "'tm8_hit', 'tm8_miss', ", "'tm8_miss', "),
    ('verify_miss', "'tm8_miss', 'tm8_stale', ", "'tm8_stale', "),
    ('verify_stale', "'tm8_stale', 'tm8_gain', ", "'tm8_gain', "),
    ('verify_gain', "'tm8_gain', 'tm8_vchk', ", "'tm8_vchk', "),
    ('verify_vchk', "'tm8_vchk', 'tm8_bad', ", "'tm8_bad', "),
    ('verify_vctl', "'tm8_bad', 'tm8_vctl',\n", "'tm8_bad',\n"),
    ('verify_inject', "'tm8_inject', 'tm8_inject_miss', ", "'tm8_inject_miss', "),
    ('verify_inject_miss', "'tm8_inject_miss', 'tm8_dlose', ", "'tm8_dlose', "),
    ('verify_dlose', "'tm8_dlose', 'tm8_ddiff', ", "'tm8_ddiff', "),
    ('verify_ddiff', "'tm8_ddiff', 'tm8_dcc_chg',\n", "'tm8_dcc_chg',\n"),
    ('verify_dcc', "'tm8_ddiff', 'tm8_dcc_chg',\n", "'tm8_ddiff',\n"),
    ('verify_rbchk', "'tm8_rbchk', 'tm8_rbbad', ", "'tm8_rbbad', "),
    ('verify_rbinject', "'tm8_rbinject', 'tm8_rbinject_miss', ", "'tm8_rbinject_miss', "),
    ('verify_rbinject_miss', "'tm8_rbinject_miss', 'tm8_pb0_ns', ", "'tm8_pb0_ns', "),
    ('verify_pb0', "'tm8_pb0_ns', 'tm8_pb_ns', ", "'tm8_pb_ns', "),
    ('verify_pb', "'tm8_pb_ns', 'tm8_pb_n')", "'tm8_pb_n')"),
    ('verify_pbn', "'tm8_pb_ns', 'tm8_pb_n')", "'tm8_pb_ns')"),
    ('correct_bad', "CORRECT_KEYS = ('tm8_bad', 'tm8_vctl_bad', 'tm8_relive', 'tm8_rbbad')",
     "CORRECT_KEYS = ('tm8_vctl_bad', 'tm8_relive', 'tm8_rbbad')"),
    ('correct_vctl_bad', "CORRECT_KEYS = ('tm8_bad', 'tm8_vctl_bad', 'tm8_relive', 'tm8_rbbad')",
     "CORRECT_KEYS = ('tm8_bad', 'tm8_relive', 'tm8_rbbad')"),
    ('correct_relive', "CORRECT_KEYS = ('tm8_bad', 'tm8_vctl_bad', 'tm8_relive', 'tm8_rbbad')",
     "CORRECT_KEYS = ('tm8_bad', 'tm8_vctl_bad', 'tm8_rbbad')"),
    ('correct_rbbad', "CORRECT_KEYS = ('tm8_bad', 'tm8_vctl_bad', 'tm8_relive', 'tm8_rbbad')",
     "CORRECT_KEYS = ('tm8_bad', 'tm8_vctl_bad', 'tm8_relive')"),
    ('leak_keeps_correct', 'LEAK_KEYS = tuple(k for k in TM8_VERIFY if k not in CORRECT_KEYS)',
     'LEAK_KEYS = TM8_VERIFY'),
    ('zero_x2', "ZERO_ALL_KEYS = ('tm8_x2', 'tm8_cenoff')", "ZERO_ALL_KEYS = ('tm8_cenoff',)"),
    ('zero_cenoff', "ZERO_ALL_KEYS = ('tm8_x2', 'tm8_cenoff')", "ZERO_ALL_KEYS = ('tm8_x2',)"),
    ('switch_inval', "SWITCH_KEYS = ('tm8_inval', 'tm8_mode')", "SWITCH_KEYS = ('tm8_mode',)"),
    ('switch_mode', "SWITCH_KEYS = ('tm8_inval', 'tm8_mode')", "SWITCH_KEYS = ('tm8_inval',)"),
    ('armed_fill_key', "ARMED_KEYS = ('tm8_fill', 'tm8_evict')", "ARMED_KEYS = ('tm8_evict',)"),
    ('armed_evict_key', "ARMED_KEYS = ('tm8_fill', 'tm8_evict')", "ARMED_KEYS = ('tm8_fill',)"),
    ('p_info_alias', "'tm8_evict_view', 'tm8_alias', 'tm8_renorm')", "'tm8_evict_view', 'tm8_renorm')"),
    ('key_miss_empty', "KEY_MISS = ('texmemo_collide', 'texmemo_empty')", "KEY_MISS = ('texmemo_collide',)"),
    ('key_miss_stale', "KEY_MISS = ('texmemo_collide', 'texmemo_empty')",
     "KEY_MISS = ('texmemo_collide', 'texmemo_empty', 'texmemo_stale')"),
    ('report_diff_rec', "REPORT_DIFFS = ('texmemo_stale', 'texfast_ok', 'texfast_no', 'texfast_rec', 'b_texn')",
     "REPORT_DIFFS = ('texmemo_stale', 'texfast_ok', 'texfast_no', 'b_texn')"),
    # ---- regexes of the log
    ('field_neg', "FIELD = re.compile(rb' (\\w+)=(-?\\d+)')", "FIELD = re.compile(rb' (\\w+)=(\\d)')"),
    ('pin_regex', "PIN = re.compile(rb'^GpuClockPin: mode (\\d+)')", "PIN = re.compile(rb'^GpuClockPin: mode 1(\\d*)')"),
    ('gate_regex', "GATE = re.compile(rb'^Gate: (\\w+)=(\\d+) frame=(\\d+)$')",
     "GATE = re.compile(rb'^Gate: (\\w+)=(\\d+) frame=(\\d+)')"),
    ('gatearm_regex', "period=(\\d+) abba=(\\d+) text=(.*)$')", "period=(\\d+) abba=(\\d+) text=(\\S*)')"),
    # ---- identities (review RC1)
    ('id_texn_hits', "     ('tex_hits', 'texmemo_collide', 'texmemo_empty', 'texmemo_stale', 'tnull_hit', 'tnull_miss'), 'far', 'eq'),",
     "     ('texmemo_collide', 'texmemo_empty', 'texmemo_stale', 'tnull_hit', 'tnull_miss'), 'far', 'eq'),"),
    ('id_texn_collide', "     ('tex_hits', 'texmemo_collide', 'texmemo_empty', 'texmemo_stale', 'tnull_hit', 'tnull_miss'), 'far', 'eq'),",
     "     ('tex_hits', 'texmemo_empty', 'texmemo_stale', 'tnull_hit', 'tnull_miss'), 'far', 'eq'),"),
    ('id_texn_empty', "     ('tex_hits', 'texmemo_collide', 'texmemo_empty', 'texmemo_stale', 'tnull_hit', 'tnull_miss'), 'far', 'eq'),",
     "     ('tex_hits', 'texmemo_collide', 'texmemo_stale', 'tnull_hit', 'tnull_miss'), 'far', 'eq'),"),
    ('id_texn_stale', "     ('tex_hits', 'texmemo_collide', 'texmemo_empty', 'texmemo_stale', 'tnull_hit', 'tnull_miss'), 'far', 'eq'),",
     "     ('tex_hits', 'texmemo_collide', 'texmemo_empty', 'tnull_hit', 'tnull_miss'), 'far', 'eq'),"),
    ('id_texn_nullhit', "     ('tex_hits', 'texmemo_collide', 'texmemo_empty', 'texmemo_stale', 'tnull_hit', 'tnull_miss'), 'far', 'eq'),",
     "     ('tex_hits', 'texmemo_collide', 'texmemo_empty', 'texmemo_stale', 'tnull_miss'), 'far', 'eq'),"),
    ('id_texn_nullmiss', "     ('tex_hits', 'texmemo_collide', 'texmemo_empty', 'texmemo_stale', 'tnull_hit', 'tnull_miss'), 'far', 'eq'),",
     "     ('tex_hits', 'texmemo_collide', 'texmemo_empty', 'texmemo_stale', 'tnull_hit'), 'far', 'eq'),"),
    ('id_texn_near', "'tnull_hit', 'tnull_miss'), 'far', 'eq'),", "'tnull_hit', 'tnull_miss'), 'near', 'eq'),"),  # [MH FAR as NEAR]
    ('id_texn_le', "'tnull_hit', 'tnull_miss'), 'far', 'eq'),", "'tnull_hit', 'tnull_miss'), 'far', 'le'),"),
    ('id_fill_collide', "     ('texmemo_collide', 'texmemo_empty', 'texmemo_stale', 'tm8_bad', 'tm8_vctl_bad', 'tm8_relive'), 'far', 'le'),",
     "     ('texmemo_empty', 'texmemo_stale', 'tm8_bad', 'tm8_vctl_bad', 'tm8_relive'), 'far', 'le'),"),
    ('id_fill_empty', "     ('texmemo_collide', 'texmemo_empty', 'texmemo_stale', 'tm8_bad', 'tm8_vctl_bad', 'tm8_relive'), 'far', 'le'),",
     "     ('texmemo_collide', 'texmemo_stale', 'tm8_bad', 'tm8_vctl_bad', 'tm8_relive'), 'far', 'le'),"),
    ('id_fill_stale', "     ('texmemo_collide', 'texmemo_empty', 'texmemo_stale', 'tm8_bad', 'tm8_vctl_bad', 'tm8_relive'), 'far', 'le'),",
     "     ('texmemo_collide', 'texmemo_empty', 'tm8_bad', 'tm8_vctl_bad', 'tm8_relive'), 'far', 'le'),"),
    ('id_fill_bad', "'texmemo_stale', 'tm8_bad', 'tm8_vctl_bad', 'tm8_relive'), 'far', 'le'),",
     "'texmemo_stale', 'tm8_vctl_bad', 'tm8_relive'), 'far', 'le'),"),
    ('id_fill_vctl_bad', "'texmemo_stale', 'tm8_bad', 'tm8_vctl_bad', 'tm8_relive'), 'far', 'le'),",
     "'texmemo_stale', 'tm8_bad', 'tm8_relive'), 'far', 'le'),"),
    ('id_fill_relive', "'texmemo_stale', 'tm8_bad', 'tm8_vctl_bad', 'tm8_relive'), 'far', 'le'),",
     "'texmemo_stale', 'tm8_bad', 'tm8_vctl_bad'), 'far', 'le'),"),
    ('id_fill_near', "'tm8_vctl_bad', 'tm8_relive'), 'far', 'le'),", "'tm8_vctl_bad', 'tm8_relive'), 'near', 'le'),"),
    ('id_evict_fill_far', "    ('evict<=fill', ('tm8_evict',), ('tm8_fill',), 'near', 'le'),",
     "    ('evict<=fill', ('tm8_evict',), ('tm8_fill',), 'far', 'le'),"),
    ('id_evict_fill_dropped', "    ('evict<=fill', ('tm8_evict',), ('tm8_fill',), 'near', 'le'),\n", ""),
    ('id_evict_collide_near', "    ('evict<=collide', ('tm8_evict',), ('texmemo_collide',), 'far', 'le'),",
     "    ('evict<=collide', ('tm8_evict',), ('texmemo_collide',), 'near', 'le'),"),
    ('id_evict_collide_dropped', "    ('evict<=collide', ('tm8_evict',), ('texmemo_collide',), 'far', 'le'),\n", ""),
    ('id_view_far', "    ('evict_view<=evict', ('tm8_evict_view',), ('tm8_evict',), 'near', 'le'),",
     "    ('evict_view<=evict', ('tm8_evict_view',), ('tm8_evict',), 'far', 'le'),"),
    ('id_view_dropped', "    ('evict_view<=evict', ('tm8_evict_view',), ('tm8_evict',), 'near', 'le'),\n", ""),
    ('within_near_lt', '        return abs(res) <= SKEW_NEAR', '        return abs(res) < SKEW_NEAR'),
    ('within_far_lt', '    return 1000 * abs(res) <= max(1000 * SKEW_FAR_ABS,', '    return 1000 * abs(res) < max(1000 * SKEW_FAR_ABS,'),
    ('within_far_lhs', 'SKEW_FAR_PERMILLE * max(abs(lhs), abs(rhs)))', 'SKEW_FAR_PERMILLE * abs(rhs))'),
    ('within_far_rhs', 'SKEW_FAR_PERMILLE * max(abs(lhs), abs(rhs)))', 'SKEW_FAR_PERMILLE * abs(lhs))'),
    ('within_far_min', 'SKEW_FAR_PERMILLE * max(abs(lhs), abs(rhs)))', 'SKEW_FAR_PERMILLE * min(abs(lhs), abs(rhs)))'),
    ('within_far_no_abs', "    return 1000 * abs(res) <= max(", "    return 1000 * res <= max("),
    ('le_two_sided', "            if rel == 'le' and res <= 0:\n                continue\n", ""),
    ('le_sign', "            if rel == 'le' and res <= 0:", "            if rel == 'le' and res >= 0:"),
    ('total_dropped', "        if rel == 'eq' and cls == 'far' and 10000 * abs(tl - tr)", "        if False and 10000 * abs(tl - tr)"),
    ('total_1000', "and 10000 * abs(tl - tr) > SKEW_MEAN_PER10K", "and 1000 * abs(tl - tr) > SKEW_MEAN_PER10K"),
    ('total_min', 'SKEW_MEAN_PER10K * max(abs(tl), abs(tr)):', 'SKEW_MEAN_PER10K * min(abs(tl), abs(tr)):'),
    ('total_le_too', "        if rel == 'eq' and cls == 'far' and 10000", "        if cls == 'far' and 10000"),
    ('identity_first_block_only', "            tl += lhs\n", "            tl = lhs\n"),
    ('identity_est', "            lhs = sum(r[k] for r in blk['ident'] for k in left)\n            rhs = sum(r[k] for r in blk['ident'] for k in right)",
     "            lhs = sum(r[k] for r in blk['est'] for k in left)\n            rhs = sum(r[k] for r in blk['est'] for k in right)"),  # [pre-seal m12]
    ('identity_rhs_est', "            rhs = sum(r[k] for r in blk['ident'] for k in right)",
     "            rhs = sum(r[k] for r in blk['est'] for k in right)"),
    ('identity_window_all', "            lhs = sum(r[k] for r in blk['ident'] for k in left)",
     "            lhs = sum(r[k] for r in blk['est'] for k in left)"),
    # ---- helpers
    ('idle_lt', '    return isinstance(v, (int, float)) and v <= IDLE_GPU_MAX', '    return isinstance(v, (int, float)) and v < IDLE_GPU_MAX'),
    ('idle_any_type', '    return isinstance(v, (int, float)) and v <= IDLE_GPU_MAX', '    return v is not None and float(v) <= IDLE_GPU_MAX'),
    ('two_se_se', '    return 2.0 * statistics.stdev(values) / math.sqrt(len(values))',
     '    return 1.0 * statistics.stdev(values) / math.sqrt(len(values))'),                         # [MH SE for 2SE]
    ('two_se_no_sqrt', '    return 2.0 * statistics.stdev(values) / math.sqrt(len(values))',
     '    return 2.0 * statistics.stdev(values) / len(values)'),
    ('two_se_pstdev', '    return 2.0 * statistics.stdev(values) / math.sqrt(len(values))',
     '    return 2.0 * statistics.pstdev(values) / math.sqrt(len(values))'),
    ('two_se_min1', '    if len(values) < 2:\n        return None', '    if len(values) < 1:\n        return None'),
    ('mean_median', '    return sum(values) / len(values) if values else None',
     '    return statistics.median(values) if values else None'),                                  # [MH median]
    ('regime_new_lt', '    if v <= BDA_NEW_MAX:', '    if v < BDA_NEW_MAX:'),
    ('regime_old_gt', '    if v >= BDA_OLD_MIN:', '    if v > BDA_OLD_MIN:'),
    ('regime_mixed', "    return 'MIXED'", "    return 'NEW'"),
    # ---- arms / gate lines
    ('arms_arms', '        if arms != 2 or period', '        if arms < 2 or period'),
    ('arms_period', 'or period != PERIOD or abba', 'or abba'),
    ('arms_abba', 'or abba != 1 or arm not in', 'or arm not in'),
    ('arms_armid', 'or arm not in (0, 1) or text', 'or text'),
    ('arms_text', ' or text != ARM_TEXT[arm]:', ':'),                                             # [MH texts]
    ('arms_text_prefix', ' or text != ARM_TEXT[arm]:', ' or not text.startswith(ARM_TEXT[arm]):'),
    ('arms_frame', '        if frame != START + PERIOD * block or ABBA', '        if ABBA'),
    ('arms_abba_seq', 'or ABBA[block % 4] != arm or block in blocks:', 'or block in blocks:'),
    ('arms_dup', 'or ABBA[block % 4] != arm or block in blocks:', 'or ABBA[block % 4] != arm:'),
    ('arms_consecutive', '    ok = bool(blocks) and sorted(blocks) == list(range(len(blocks)))', '    ok = bool(blocks)'),
    ('arms_empty_ok', '    ok = bool(blocks) and sorted(blocks) == list(range(len(blocks)))',
     '    ok = sorted(blocks) == list(range(len(blocks)))'),
    ('arms_none_line', '        if g is None:\n            return False, {}\n        arm, arms, block',
     '        if g is None:\n            continue\n        arm, arms, block'),
    ('gate_malformed', '        if m is None:\n            return False\n        name = m.group(1)',
     '        if m is None:\n            continue\n        name = m.group(1)'),
    ('gate_name', '        if name not in ARM_VALUES[0] or', '        if'),
    ('gate_modulo', ' or (frame - START) % PERIOD != 0 or', ' or'),
    ('gate_block', '        if block not in blocks or m.group(2)', '        if block not in blocks and m.group(2)'),
    ('gate_value', " or m.group(2).decode() != ARM_VALUES[blocks[block]][name]:", ":"),
    # ---- parse
    ('raw_from_main', "                if kind == 'x':\n                    for k in raw:", "                if kind == 'main':\n                    for k in raw:"),
    ('raw_last_only', '                        raw[k] += int(got.get(k.encode(), 0))', '                        raw[k] = int(got.get(k.encode(), 0))'),
    ('raw_first_copy_only', "                if kind == 'x':\n                    for k in raw:",
     "                if kind == 'x' and n not in seen['x']:\n                    for k in raw:"),    # [pre-seal m16]
    ('rec_partial', '                seen[kind][n] = rec if len(rec) == len(names) else None', '                seen[kind][n] = rec'),
    ('dups_ignored', '                if n in seen[kind]:\n                    dups.add(n)', '                if False:\n                    dups.add(n)'),
    ('last_main_any', "                if kind == 'main':\n                    last_main = n", "                if kind == 'x':\n                    last_main = n"),
    ('pins_any_mode', '                pins.append(int(mp.group(1)) if mp else -1)', '                pins.append(1 if mp else -1)'),
    # ---- select / pairs / streams / skip
    ('select_window_short', "        frames = block_frames(b)[KEEP[0]:KEEP[1]]\n        if all(",
     "        frames = block_frames(b)[KEEP[0]:KEEP[1] - 1]\n        if all("),                     # [MH keep <88]
    ('select_arm_label', "and seen['main'][n]['arm'] == arm and", 'and'),
    ('select_blk_label', " and seen['main'][n]['blk'] == b for n in frames):", " for n in frames):"),
    ('select_draws_ge', "est=[r for r in win if r['draws'] > DRAWS_MIN]", "est=[r for r in win if r['draws'] >= DRAWS_MIN]"),
    ('select_dups', '        return n not in dups and all(seen[k].get(n)', '        return all(seen[k].get(n)'),
    ('pairs_step1', '    pairs = [(b, b + 1) for b in range(0, top, 2)', '    pairs = [(b, b + 1) for b in range(0, top, 1)'),  # [MH]
    ('pairs_nonadjacent', '    pairs = [(b, b + 1) for b in range(0, top, 2)', '    pairs = [(b, b + 2) for b in range(0, top, 2)'),  # [MH]
    ('pairs_est_dropped', "             if b in done and b + 1 in done and done[b]['est'] and done[b + 1]['est']]",
     "             if b in done and b + 1 in done]"),
    ('streams_last_not_exempt', "            if n not in seen['main'] or n == parsed['last_main']:",
     "            if n not in seen['main']:"),
    ('streams_dups', "            if n in dups or any(seen[k].get(n) is None for k in seen):",
     "            if any(seen[k].get(n) is None for k in seen):"),
    ('streams_window', '        for n in block_frames(b)[KEEP[0]:KEEP[1]]:\n            if n not in', '        for n in block_frames(b):\n            if n not in'),
    ('skip_lo', '    return b in blocks and KEEP[0] <= pos < KEEP[1]', '    return b in blocks and KEEP[0] < pos < KEEP[1]'),
    ('skip_hi', '    return b in blocks and KEEP[0] <= pos < KEEP[1]', '    return b in blocks and KEEP[0] <= pos <= KEEP[1]'),
    ('skip_blocks', '    return b in blocks and KEEP[0] <= pos < KEEP[1]', '    return KEEP[0] <= pos < KEEP[1]'),
    # ---- arming proof / leaks
    ('armed_empty_ok', '    return bool(p) and all(sum(r[k]', '    return all(sum(r[k]'),
    ('armed_ge0', "for r in blk['ident']) > 0 for blk in p for k in ARMED_KEYS)", "for r in blk['ident']) >= 0 for blk in p for k in ARMED_KEYS)"),
    ('armed_all_rows_m', "    p = [blk for blk in done.values() if blk['arm'] == ARM_P]", "    p = [blk for blk in done.values()]"),
    ('armed_est', "for r in blk['ident']) > 0 for blk in p for k in ARMED_KEYS)",
     "for r in blk['est']) > 0 for blk in p for k in ARMED_KEYS)"),                                   # [pre-seal m7]
    ('m_zero_est_blocks', "    return all(r[k] == 0 for blk in done.values() if blk['arm'] == ARM_M for r in blk['ident'] for k in TM8_KEYS)",
     "    return all(r[k] == 0 for blk in done.values() if blk['arm'] == ARM_M and blk['est'] for r in blk['ident'] for k in TM8_KEYS)"),  # [pre-seal m15]
    ('m_zero_p', "    return all(r[k] == 0 for blk in done.values() if blk['arm'] == ARM_M for r in blk['ident'] for k in TM8_KEYS)",
     "    return all(r[k] == 0 for blk in done.values() if blk['arm'] == ARM_M for r in blk['est'] for k in TM8_KEYS)"),
    ('m_zero_rare_only', "if blk['arm'] == ARM_M for r in blk['ident'] for k in TM8_KEYS)", "if blk['arm'] == ARM_M for r in blk['ident'] for k in ARMED_KEYS)"),
    ('switch_est', "    return all(r[k] == 0 for blk in done.values() for r in blk['ident'] for k in SWITCH_KEYS)",
     "    return all(r[k] == 0 for blk in done.values() for r in blk['est'] for k in SWITCH_KEYS)"),  # [pre-seal m6]
    ('switch_m_only', "    return all(r[k] == 0 for blk in done.values() for r in blk['ident'] for k in SWITCH_KEYS)",
     "    return all(r[k] == 0 for blk in done.values() if blk['arm'] == ARM_M for r in blk['ident'] for k in SWITCH_KEYS)"),
    ('verify_leak_lines', "all(raw[k] == 0 for k in LEAK_KEYS) and parsed['lines']['tm8_injected'] == 0,",
     "all(raw[k] == 0 for k in LEAK_KEYS),"),
    ('verify_leak_dropped', "        verify_leak=all(raw[k] == 0 for k in LEAK_KEYS) and", "        verify_leak=True or all(raw[k] == 0 for k in LEAK_KEYS) and"),  # [MH S2 third]
    ('x2_dropped', '        x2_cenoff=all(raw[k] == 0 for k in ZERO_ALL_KEYS))', '        x2_cenoff=True)'),
    ('correct_lines', "    correct = all(raw[k] == 0 for k in CORRECT_KEYS) and parsed['lines']['tm8_mismatch'] == 0",
     "    correct = all(raw[k] == 0 for k in CORRECT_KEYS)"),
    ('correct_window_only', "    correct = all(raw[k] == 0 for k in CORRECT_KEYS) and",
     "    correct = all(r[k] == 0 for blk in done.values() for r in blk['ident'] for k in CORRECT_KEYS) and"),  # [MH]
    # ---- admission checks (each dropped)
    ('chk_binary', "        binary=meta.get('binary_sha256') == BUILD_SHA,", '        binary=True,'),
    ('chk_installed', '        installed_now=installed_sha == BUILD_SHA,', '        installed_now=True,'),
    ('chk_pin_env', "        pinned=env.get('KYTY_GPU_CLOCK_PIN') == '1' and parsed['pins'] == [1],", "        pinned=parsed['pins'] == [1],"),
    ('chk_pin_lines', "        pinned=env.get('KYTY_GPU_CLOCK_PIN') == '1' and parsed['pins'] == [1],", "        pinned=env.get('KYTY_GPU_CLOCK_PIN') == '1' and 1 in parsed['pins'],"),
    ('chk_env', "        env_exact=kyty_env == ENV_EXPECT and meta.get('schedule') == SCHEDULE,", "        env_exact=meta.get('schedule') == SCHEDULE,"),
    ('chk_env_subset', "        env_exact=kyty_env == ENV_EXPECT and", "        env_exact=all(kyty_env.get(k) == v for k, v in ENV_EXPECT.items()) and"),
    ('chk_schedule', "        env_exact=kyty_env == ENV_EXPECT and meta.get('schedule') == SCHEDULE,", "        env_exact=kyty_env == ENV_EXPECT,"),
    ('chk_vk', '        env_vk=all(k in VK_ALLOWED for k in vk_env),', '        env_vk=True,'),
    ('chk_hold', "        hold=draft or meta.get('hold_s') == HOLD_S,", '        hold=True,'),
    ('chk_hold_draft', "        hold=draft or meta.get('hold_s') == HOLD_S,", "        hold=meta.get('hold_s') == HOLD_S,"),
    ('chk_hold_ge', "        hold=draft or meta.get('hold_s') == HOLD_S,", "        hold=draft or meta.get('hold_s') >= HOLD_S,"),  # [pre-seal m24]
    ('chk_attempts_one', '        one_ok_attempt=len(atts) == 1 and len(ok_att) == 1,', '        one_ok_attempt=len(ok_att) == 1,'),
    ('chk_attempts_ok', '        one_ok_attempt=len(atts) == 1 and len(ok_att) == 1,', '        one_ok_attempt=len(atts) == 1,'),
    ('chk_attempt_exit', "    ok_att = [a for a in atts if a.get('outcome') == 'ok' and a.get('hold_exit') is None]",
     "    ok_att = [a for a in atts if a.get('outcome') == 'ok']"),
    ('chk_prereg', '        prereg=prereg_ok,', '        prereg=True,'),
    ('chk_prereg_sha', '        prereg_sha=prereg_sha_ok,', '        prereg_sha=True,'),
    ('chk_gates', '        gates_exact=(Path(gates_file).is_file() and sha_file(gates_file) == GATES_SHA and gates_text == base_text),',
     '        gates_exact=(Path(gates_file).is_file() and sha_file(gates_file) == GATES_SHA),'),
    ('chk_gates_sha', '        gates_exact=(Path(gates_file).is_file() and sha_file(gates_file) == GATES_SHA and gates_text == base_text),',
     '        gates_exact=(gates_text == base_text),'),
    ('chk_gates_ws', "    gates_text = ' '.join((meta.get('gates') or '').split())", "    gates_text = meta.get('gates') or ''"),
    ('chk_arm_asserts', '        arm_asserts=arm_asserts(texts, gates_text),', '        arm_asserts=True,'),
    ('chk_gate_lines', "        gate_lines=gate_lines_ok(parsed['gate_lines'], blocks),", '        gate_lines=True,'),
    ('chk_arms', '        arms=arms_fine,', '        arms=True,'),
    ('chk_marker', "        no_marker=not parsed['markers'],", '        no_marker=True,'),
    ('chk_skip', '        no_skip_window=not skipped_in,', '        no_skip_window=True,'),
    ('chk_streams', '        streams=streams_ok(parsed, blocks),', '        streams=True,'),
    ('chk_pairs', '        pairs=draft or len(pairs) >= min_pairs,', '        pairs=True,'),
    ('chk_pairs_gt', '        pairs=draft or len(pairs) >= min_pairs,', '        pairs=draft or len(pairs) > min_pairs,'),
    ('chk_idle', '        idle=idle_ok(meta),', '        idle=True,'),
    ('chk_armed', '        armed_fill=armed_fill_ok(done),', '        armed_fill=True,'),                # [MH S2]
    ('chk_m_zero', '        m_zero=m_zero_ok(done),', '        m_zero=True,'),                          # [MH S2 leak]
    ('chk_switch', '        no_switch_in_window=no_switch_ok(done),', '        no_switch_in_window=True,'),
    ('admitted_any', '    admitted = all(checks.values())', '    admitted = any(checks.values())'),
    ('min_pairs_default', '    min_pairs = MIN_PAIRS if min_pairs is None else min_pairs', '    min_pairs = 4 if min_pairs is None else min_pairs'),
    # ---- pre-registration
    ('pred_draft_bypass', '    if draft:\n        return True, True\n    prereg', '    if False:\n        return True, True\n    prereg'),
    ('pred_path_slashes', "    path_ok = str(prereg.get('path') or '').replace('\\\\', '/') == pred_path",
     "    path_ok = str(prereg.get('path') or '') == pred_path"),
    ('pred_unsealed', '    if not pred_sha or not pred_bytes or not Path(pred_path).is_file():',
     '    if not Path(pred_path).is_file():'),
    ('pred_file_sha', '    sha_ok = (hashlib.sha256(data).hexdigest() == pred_sha and len(data) == pred_bytes',
     '    sha_ok = (len(data) == pred_bytes'),
    ('pred_file_bytes', '(data).hexdigest() == pred_sha and len(data) == pred_bytes\n', '(data).hexdigest() == pred_sha\n'),
    ('pred_meta_sha', "              and prereg.get('sha256') == pred_sha and prereg.get('bytes') == pred_bytes)",
     "              and prereg.get('bytes') == pred_bytes)"),
    ('pred_meta_bytes', "              and prereg.get('sha256') == pred_sha and prereg.get('bytes') == pred_bytes)",
     "              and prereg.get('sha256') == pred_sha)"),
    ('pred_default_path', '    pred_path = PRED_PATH if pred_path is None else pred_path', '    pred_path = pred_path or GATES_FILE'),
    ('pred_default_sha', '    pred_sha = PRED_SHA if pred_sha is None else pred_sha', '    pred_sha = PRED_SHA if pred_sha is None else PRED_SHA'),
    # ---- verify result (S9)
    ('vfy_default_sha', '    vfy_sha = VFY_SCORER_SHA if vfy_sha is None else vfy_sha', "    vfy_sha = 'ab' * 32 if vfy_sha is None else vfy_sha"),
    ('vfy_ignored', '    elif upper < 0 and vfy_ok:', '    elif upper < 0:'),                            # [MH]
    ('vfy_unsealed_ok', "    if want_sha is None:\n        return False, 'vfy_sha_unsealed', summary",
     "    if want_sha is None:\n        want_sha = v.get('scorer_sha256')"),
    ('vfy_scorer', "    if v.get('scorer_sha256') != want_sha:", '    if False:'),
    ('vfy_build', "    if v.get('build_sha256') != BUILD_SHA:", '    if False:'),
    ('vfy_tagcheck', "    if v.get('tag') != vfy_tag:", '    if False:'),
    ('vfy_draft', "    if v.get('draft') is not False:", '    if v.get(\'draft\') is True:'),
    ('vfy_verdict', "    if v.get('verdict') != 'PASS':", "    if v.get('verdict') not in ('PASS', 'NOT_EVALUABLE'):"),
    ('vfy_dict', "    if not isinstance(v, dict):\n        return False, 'vfy_unreadable', None\n",
     "    if not isinstance(v, (dict, list)):\n        return False, 'vfy_unreadable', None\n"),
    ('vfy_path_root', "    vfy_path = Path(root) / 'runs121' / (vfy_tag + '.score.json')",
     "    vfy_path = Path(root) / 'runs121' / (VFY_TAG + '.score.json')"),
    # ---- estimator and verdict
    ('est_sign', '        diffs.append(a - c)', '        diffs.append(c - a)'),                     # [MH sign]
    ('est_pooled', "    return dict(delta=mean(diffs), two_se=two_se(diffs), P=mean(pm), M=mean(mm), pair_diffs=diffs)",
     "    return dict(delta=mean([r[key] for pr in pairs for b in pr if done[b]['arm'] == ARM_P for r in done[b]['est']]) - mean([r[key] for pr in pairs for b in pr if done[b]['arm'] == ARM_M for r in done[b]['est']]), two_se=two_se(diffs), P=mean(pm), M=mean(mm), pair_diffs=diffs)"),  # [MH frames]
    ('est_block_window', "        a = mean([r[key] for r in done[pb]['est']])", "        a = mean([r[key] for r in done[pb]['ident']])"),
    ('est_arm_p_pooled', '    return dict(delta=mean(diffs), two_se=two_se(diffs), P=mean(pm),',
     "    return dict(delta=mean(diffs), two_se=two_se(diffs), P=mean([r[key] for pr in pairs for b in pr if done[b]['arm'] == ARM_P for r in done[b]['est']]),"),
    ('cpu_key', "    cpu = estimate(done, pairs, 'cpu_gpu_us')", "    cpu = estimate(done, pairs, 'dt_us')"),
    ('ship_le', '    elif upper < 0 and vfy_ok:', '    elif upper <= 0 and vfy_ok:'),                 # [MH]
    ('ship_delta_only', '    upper = None if dt[\'delta\'] is None or dt[\'two_se\'] is None else dt[\'delta\'] + dt[\'two_se\']',
     '    upper = None if dt[\'delta\'] is None or dt[\'two_se\'] is None else dt[\'delta\']'),
    ('ship_minus', "else dt['delta'] + dt['two_se']", "else dt['delta'] - dt['two_se']"),
    ('verdict_correct_first', "    if not correct:\n        verdict = 'NO_SHIP'\n    elif not admitted:",
     "    if False:\n        verdict = 'NO_SHIP'\n    elif not admitted:"),
    ('verdict_na_after_ne', "    elif not admitted:\n        verdict = 'NOT_EVALUABLE' if tag == TAGS[1] else 'NOT_ADMITTED'\n    elif ne:\n        verdict = 'NOT_EVALUABLE'",
     "    elif ne:\n        verdict = 'NOT_EVALUABLE'\n    elif not admitted:\n        verdict = 'NOT_EVALUABLE' if tag == TAGS[1] else 'NOT_ADMITTED'"),
    ('verdict_repeat_rule', "        verdict = 'NOT_EVALUABLE' if tag == TAGS[1] else 'NOT_ADMITTED'", "        verdict = 'NOT_ADMITTED'"),
    ('verdict_ne_dropped', "    elif ne:\n        verdict = 'NOT_EVALUABLE'\n    elif upper", "    elif False:\n        verdict = 'NOT_EVALUABLE'\n    elif upper"),
    ('verdict_else', "    else:\n        verdict = 'NO_SHIP'\n", "    else:\n        verdict = 'NOT_EVALUABLE'\n"),
    # ---- not evaluable: arming, regime, 2SE
    ('arm_hits_gt', "    if arming['tex_hits'] is None or arming['tex_hits'] < ARM_MIN:", "    if arming['tex_hits'] is None or arming['tex_hits'] <= ARM_MIN:"),
    ('arm_hits_dropped', "    if arming['tex_hits'] is None or arming['tex_hits'] < ARM_MIN:", '    if False:'),   # [MH bands]
    ('arm_key_lt', "    if arming['key_miss'] is None or arming['key_miss'] > -ARM_MIN:", "    if arming['key_miss'] is None or arming['key_miss'] >= -ARM_MIN:"),
    ('arm_key_dropped', "    if arming['key_miss'] is None or arming['key_miss'] > -ARM_MIN:", '    if False:'),
    ('arm_key_sign', "    if arming['key_miss'] is None or arming['key_miss'] > -ARM_MIN:", "    if arming['key_miss'] is None or arming['key_miss'] < ARM_MIN:"),
    ('arm_window_est', "    wp = [r for b in p_blocks for r in done[b]['ident']]", "    wp = [r for b in p_blocks for r in done[b]['est']]"),
    ('arm_window_m_est', "    wm = [r for b in m_blocks for r in done[b]['ident']]", "    wm = [r for b in m_blocks for r in done[b]['est']]"),
    ('arm_all_blocks', "    p_blocks = arm_pairs(done, pairs, ARM_P)", "    p_blocks = [b for b in done if done[b]['arm'] == ARM_P]"),
    ('arm_hits_sign', "    arming = dict(tex_hits=diff(window_mean(wp, ('tex_hits',)), window_mean(wm, ('tex_hits',))),",
     "    arming = dict(tex_hits=diff(window_mean(wm, ('tex_hits',)), window_mean(wp, ('tex_hits',))),"),
    ('arm_ceiling_dropped', "    if arming['tex_hits'] is not None and arming['M_key_miss'] is not None and arming['tex_hits'] > arming['M_key_miss']:",
     '    if False:'),                                                                                  # [pre-seal RC8]
    ('arm_ceiling_ge', "and arming['tex_hits'] > arming['M_key_miss']:", "and arming['tex_hits'] >= arming['M_key_miss']:"),
    ('arm_ceiling_p_key', "and arming['tex_hits'] > arming['M_key_miss']:", "and arming['tex_hits'] > arming['P_key_miss']:"),
    ('arm_ceiling_const', "and arming['tex_hits'] > arming['M_key_miss']:", "and arming['tex_hits'] > 1772.0:"),
    ('arm_ceiling_census', "and arming['tex_hits'] > arming['M_key_miss']:", "and arming['tex_hits'] > CENSUS_ARM + ARM_MIN:"),
    ('arm_key_swap', "                  key_miss=diff(window_mean(wp, KEY_MISS), window_mean(wm, KEY_MISS)),",
     "                  key_miss=diff(window_mean(wm, KEY_MISS), window_mean(wp, KEY_MISS)),"),
    ('bda_dropped', "    if bda['P_regime'] is None or bda['P_regime'] != bda['M_regime']:", '    if False:'),    # [MH]
    ('bda_none_ok', "    if bda['P_regime'] is None or bda['P_regime'] != bda['M_regime']:", "    if bda['P_regime'] != bda['M_regime']:"),
    ('bda_window', "    bda = dict(P=mean([r['bda_scan'] for r in est_p]),", "    bda = dict(P=mean([r['bda_scan'] for r in wp]),"),
    ('se_undefined_dropped', "    if dt['two_se'] is None:\n        ne.append('two_se_undefined')", "    if False:\n        ne.append('two_se_undefined')"),
    ('identities_dropped', '    ne += identity_failures(done)', '    ne += []'),
    # ---- reported numbers
    ('speed_formula', '    return None if not dt else GAME_FRAME_US / dt', '    return None if not dt else dt / GAME_FRAME_US'),
    ('speed_pp', "else 100.0 * (speeds['P'] - speeds['M'])", "else 100.0 * (speeds['M'] - speeds['P'])"),
    ('speed_rel', "else 100.0 * (dt['M'] / dt['P'] - 1.0)", "else 100.0 * (dt['P'] / dt['M'] - 1.0)"),
    ('probe_pb0', "(raw['tm8_pb_ns'] - raw['tm8_pb0_ns']) / raw['tm8_pb_n']))", "raw['tm8_pb_ns'] / raw['tm8_pb_n']))"),
    ('probe_floor', "                 else max(0.0, (raw['tm8_pb_ns']", "                 else max(-1e9, (raw['tm8_pb_ns']"),
    ('probe_us_twice', "    probe = dict(pb_us=raw['tm8_pb_ns'] / NS_PER_US,", "    probe = dict(pb_us=raw['tm8_pb_ns'] / NS_PER_US / NS_PER_US,"),  # [MH units]
    ('report_diff_sign', '    info = {k: diff(window_mean(wp, (k,)), window_mean(wm, (k,))) for k in REPORT_DIFFS}',
     '    info = {k: diff(window_mean(wm, (k,)), window_mean(wp, (k,))) for k in REPORT_DIFFS}'),
    ('p_tm8_m', '    p_tm8 = {k: window_mean(wp, (k,)) for k in P_INFO_KEYS}', '    p_tm8 = {k: window_mean(wm, (k,)) for k in P_INFO_KEYS}'),
    # ---- report
    ('rep_delta_line', "    out.append('Delta dt_us (P - M) %s +- %s us (2SE, %d pairs), upper %s; P %s M %s us'",
     "    out.append('Delta dt_us (P - M) %s +- %s us (SE, %d pairs), upper %s; P %s M %s us'"),
    ('rep_pred', "    out.append('prediction %s us (range %s .. %s) [I]' % (fmt(PRED_US), fmt(PRED_LO), fmt(PRED_HI)))",
     "    out.append('prediction %s us (range %s .. %s) [I]' % (fmt(PRED_US), fmt(PRED_HI), fmt(PRED_LO)))"),
    ('rep_speed', "               % (fmt(sp['P'], 4), fmt(sp['M'], 4), fmt(sp['change_pp'], 2), fmt(sp['change_rel_pct'], 2)))",
     "               % (fmt(sp['M'], 4), fmt(sp['P'], 4), fmt(sp['change_pp'], 2), fmt(sp['change_rel_pct'], 2)))"),
    ('rep_cpu', "               % (fmt(cpu['delta']), fmt(cpu['two_se']), fmt(cpu['P']), fmt(cpu['M'])))",
     "               % (fmt(dt['delta']), fmt(cpu['two_se']), fmt(cpu['P']), fmt(cpu['M'])))"),
    ('rep_census', "               % (fmt(a['tex_hits']), fmt(ARM_MIN, 0), fmt(a['M_key_miss']), fmt(CENSUS_ARM, 0), fmt(a['key_miss']),",
     "               % (fmt(a['tex_hits']), fmt(ARM_MIN, 0), fmt(a['M_key_miss']), fmt(ARM_MIN, 0), fmt(a['key_miss']),"),
    ('rep_ceiling', "               % (fmt(a['tex_hits']), fmt(ARM_MIN, 0), fmt(a['M_key_miss']), fmt(CENSUS_ARM, 0), fmt(a['key_miss']),",
     "               % (fmt(a['tex_hits']), fmt(ARM_MIN, 0), fmt(a['P_key_miss']), fmt(CENSUS_ARM, 0), fmt(a['key_miss']),"),
    ('rep_bda', "    out.append('bda_scan P %s (%s) M %s (%s)' % (fmt(res['bda_scan']['P']), res['bda_scan']['P_regime'],",
     "    out.append('bda_scan P %s (%s) M %s (%s)' % (fmt(res['bda_scan']['P']), res['bda_scan']['M_regime'],"),
    ('rep_vfy', "    out.append('vfy %s: %s (%s)' % (v['tag'], 'PASS' if v['ok'] else 'not PASS', v['reason']))",
     "    out.append('vfy %s: %s (%s)' % (v['tag'], 'PASS', v['reason']))"),
    ('rep_not_admitted', "        out.append('REPORT OF A NOT_ADMITTED RUN - NOT TO BE QUOTED')", '        pass'),
    ('rep_draft', "        out.append('DRAFT: unsealed scoring (pre-registration, hold and pair minimum not checked) - not a verdict')", '        pass'),
    ('rep_verdict_draft', "fmt(res['upper']), ' DRAFT' if res['draft'] else ''))", "fmt(res['upper']), ''))"),
    ('rep_correct_tail', "    if not res['correct']:\n        tail = ' ' + CORRECTNESS_NOTE", "    if False:\n        tail = ' ' + CORRECTNESS_NOTE"),
    ('rep_vfy_tail', "    elif res['verdict'] == 'NO_SHIP' and not v['ok']:", "    elif res['verdict'] == 'NO_SHIP':"),
    ('rep_consequence', "    out.append('CONSEQUENCE: %s%s' % (CONSEQUENCE[res['verdict']], tail))",
     "    out.append('CONSEQUENCE: %s%s' % (CONSEQUENCE['NO_SHIP'], tail))"),
    # ---- command line
    ('cli_tag_check', "    if (tag not in TAGS or vfy not in VFY_TAGS) and not draft:", "    if tag not in TAGS and not draft:"),
    ('cli_vfy_passed', '    res = evaluate(root, tag, draft=draft, vfy_tag=vfy)', '    res = evaluate(root, tag, draft=draft)'),
    ('cli_rc', "    return 0 if res['verdict'] in ('SHIP', 'NO_SHIP') else 1", "    return 0"),
]
if __name__ == '__main__':
    STAGE.mkdir(parents=True, exist_ok=True)
    killed = 0
    for name, old, new in MUTANTS:
        if SRC.count(old) != 1:
            print('%-26s ANCHOR x%d' % (name, SRC.count(old)))
            continue
        path = STAGE / ('mut_shp121_%s.py' % name)
        path.write_bytes(SRC.replace(old, new).encode('utf-8'))
        r = subprocess.run([sys.executable, 'C:/kyty/s121/test_shp121.py', str(path)], capture_output=True, text=True)
        killed += r.returncode != 0
        print('%-26s %s' % (name, 'killed' if r.returncode != 0 else 'SURVIVED'))
        path.unlink()
    print('killed %d of %d' % (killed, len(MUTANTS)))
