"""Session 114: mutants of check114.py (from mut_check113.py by make_check114.py) - each must be killed by
test_check114.py; run through mutlib v2 (frozen copy) --control --no-memo on the sealed copy."""
import subprocess
import sys
from pathlib import Path

STAGE = Path('C:/kyty/s106_stage')
SRC = Path('C:/kyty/s114/check114.py').read_text(encoding='utf-8')
MUTANTS = [
    ('frames', 'MIN_FRAMES = 3000', 'MIN_FRAMES = 2999'),
    ('rows', 'MIN_ROWS = 1000', 'MIN_ROWS = 999'),
    ('pin_count', 'pins == 1 and pin1 == 1', 'pin1 >= 1'),
    ('pin_mode', "pin1 += int(line.startswith(b'GpuClockPin: mode 1'))", 'pin1 += 1'),
    ('pin_env', "env.get('KYTY_GPU_CLOCK_PIN') == '1' and ", ''),
    ('rec', "recorded=bool(env.get('KYTY_REC')),", 'recorded=True,'),
    ('sched', "no_schedule='KYTY_GATE_SCHEDULE' not in env,", 'no_schedule=True,'),
    ('ckpt', "no_checkpoints='KYTY_GPU_CHECKPOINTS' not in env,", 'no_checkpoints=True,'),
    ('att_len', 'len(atts) == 1 and ', ''),
    ('def_daslot', "' daslot=' not in gates and ", ''),
    ('def_daguard', "' daguard=' not in gates and ", ''),
    ('def_cspfree', "' daguard=' not in gates and ' cspfree=' not in gates", "' daguard=' not in gates"),
    ('glitch', "int(mg.group(1)) == 0", "int(mg.group(1)) <= 1"),
    ('missing', 'rows >= MIN_ROWS and missing == 0', 'rows >= MIN_ROWS'),
    ('free', "tot['da_q_free'] > 0 and ", ''),
    ('noguard', " and tot['da_q_noguard'] == 0,", ','),
    ('slot_bad', "slot_no_bad=tot['da_slot_bad'] == 0,", 'slot_no_bad=True,'),
    ('hit', "tot['cspfree_hit'] > 0 and ", ''),
    ('free_bad', " and tot['cspfree_bad'] == 0,", ','),
    ('guard', "guard=tot['cs_sync_new'] == 0,", 'guard=True,'),
    ('stdout', "    if so.is_file():", "    if False:"),
    ('stable', 'int(m.group(1)) >= stable', 'int(m.group(1)) >= 0'),
    ('marker_fatal', "b'fatal', ", ''),
    ('installed', 'installed_now=installed_sha == BUILD_SHA,', 'installed_now=True,'),
    ('def_bdanarrow', "and ' bdanarrow=' not in gates)", 'and True)'),
    ('shift', "no_shift='KYTY_BUFFER_GC_TRIGGER_SHIFT_MB' not in env,", 'no_shift=True,'),
    ('nskip', "tot['bda_nskip'] == 0 and ", ''),
    ('would', " and tot['bda_nwould'] == 0,", ','),
    ('gc_count', 'len(gc_lines) == 1 and ', ''),
    ('gc_shift', " and gc_lines[0].endswith(' shift_mb=0'),", ','),
    ('gc_collect', "gc_lines.append(line[:200].decode('utf-8', 'replace').strip())", 'pass'),
    ('title_knob', "no_title_knob=' titleasync=' not in gates,", 'no_title_knob=True,'),
    ('no_hold', "no_hold='KYTY_PREPARE_HOLD_MS' not in env,", 'no_hold=True,'),
    ('title_n', "(tot['pres_title_n'] > 0", '(True'),
    ('title_cap', 'TITLE_WALL_MAX_NS = 60000', 'TITLE_WALL_MAX_NS = 60001'),
    ('title_cap_lt', "<= TITLE_WALL_MAX_NS * tot['pres_title_n']", "< TITLE_WALL_MAX_NS * tot['pres_title_n']"),
    ('title_wall', "and tot['pres_title_ns'] <= TITLE_WALL_MAX_NS * tot['pres_title_n']),", 'and True),'),
    ('ov_sum', "tot['present_overlap'] == 0 and ", ''),
    ('ov_lines', " and overlap_lines == 0,", ','),
    ('ov_collect', '                overlap_lines += 1', '                overlap_lines += 0'),
    ('b_binary', "boot_binary=bmeta.get('binary_sha256') == BUILD_SHA,", 'boot_binary=True,'),
    ('b_pin_list', 'bpin == [True]', 'True in bpin'),
    ('b_pin_mode', "bpin.append(line.startswith(b'GpuClockPin: mode 1'))", 'bpin.append(True)'),
    ('b_pin_env', " and benv.get('KYTY_GPU_CLOCK_PIN') == '1',", ','),
    ('b_hold_env', "boot_hold_env=benv.get('KYTY_PREPARE_HOLD_MS') == str(HOLD_MS),", 'boot_hold_env=True,'),
    ('b_sched', "boot_no_schedule='KYTY_GATE_SCHEDULE' not in benv,", 'boot_no_schedule=True,'),
    ('b_ckpt', "boot_no_checkpoints='KYTY_GPU_CHECKPOINTS' not in benv,", 'boot_no_checkpoints=True,'),
    ('b_shift', "boot_no_shift='KYTY_BUFFER_GC_TRIGGER_SHIFT_MB' not in benv,", 'boot_no_shift=True,'),
    ('b_att_len', 'len(batts) == 1 and ', ''),
    ('b_att_ok', ' and len(bok) == 1,', ','),
    ('b_att_exit', "bok = [a for a in batts if a.get('outcome') == 'ok' and a.get('hold_exit') is None]",
     "bok = [a for a in batts if a.get('outcome') == 'ok']"),
    ('b_def_daslot', "('daslot', 'daguard',", "('daguard',"),
    ('b_def_daguard', "'daslot', 'daguard', 'cspfree'", "'daslot', 'cspfree'"),
    ('b_def_cspfree', "'daguard', 'cspfree', 'bdanarrow'", "'daguard', 'bdanarrow'"),
    ('b_def_bdanarrow', "'cspfree', 'bdanarrow', 'titleasync'", "'cspfree', 'titleasync'"),
    ('b_def_titleasync', "'bdanarrow', 'titleasync')", "'bdanarrow')"),
    ('b_def_all', "boot_default_runs=all(' %s=' % k not in bgates for k in BOOT_DEFAULTS),",
     'boot_default_runs=True,'),
    ('b_hold_line', "bholds == ['PrepareHold: ms=%d' % HOLD_MS]", 'len(bholds) == 1'),
    ('b_hold_collect', "bholds.append(line.decode('utf-8', 'replace').strip())", 'pass'),
    ('hold_ms', 'HOLD_MS = 10000', 'HOLD_MS = 9999'),
    ('b_wait_count', 'len(bwaits) == 1 and ', ''),
    ('b_wait_gt', 'bwaits[0] >= HOLD_MS', 'bwaits[0] > HOLD_MS'),
    ('b_wait_any', 'bwaits[0] >= HOLD_MS', 'bwaits[0] >= 0'),
    ('b_rows', 'brows >= MIN_ROWS and ', ''),
    ('b_rows_missing', ' and bmissing == 0,', ','),
    ('b_ov_lines', 'bov_lines == 0 and ', ''),
    ('b_ov_sum', ' and bov_sum == 0,', ','),
    ('b_ov_collect', '                bov_lines += 1', '                bov_lines += 0'),
    ('b_marker', 'boot_no_marker=not bmarkers,', 'boot_no_marker=True,'),
    ('b_stdout', '    if bso.is_file():', '    if False:'),
    ('all_merge', "res['checks'].update(boot['checks'])", 'pass'),
    ('all_verdict', "res['verdict'] = 'PASS' if all(res['checks'].values()) else 'FAIL'",
     "res['verdict'] = res['verdict']"),
    ('vid_binary', "binary=meta.get('binary_sha256') == BUILD_SHA,", 'binary=True,'),
    ('vid_ok_exit', "ok_att = [a for a in atts if a.get('outcome') == 'ok' and a.get('hold_exit') is None]",
     "ok_att = [a for a in atts if a.get('outcome') == 'ok']"),
    ('ov_mid', "if line.find(b'PresentOverlap:') >= 0:", "if line.startswith(b'PresentOverlap:'):"),
    ('b_ov_mid', "if b'PresentOverlap:' in line:", "if line.startswith(b'PresentOverlap:'):"),
    ('adm_idle_vid', 'adm_idle_vid=idle_ok(meta))', 'adm_idle_vid=True)'),
    ('adm_idle_boot', 'adm_idle_boot=idle_ok(bmeta),', 'adm_idle_boot=True,'),
    ('idle_max', 'IDLE_GPU_MAX = 10', 'IDLE_GPU_MAX = 11'),
    ('idle_le', 'v <= IDLE_GPU_MAX', 'v < IDLE_GPU_MAX'),
    ('idle_type', 'isinstance(v, (int, float)) and ', ''),
    ('park_min', 'bpark >= HOLD_MS * 1000', 'bpark >= HOLD_MS * 999'),
    ('park_gt', 'bpark >= HOLD_MS * 1000', 'bpark > HOLD_MS * 1000'),
    ('park_none', 'bpark is not None and ', ''),
    ('park_after_wait', 'if ml and bwaits and bpark is None:', 'if ml and bpark is None:'),
    ('park_first', 'if ml and bwaits and bpark is None:', 'if ml and bwaits:'),
    ('prog_lines', 'len(bprog) >= PROG_MIN_LINES', 'len(bprog) >= 1'),
    ('prog_lines_c', 'PROG_MIN_LINES = 9', 'PROG_MIN_LINES = 10'),
    ('prog_ms', 'max(bprog) >= PROG_MIN_MS', 'max(bprog) >= 0'),
    ('prog_ms_c', 'PROG_MIN_MS = 9000', 'PROG_MIN_MS = 9001'),
    ('prog_collect', 'bprog.append(int(mp.group(1)))', 'bprog.append(99999)'),
    ('adm_verdict', "    if not res['admitted']:", '    if False:'),
    ('adm_filter', "k.startswith('adm_')", "k.startswith('adm_x')"),
]
killed = 0
for name, old, new in MUTANTS:
    if SRC.count(old) != 1:
        print('%-14s ANCHOR x%d' % (name, SRC.count(old)))
        continue
    path = STAGE / ('mut_check114_%s.py' % name)
    path.write_text(SRC.replace(old, new), encoding='utf-8', newline='\n')
    r = subprocess.run([sys.executable, 'C:/kyty/s114/test_check114.py', str(path)], capture_output=True, text=True)
    killed += r.returncode != 0
    print('%-14s %s' % (name, 'killed' if r.returncode != 0 else 'SURVIVED'))
    path.unlink()
print('killed %d of %d' % (killed, len(MUTANTS)))
