set(KYTY_GIT_VERSION "unknown")
set(KYTY_GIT_HASH "unknown")
set(KYTY_GIT_REVISION "unknown")
if(GIT_EXECUTABLE)
	execute_process(
		COMMAND "${GIT_EXECUTABLE}" describe --tags --always --dirty
		WORKING_DIRECTORY "${GIT_WORKING_DIRECTORY}"
		OUTPUT_VARIABLE KYTY_GIT_VERSION
		OUTPUT_STRIP_TRAILING_WHITESPACE
		RESULT_VARIABLE GIT_RESULT
		ERROR_QUIET
	)
	if(NOT GIT_RESULT EQUAL 0)
		set(KYTY_GIT_VERSION "unknown")
	endif()

	execute_process(
		COMMAND "${GIT_EXECUTABLE}" rev-parse HEAD
		WORKING_DIRECTORY "${GIT_WORKING_DIRECTORY}"
		OUTPUT_VARIABLE KYTY_GIT_REVISION
		OUTPUT_STRIP_TRAILING_WHITESPACE
		RESULT_VARIABLE GIT_HASH_RESULT
		ERROR_QUIET
	)
	if(NOT GIT_HASH_RESULT EQUAL 0)
		set(KYTY_GIT_HASH "unknown")
		set(KYTY_GIT_REVISION "unknown")
	else()
		string(SUBSTRING "${KYTY_GIT_REVISION}" 0 7 KYTY_GIT_HASH)
		execute_process(
			COMMAND "${GIT_EXECUTABLE}" diff-index --quiet HEAD --
			WORKING_DIRECTORY "${GIT_WORKING_DIRECTORY}"
			RESULT_VARIABLE GIT_DIRTY_RESULT
			ERROR_QUIET
		)
		if(NOT GIT_DIRTY_RESULT EQUAL 0)
			string(APPEND KYTY_GIT_HASH "-dirty")
		endif()
	endif()
endif()
# Content hash of the shader translator sources: the shader translation cache is keyed by it,
# so commits elsewhere in the emulator keep the cache valid.
set(KYTY_SHADER_SOURCE_HASH "unknown")
if(SHADER_SOURCE_DIR)
	file(GLOB_RECURSE SHADER_SOURCES LIST_DIRECTORIES false
		"${SHADER_SOURCE_DIR}/*.cpp" "${SHADER_SOURCE_DIR}/*.h" "${SHADER_SOURCE_DIR}/*.inc")
	list(APPEND SHADER_SOURCES ${SHADER_CACHE_EXTRA_FILES})
	list(SORT SHADER_SOURCES)
	set(SHADER_DIGESTS "")
	foreach(SHADER_SOURCE IN LISTS SHADER_SOURCES)
		if(EXISTS "${SHADER_SOURCE}")
			file(SHA1 "${SHADER_SOURCE}" SHADER_DIGEST)
			string(APPEND SHADER_DIGESTS "${SHADER_DIGEST}\n")
		endif()
	endforeach()
	string(SHA1 KYTY_SHADER_SOURCE_HASH "${SHADER_DIGESTS}")
endif()
configure_file("${INPUT_FILE}" "${OUTPUT_FILE}")
